---
title: "Curriculum vitae"
author: "Daniel Fuller"
date: '2020-08-03'
output:
  html_document: 
    keep_md: yes
    toc: true
    toc_depth: 2
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Daniel Fuller, Ph.D.  
Canada Research Chair in Population Physical Activity  
Assistant Professor  
School of Human Kinetics and Recreation   
Physical Education Building PE 2024 Memorial   
University of Newfoundland St. John’s, NL  
A1C 5S7  
Tel: (709) 864-7270    
E-mail: dfuller@mun.ca    
Web: [http://www.walkabilly.ca/](http://www.walkabilly.ca/)  

## <span style="color:#81112c">Personal</span>

Date of Birth: January 10, 1982  
Citizenship: Canadian  
Address: 176 Patrick Street, St. John’s, NL, A1C 5C4  
Email: dfuller@mun.ca  
Website: [www.walkabilly.ca](http://walkabilly.ca/home/)  
Twitter: [walkabilly](https://twitter.com/walkabilly)  
Facebook: [walkabilly](https://twitter.com/walkabilly)  

### <span style="color:#81112c">Languages</span>

* English (read, write, speak, peer review)
* French (read, write, speak, peer review)

### <span style="color:#81112c">Education</span>

* 2014:	Post-Doctoral Fellowship, University of Saskatchewan, Saskatoon, Saskatchewan, Canada 
* 2012: 	Ph.D. Public Health, Universite de Montreal, Montreal, Quebec, Canada
* 2008:	M.Sc. Kinesiology, University of Saskatchewan, Saskatoon, Saskatchewan, Canada
* 2006: 	B.Sc. Kinesiology, University of Saskatchewan, Saskatoon, Saskatchewan, Canada 

### <span style="color:#81112c">Additional Education</span>
* 2011:	International Internship, Dr. Steven Cummins, Queen Mary University of London 
* 2009:	Canadian Institute of Health Research Summer Institute, McMaster University, Hamilton, Ontario
* 2008:	NCCP (National Coaching Certification Program) Competitive Development Coach, Canoe/Kayak 

### <span style="color:#81112c">Appointments and Promotions</span>

| Period | Appointment | Rank | Unit | Institution | 
|--------|-------------|------|------|-------------|
| 2016 - Ongoing | Primary |	Assistant Professor | School of Human Kinetics and Recreation | Memorial University |
| 2016 - Ongoing |	Cross Appointment | Assistant Professor | Community Health and Humanities | Memorial University |
| 2016 - Ongoing |	Cross Appointment | Assistant Professor | Department of Computer Science | Memorial University |
| 2016 - Ongoing | | Adjunct Professor | Department of Community Health and Epidemiology | University of Saskatchewan |
| 2015 - 2016 |	Term | Assistant Professor | School of Public Health | University of Saskatchewan |

### <span style="color:#81112c">Professional Memberships</span>

 * Canadian Public Health Association
 * International Society for Behavioral Nutrition and Physical Activity
 * International Society for Physical Activity and Health

### <span style="color:#81112c">Leaves</span>

* 2016:	Parental Leave (May 1, 2016 to July 30, 2016)
* 2013:	Parental Leave (July 1, 2013 to December 1, 2013)

### <span style="color:#81112c">Awards and Honours</span>

| Year | Award | Funder | Amount | 
|------|-------|--------|--------|
| 2016 | Canada Research Chair (Tier 2) | CIHR | $500,000 |
| 2012 | Travel Award | CIHR Institute of Population and Public Health | $900 |
| 2012 | Top Post-Doctoral Fellowship Award (Socio-Health) | Saskatchewan Health Research Foundation | $0 |
| 2012 | Top Post-Doctoral Fellowship Award (Socio-Health) | Saskatchewan Health Research Foundation | $0 |
| 2012 | Post-Doctoral Fellowships | CIHR | $45,000 * 2 years |
| 2012 | Post-Doctoral Fellowships | Saskatchewan Health Research Foundation | $10,000 |
| 2012 | Meritorious Student Abstract | Society for Behavioral Medicine Conference | $0 |
| 2012 | Student Travel Award | United Kingdom Medical Research Council | $1000 |
| 2011 | Dr. John Hastings Award | Canadian Public Health Association | $0 |
| 2012 | Travel Award | CIHR Institute of Population and Public Health | $1800 |
| 2010 | Michael Smith Foreign Study Supplement | Social Science and Humanities Research Council of Canada | $6000 |
| 2010 | Student Presentation Award | International Conference on Urban Health | $0 |
| 2010 | International Conference Scholarship | Department of Social and Preventive Medicine, Universite de Montreal | $1500 |
| 2008 | Joseph-Armand Bombardier Scholarship | Social Science and Humanities Research Council of Canada | $30,000 * 4 years |
| 2007 | First Place Poster | University of Saskatchewan Life & Health Science Research Conference | $0 |
| 2007 | College of Kinesiology Graduate Scholarship | University of Saskatchewan | $15,000 * 2 years |
| 2006 | Centennial Leadership Award | Government of Saskatchewan | $0 |
| 2005 | Book Award | College of Kinesiology, University of Saskatchewan | $500 |

## <span style="color:#81112c">Publications</span>

## <span style="color:#81112c">Peer Reviewed</span>

Trainees supervised/co-supervised by Daniel Fuller _italics_  
Daniel Fuller __bold__  

1. _Lotoski L_, **Fuller D**, Stanley K, Rainham D, Muhajarine N.The effect of season and neighbourhood built environment on GPS-derived home area sedentary behaviour in 9-14 year old children. 2021. International Journal of Environmental Research and Public Health. 2021, 18(4), 1968 [https://doi.org/10.3390/ijerph18041968](https://doi.org/10.3390/ijerph18041968).
1. Whitehurst, D., DeVries, D., __Fuller, D.__, Winters, M. An economic analysis of health-related benefits of bicycle infrastructure investment in three Canadian cities. 2021. PLOS One. 2021, 16(2): e0246419. [https://doi.org/10.1371/journal.pone.0246419](https://doi.org/10.1371/journal.pone.0246419)
1. Firth CL, Poirier Stephens Z,  Cantinotti, M,  __Fuller D,__ Kestens Y, Winters M. Successes and failures of built environment interventions: using concept mapping to assess stakeholder perspectives in four Canadian cities. Social Science and Medicine. 2021;268:113383. [https://doi.org/10.1016/j.socscimed.2020.113383](https://doi.org/10.1016/j.socscimed.2020.113383)
1. Bree. S., __Fuller. D.__, Diab, E. Access to Transit? Validating Local Transit Accessibility Measures Using Transit Ridership. Transportation Research Part A: Policy and Practice. 2020;141:430-442. [https://doi.org/10.1016/j.tra.2020.09.019](https://doi.org/10.1016/j.tra.2020.09.019)
1. _Hosford, K._ Laberee, K. __Fuller, D.__ Kestens, Y. Winters, M. Are They Really Interested but Concerned? A Mixed Methods Exploration of the Geller Bicyclist Typology. Transportation Research Part F: Psychology and Behaviour. 2020;75:26-36. [https://doi.org/10.1016/j.trf.2020.09.018](https://doi.org/10.1016/j.trf.2020.09.018)
1. __Fuller, D.__, Colwell, E., Low, J., _Orychock, K._, _Tobin, M._, _Simango, B._, Buote, R., _van Heerden, D._, _Slade, L._, _Luan, H._, _Taylor, G. A. N._, Cullen, K. Systematic Review of the Reliability and Validity of Commercially Available Wearable Devices for Measuring Steps, Energy Expenditure, and Heart Rate. JMIR MHealth. JMIR Mhealth Uhealth 2020;8(9):e18694. [http://dx.doi.org/10.2196/18694](http://dx.doi.org/10.2196/18694)
1. Brandon Calles M, Hosford K, Winters M, Gauvin L, __Fuller D__. The impact of implementing public bicycle share programs on bicycle crashes: the International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). Transport Findings. 2020. September. [https://doi.org/10.32866/001c.16724](https://doi.org/10.32866/001c.16724)
1. _Roy A_, __Fuller D__, Stanley K, Nelson T. Classifying Transportation Mode from Global Positioning Systems and accelerometer data: A machine learning approach. Transport Findings. 2020. September. [https://doi.org/10.32866/001c.14520](https://doi.org/10.32866/001c.14520)
1. Nelson, T., Ferster, C., Laberee, K. __Fuller, D.__, Winters, M. Crowdsourced data for bicycling research and practice. Transport Reviews. 2020.  [https://doi.org/10.1080/01441647.2020.1806943](https://doi.org/10.1080/01441647.2020.1806943)
1. Firth CL, __Fuller D,__ Wasfi R, Kestens Y, Winters M. Causally speaking: challenges in measuring gentrification for population health research. Health & Place. 2020. 63, 102350. [https://doi.org/10.1016/j.healthplace.2020.102350](https://doi.org/10.1016/j.healthplace.2020.102350)  
1. Auchincloss, A., Michael, Y., __Fuller, D.__, Li, S., Niamatullah, S., Fillmore, C., Setubal, C.,  Bettigole, C. Designing bikeshare to promote equity: baseline analysis of the Drexel Neighborhood Transportation Study (DNTS) cohort. Journal of Transportation and Health. 2020, 16, 100836. [https://doi.org/10.1016/j.jth.2020.100836](https://doi.org/10.1016/j.jth.2020.100836)
1. _Zhang R_, Stanley K, **Fuller D,** Bell S. Differentiating Population Spatial Behavior using Representative Features of Geospatial Mobility (ReFGeM). Transactions on Spatial Algorithms and Systems. 2020:6(1). [https://dl.acm.org/doi/10.1145/3362063](https://dl.acm.org/doi/10.1145/3362063)
1. _Hosford, K._, Winters, M., Gauvin, L., Camden, A., Dube, A-S., Friedman, S. M., __Fuller, D.__. Evaluating the impact of implementing public bicycle share programs on cycling: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Journal of Behavioural Nutrition and Physical Activity. 2019:16, 107. [https://doi.org/10.1186/s12966-019-0871-9](https://doi.org/10.1186/s12966-019-0871-9)
1. _Hosford, K._, Winters, M., __Fuller, D.__. Commentary on: Burn Calories, Not Fuel! The effects of bikeshare programs on obesity rates. Transportation Research Part D: Transport and Environment. 2019:75, 121-122. [https://doi.org/10.1016/j.trd.2019.08.028](https://doi.org/10.1016/j.trd.2019.08.028) 
1. __Fuller, D.__, Stanley, K. G. The future of activity space and health research. Journal of Health and Place. 2019:58, 102131. [https://doi.org/10.1016/j.healthplace.2019.05.009](https://doi.org/10.1016/j.healthplace.2019.05.009)
2. Thigpen, C. Winters, M. **Fuller, D.** Gauvin, L. Therrien, Nelson, T. Who is ready to bicycle?: Categorizing and mapping bicyclists with behavior change theory. Transport Policy. 2019:83, 11-17. [https://doi.org/10.1016/j.tranpol.2019.07.011](https://doi.org/10.1016/j.tranpol.2019.07.011)
3. Engler-Stringer, R. **Fuller, D.** Abeykoon, A.M. H. Olauson, C. Muhajarine, N. Perspectives on the Failure of New Grocery Store Interventions in Former Food Deserts. Health Education and Behaviour. 2019, 45(5). [https://doi.org/10.1177/1090198119853009](https://doi.org/10.1177/1090198119853009)
4. *Breslin, S.*, Shareck, M., **Fuller, D.** Research ethics for mobile sensing device use by vulnerable populations. Social Science and Medicine. 2019;232:50-57. [https://doi.org/10.1016/j.socscimed.2019.04.035](https://doi.org/10.1016/j.socscimed.2019.04.035)
5. __Fuller, D.,__ *Luan, H.,* Buote, R., Auchincloss, A. H. Impact of a public transit strike on public bicycle share use: An interrupted time series natural experiment study. Journal of Transportation and Health. 2019;13:137-142. [https://doi.org/10.1016/j.jth.2019.03.018](https://doi.org/10.1016/j.jth.2019.03.018)
6. *Luan, H*., *Ramsay, D.*, **Fuller, D.** Household income, active travel, and their interacting impact on body mass index in a sample of urban Canadians: A Bayesian spatial analysis. International Journal of Health Geographics. 2019;18(4). [https://doi.org/10.1186/s12942-019-0168-x](https://doi.org/10.1186/s12942-019-0168-x)
7. Branion-Calles M, Nelson T, **Fuller D**, Gauvin L, Winters M. Associations between spatial access to bicycle-specific infrastructure, sociodemographic characteristics, and city-wide safety perceptions of bicycling: a cross-sectional survey of bicyclists in 6 Canadian and U.S. cities. Transportation Research Part A: Policy and Practice. 2019, 123: 229-239. [https://doi.org/10.1016/j.tra.2018.10.024](https://doi.org/10.1016/j.tra.2018.10.024) 
8. Kestens Y, Winters M, **Fuller D,** Bell S, Berscheid J, Brondeel R, Cantinotti M, Datta G, Gauvin L, Gough M, Laberee K, Lewis P, Lord S, Luan H, McKay H, Morency C, Muhajarine N, Nelson T, Ottoni C, Poirier Stephens Z, Pugh C, Rancourt G, Shareck M, Sims-Gould J, Sones M, Stanley K, Thierry B, Thigpen C, Wasfi R. INTERACT: A comprehensive approach to assess urban form interventions through natural experiments. BMC Public Health. 2019;19(1):51. [https://doi.org/10.1186/s12889-018-6339-z](https://doi.org/10.1186/s12889-018-6339-z)
9. __Fuller D__, Neudorf J, Lockhart S, Plante C, Roberts H, Bandara T, Neudorf C. Individual- and area-level socioeconomic inequalities in diabetes mellitus in Saskatchewan between 2007 and 2012: a cross-sectional analysis. Canadian Medical Association Journal Open. 2019;7(1):E33-E39. [https://doi.org/10.9778/cmajo.20180042](https://doi.org/10.9778/cmajo.20180042)
11. *Hosford, K*., Lear, S A., **Fuller, D**., Teschke, Therrien, S., Winters. Who is in the near market for bicycle sharing? Identifying current, potential, and unlikely users of a public bicycle share program in Vancouver, Canada. BMC Public Health. 2018, 18: 1326. [https://doi.org/10.1186/s12889-018-6246-3](https://doi.org/10.1186/s12889-018-6246-3)
11. Winters M, Fischer J, **Fuller D**, Gauvin L, Whitehurst DGT, Nelson T. Equity In Spatial Access To Bicycling Infrastructure In Mid-Sized Canadian Cities. Transportation Research Board. 2018, 2672:36. [https://doi.org/10.1177/0361198118791630](https://doi.org/10.1177/0361198118791630) 
12. *Hosford, K*., **Fuller, D**., Lear, S A., Teschke, K., Gauvin, L., Brauer, M., Winters. Evaluation of the impact of a public bicycle share program on population bicycling in Vancouver, BC. Preventive Medicine Reports. 2018, 12:176-181. [https://doi.org/10.1016/j.pmedr.2018.09.014](https://doi.org/10.1016/j.pmedr.2018.09.014) 
13. Winters M, Branion-Calles M, Therrien S, **Fuller D**, Gauvin L, Whitehurst DGT, & Nelson T. Impacts of Bicycle Infrastructure in Mid-Sized Cities (IBIMS): protocol for a natural experiment study in three Canadian cities. BMJ Open 2018;8:e019130. [https://dx.doi.org/10.1136/bmjopen-2017-019130](https://dx.doi.org/10.1136/bmjopen-2017-019130)
14. *Alphonsus, K.*, Waldner, C., **Fuller D**. Examining the Association between Area Level Deprivation and Vehicle Collisions. Canadian Journal of Public Health. 2018, 109:43–51. [https://dx.doi.org/10.17269/s41997-018-0036-7](https://dx.doi.org/10.17269/s41997-018-0036-7)
15. Brook JR, Setton EM, Seed E, Shooshtari M, Doiron D, and the CANUE – The Canadian Urban Environmental Health Research Consortium. The Canadian Urban Environmental Health Research Consortium – a protocol for building a national environmental exposure data platform for integrated analyses of urban form and health. BMC Public Health. 2018, 18:114. [https://doi.org/10.1186/s12889-017-5001-5](https://doi.org/10.1186/s12889-017-5001-5)
16. Sones M, **Fuller D**, Kestens Y, Winters M. If we built it, who will come? The case for attention to equity in healthy community design. British Journal of Sports Medicine. 2018, 53(8). [http://dx.doi.org/10.1136/bjsports-2018-099667](http://dx.doi.org/10.1136/bjsports-2018-099667)
22. Pabayo, R., **Fuller, D.**, Lee, E.Y., Horino, M., Kawachi, I. State-level income inequality and meeting physical activity guidelines; differential associations among US men and women, Journal of Public Health. 2018, 2:229–236. [https://doi.org/10.1093/pubmed/fdx082](https://doi.org/10.1093/pubmed/fdx082)
18. **Fuller D.**, Winters M. Income inequalities in Bike Score and bicycle to work mode share in Canadian cities. Journal of Transportation and Health. 2017, 7(B): 264-268. https://doi.org/10.1016/j.jth.2017.09.005 
18. **Fuller D.**, Shareck M, Stanley C. Ethical implications of tracking participants for health research studies with mobile sensing devices. Social Science and Medicine. 2017, 191, 84-88 [https://doi.org/10.1016/j.socscimed.2017.08.043](https://doi.org/10.1016/j.socscimed.2017.08.043)
19. **Fuller, D.**, Buote, R., Stanley, K. A Glossary for Big Data in Population and Public Health: Discussion and Commentary on Terminology and Research Methods. Journal of Epidemiology and Community Health. 2017, 71:1113-1117. [http://dx.doi.org/10.1136/jech-2017-209608](http://dx.doi.org/10.1136/jech-2017-209608) 
20. *Hasselback*, J., Schwandt, M., **Fuller, D.** Choosing Tools for Building Health Spaces: A Global Overview. Cities and Health. 2017, 1: 31-37. [http://dx.doi.org/10.1080/23748834.2017.1309091](http://dx.doi.org/10.1080/23748834.2017.1309091)
21. McGowan, E., **Fuller, D.**, Cutumisu, N., North, S., & Courneya, K. Examining Whether Built Environment Factors are Effect Modifiers in a Randomized Controlled Trial to Increase Physical Activity among Men with Prostate Cancer: The PROMOTE Trial. Supportive Care in Cancer. 2017, 25(10), 2993–2996. [https://doi.org/10.1007/s00520-017-3798-1](https://doi.org/10.1007/s00520-017-3798-1)
23. Pabayo, R., **Fuller, D.**, Goldstein, R.B., Kawachi, I., Gilman, S.E. Income inequality among American states and the conditional risk of post-traumatic stress disorder. Soc Psychiatry Psychiatr Epidemiol 2017, 52: 1195. [https://doi.org/10.1007/s00127-017-1413-x](https://doi.org/10.1007/s00127-017-1413-x) 
25. **Fuller, D.**, Engler-Stringer, R., Muhajarine, N. Retail food environments research: Promising future with more work to be done. Canadian Journal of Public Health. 2016, 107(0): 5622. [http://dx.doi.org/10.17269/cjph.107.5622](http://dx.doi.org/10.17269/cjph.107.5622)
25. Sullivan, E., **Fuller, D.**, Paterson, Q. S., Huffman, S., Challa, S., Woods, R. Emergency Physicians as human billboards for injury prevention: A randomized controlled trial. Canadian Journal of Emergency Medicine. 2016, 19(4):277-284. [http://dx.doi.org/10.1017/cem.2016.366](http://dx.doi.org/10.1017/cem.2016.366)
26. Winters, M., Teschke, K., Brauer, M., **Fuller, D.** Bike Score®: Associations between urban bikeability and cycling behavior in 24 cities. International Journal of Behavioral Nutrition and Physical Activity. 2016, 13:18 [https://doi.org/10.1186/s12966-016-0339-0](https://doi.org/10.1186/s12966-016-0339-0) 
27. **Fuller, D.**, Neudorf, J., Bermedo-Carrasco, S., Neudorf, C. Classifying the population by socio-economic factors associated with support for policies to reduce social inequalities in health. Journal of Public Health.  2016, 38(4), 635-643. [http://www.dx.doi.org/10.1093/pubmed/fdv201](http://www.dx.doi.org/10.1093/pubmed/fdv201) 
31. **Fuller, D.**, Engler-Stringer, R., Muhajarine, N. Examining food purchasing patterns from sales data at a full-service grocery store intervention in a former food desert. Preventive Medicine Reports. 2015, 2:164-169. [https://doi.org/10.1016/j.pmedr.2015.02.012](https://doi.org/10.1016/j.pmedr.2015.02.012)
29. Neudorf, C., **Fuller, D.**, Cushon, J., Glew, R., Turner, H., Ugolini, C. An analytic approach for describing, prioritizing and acting on health inequities at the local level in Canada. CMAJ Open. 2015, 3(4): E366-E372. [http://www.dx.doi.org/10.9778/cmajo.20150049](http://www.dx.doi.org/10.9778/cmajo.20150049) 
29. Muhajarine, N., Katapally, T R., **Fuller, D.**, Stanley, K., Rainham, D. Longitudinal active living research to address obesity in children in transition from preadolescence to adolescence. BMC Public Health. 2015, 15:495 [https://doi.org/10.1186/s12889-015-1822-2](https://doi.org/10.1186/s12889-015-1822-2) 
30. Therrien, S., Winters, M., Teschke, K., **Fuller, D.**, Gauvin, L., Brauer, M. Investigation population-level readiness to use a public bike share systems in Vancouver, BC. Transportation Research Record. 2014, (2468):74-83. [http://docs.trb.org/prp/14-3524.pdf](http://docs.trb.org/prp/14-3524.pdf)
33. **Fuller, D.**, Shareck, M. Canada Post community mailboxes: Implications for health research. Canadian Journal of Public Health. 2014, 105(6):e453-e455. [http://dx.doi.org/10.17269/cjph.105.4721](http://dx.doi.org/10.17269/cjph.105.4721)
33. **Fuller, D.**, Pabayo, R. The relationship between utilitarian walking, utilitarian cycling, and body mass index in a population based cohort study of adults: Comparing random intercepts and fixed effects models. Preventive Medicine. 2014, 69:261-266. [https://doi.org/10.1016/j.ypmed.2014.10.022](https://doi.org/10.1016/j.ypmed.2014.10.022) 
34. **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teschke, K., Russo, E. T., Camden, A., Mee, C., Friedman, S. M. Evaluating the impact of environmental interventions across 2 countries: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS) Study protocol. BMC Public Health. 2014, 14:1103. [https://doi.org/10.1186/1471-2458-14-1103](https://doi.org/10.1186/1471-2458-14-1103) 
35. Belanger-Gravel, A., **Fuller, D.**, Gauvin, L., Drouin, L. Implementing a Public Bicycle Share Program: Impact on Perceptions and Support for Public Policies for Active Transportation. Journal of Physical Activity and Health. 2014, 12(4),  477-482. [https://doi.org/10.1123/jpah.2013-0206](https://doi.org/10.1123/jpah.2013-0206)
36. Belanger-Gravel, A., **Fuller, D.**, Gauvin, L., Drouin, L. Association of implementation of a public bicycle share program with intention and self-efficacy: The moderating role of socioeconomic status. Journal of Health Psychology. 2014, 21(6):944-53. [https://doi.org/10.1177/1359105314542820](https://doi.org/10.1177/1359105314542820) 
38. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., & Drouin, L. Impact of implementing a public bicycle share program on the likelihood of collisions and quasi-collisions in Montreal, Canada. Preventive Medicine. 2013, 57(6):920–924. [https://doi.org/10.1016/j.ypmed.2013.05.028](https://doi.org/10.1016/j.ypmed.2013.05.028)
38. **Fuller, D.**, Morency, P. Could a population approach to traffic collisions influence road injury prevention and city planning? Journal of Environmental and Public Health.  2013, 3:1-5. [http://dx.doi.org/10.1155/2013/916460](http://dx.doi.org/10.1155/2013/916460)
39. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. The potential modal shift and health benefits of implementing a public bicycle share program in Montreal, Canada. International Journal of Behavioral Nutrition and Physical Activity,  2013, 10:66. [https://doi.org/10.1186/1479-5868-10-66](https://doi.org/10.1186/1479-5868-10-66)
40. **Fuller, D.** Focus on methods key for advancing population health intervention research. Canadian Journal of Public Health, 2013, 104(1) e95. [http://dx.doi.org/10.17269/cjph.104.3799](http://dx.doi.org/10.17269/cjph.104.3799)
41. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Impact evaluation of a public bicycle share program on cycling: A case example of BIXI in Montreal, Canada. American Journal of Public Health. 2013, 103(3):e85-92. [http://dx.doi.org/10.2105/AJPH.2012.300917](http://dx.doi.org/10.2105/AJPH.2012.300917) 
42.	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., & Drouin, L. Individual- and Area-Level Disparities in Access to the Road Network, Subway System, and a Public Bicycle Share Program on the Island of Montreal, Canada. Annals of Behavioral Medicine. 2013, 45(1), 95-100.  [http://dx.doi.org/10.1007/s12160-012-9433-y](http://dx.doi.org/10.1007/s12160-012-9433-y) 
43.	**Fuller, D.**, Cummins, S., Matthews S. A. Does transportation mode modify associations between distance to food store, fruit and vegetable consumption and BMI in low income neighborhoods? American Journal of Clinical Nutrition, 2013, 97(1), 167-72. [http://dx.doi.org/10.3945/ajcn.112.036392](http://dx.doi.org/10.3945/ajcn.112.036392) 
45. **Fuller, D.**, Teschke, K., Winters, M., Zanotto, M. (2012) Helmets and bicycling deaths: the importance of context. Canadian Medical Association Journal. 2012. [http://dx.doi.org/10.1503/cmaj.120988](http://www.cmaj.ca/content/184/17/E921/reply#cmaj_el_713394)
45. **Fuller, D.**, Gyurcsik, N.C., Spink, K.S., Brawley, L.R. Prospective examination of self-regulatory efficacy in predicting walking for active transportation: A social cognitive theory approach. Journal of Applied Social Psychology. 2012, 42 (12), 2817-2932. [http://dx.doi.org/10.1111/j.1559-1816.2012.00968.x](http://dx.doi.org/10.1111/j.1559-1816.2012.00968.x)
46. **Fuller, D.**, Potvin, L. Context by treatment interactions as the primary object of study in cluster randomized controlled trials of population health intervention. International Journal of Public Health. 2012, 57(3), 633-636. [http://dx.doi.org/10.1007/s00038-012-0357-x](http://dx.doi.org/10.1007/s00038-012-0357-x)
47.	**Fuller, D.**, Gauvin, L., Fournier, M., Kestens, Y., Daniel, M., Morency, P., & Drouin, L. Reliability and Validity of a Self-Report Measure of Favorability towards Active Living-Friendly Policies (ALF-P) in a Population-based, Cross-sectional Sample of Adults. Journal of Urban Health.  2012, 89(2), 258-269. [http://dx.doi.org/10.1007/s11524-011-9650-x](http://dx.doi.org/10.1007/s11524-011-9650-x)
48.	**Fuller, D.**, Sahlqvist, S., Cummins, S., Ogilvie, D. The impact of public transportation strikes on use of a bicycle share program in London: interrupted time series design. Preventive Medicine. 2012, 54, 74–76. [https://doi.org/10.1016/j.ypmed.2011.09.021](https://doi.org/10.1016/j.ypmed.2011.09.021)
50. **Fuller, D.**, Gauvin, L., Kestens, Y., Daniel, M., Fournier, M., Morency, P., & Drouin, L. Use of a New Public Bicycle Share Program in Montreal, Canada. American Journal of Preventive Medicine. 2011, 41(1), 80–83. [https://doi.org/10.1016/j.amepre.2011.03.002](https://doi.org/10.1016/j.amepre.2011.03.002)
50.	**Fuller, D.**, Sabiston, C., Karp, I., Barnett, T., O’Loughlin, J. School sport opportunities influence physical activity in secondary school and beyond. Journal of School Health, 2011, 81(8), 449-454. [https://doi.org/10.1111/j.1746-1561.2011.00613.x](https://doi.org/10.1111/j.1746-1561.2011.00613.x)
51.	**Fuller, D.**, Hobin, E. P., Hystad, P. & Shareck, M. (Joint Authorship). Challenges to interdisciplinary training for junior space, place and health researchers. Critical Public Health. 2011, 22(1), 1-7. [http://dx.doi.org/10.1080/09581596.2010.520010](http://dx.doi.org/10.1080/09581596.2010.520010)
52.	Meili, R., **Fuller, D.**, & Lydiate, J. Teaching Social Accountability by Making the Links: Qualitative evaluation of student experiences in a service-learning project. Medical Teacher. 2011, 33(8), 659-666. [http://dx.doi.org/10.3109/0142159X.2010.530308](http://dx.doi.org/10.3109/0142159X.2010.530308)
53.	**Fuller, D.**, Muhajarine, N., and Smart Cities, Healthy Kids Research Team. Replication of the Neighborhood Active Living Potential Measure in Saskatoon, Canada. American Journal of Preventive Medicine. 2010, 39(4), 364-367. [https://doi.org/10.1016/j.amepre.2010.05.015](https://doi.org/10.1016/j.amepre.2010.05.015)
54.	Gyurcsik, N.C., Brawley, L.R., Spink, K.S., Brittain, D.R., **Fuller, D.**, & Chad, K. Physical activity in women with arthritis: Examining perceived barriers and self-regulatory efficacy to cope. Arthritis Care and Research. 2009, 61(8), 1087-1094. [https://doi.org/10.1002/art.24697](https://doi.org/10.1002/art.24697)
55.	Forbes, S., **Fuller, D.**, Little, J.P., Krentz, J. Anthropometric and physiological predictors of flat-water 1000m kayak performance in young adolescents and the effectiveness of a high volume training camp. International Journal of Exercise Science. 2008, 2, 106-114. [http://digitalcommons.wku.edu/ijes/vol2/iss2/4/](http://digitalcommons.wku.edu/ijes/vol2/iss2/4/)
56.	Forbes, D. A., Bangma, J., Neilson, C., Forbes, J., **Fuller, D.**, & Furniss, S. Saskatchewan residents’ access to the Cochrane Library. Canadian Journal of Library and Information Practice and Research. 2007, 2(2).

### <span style="color:#81112c">Published Conference Papers</span>
1.	*Alfosool, A.M.S.*, Chen, Y., **Fuller, D.** Road Importance Using Complex-Networks, Graph Reduction & Interpolation. 2020 International Conference on Computing, Networking and Communications (ICNC). Hawaii, USA. February 2020. https://doi.org/10.1109/ICNC47757.2020.9049768 
2.	Zhang R, Stanley K, Bell S, **Fuller D.** A Feature Set for Spatial Behavior Characterization. SIG Spatial 2018: Proceedings of the 26th ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems. Seattle, USA. November 2018. https://doi.org/10.1145/3274895.3274973.


### <span style="color:#81112c">In Press Publications</span>
1. __Fuller D__, Rahimipour Anaraki J, _Simango B_, Dorani F, Bozorgi F, _Luan D_, Basset F. 2021. Predicting lying, sitting, walking, and running using Apple Watch and Fitbit data. BMJ Open Sport & Exercise Medicine.
1. Firth, C.L., Thierry, B., __Fuller, D.__, Winters, M., Kestens, Y. Gentrification, Urban Interventions, and Equity (GENUINE): a map-based gentrification tool for Canadian Metropolitan Areas. 2021. Health Reports.
4. Wasfi R, Poirier Stephens Z, Sones M, Laberee K, Gough M, Pugh C, __Fuller D__, Winters M, Kestens Y. Recruiting Participants for Population Health Intervention Research: Effectiveness and Costs of Recruitment Methods for the INTErventions, Research, and Action in Cities Team (INTERACT) study. Journal of Medical Internet Research. [http://www.doi.org/10.2196/preprints.21142](http://www.doi.org/10.2196/preprints.21142)
4. _Brondeel, R._, Kestens, Y., _Rahimipour Anaraki, J._, Stanley, K., Thierry, B., __Fuller, D.__ Converting raw accelerometer data to activity counts using open source code in MATLAB, Python, and R – a comparison to ActiLife activity counts. Journal for the Measurement of Physical Behaviour.
5. Alhassan J A K, Gauvin L, Muhajarine N, __Fuller D__. Enablers and Barriers to Multisectoral Collaboration: Evidence from a Midsized Canadian City. Canadian Journal of Public Health.


### <span style="color:#81112c">Submitted Publications Under Review</span>

#### Physical Activity Measurement 

1. _Khataeipour S_, Rahimipour Anaraki J, Bozorgi A, Rayner M, Basset F, __Fuller D__. Predicting Movement Types Using Smartphone Accelerometers at Three Different Wear Locations; Hands, Pants Pocket, Backpack. Frontiers in Computer Science. 
5. _Angarita-Fonseca A_, Trask C, Pahwa P, __Fuller D__, Bath B. Physical activity and chronic back disorders: A repeated measures analysis of a 16-year prospective cohort study. Preventive Medicine. Preventive Medicine..
6. _Angarita-Fonseca A_, Trask C, Pahwa P, Herman H, __Fuller D__, Bath B. Is meeting Canadian physical activity guidelines associated with Chronic Back Disorders? A comparison between self-reported and accelerometer-measured physical activity. Spine. 

#### Healthy Cities
1. __Fuller D__, Bell S, Firth C L, Muhajarine N, Nelson T, Stanley K S, Sones M, Smith J, Thierry B, Laberee K, Poirier Stephens Z, Philips K, Kestens Y, Winters M. Wave 1 results of the INTerventions, Research, and Action in Cities Team (INTERACT) cohort study: Examining the spatio-temporal measures for urban environments and health. Submitted to Health & Place. 
1. _Luan H_, __Fuller D__. Urban form in Canada at a small-area level: quantifying “compactness” and “sprawl” with Bayesian multivariate spatial factor analysis. Computers, Environment and Urban Systems.    
1. Firth C, Laberee K, **Fuller D**, Kestens Y, Winters M. Well-being glossary for healthy cities research. Landscape and Urban Planning.
1. Slaney J, Fuller D, Apparicio P, Gelb J. Examining the Relationship Between Ventilation and Exercise Intensity During a Field Study in Seven Major Cities. Submitted. Journal of Transport and Health.
3. __Fuller D__, _Tobin M_, _Orychock K_, Ross N, Hajna S, DeVries M, Villeneuve P J, Frank L D, McCormack G, Wasfi R, Steinmetz-Wood M, Gilliland J, Booth GL, Winters M, Kestens Y, Manaugh K, Rainham D, Gauvin L, Widener M J, Muhajarine N, _Luan H_. Active Living Environments: Re-Framing and Defining the Concept of Walkability. BMC Public Health. 
5. Sones M, Firth CL, __Fuller D__, Holden M, Kestens Y, Winters M. Situating social connectedness in healthy cities: A conceptual primer for research and policy. Cities and Health.
7. Parenteau, N., __Fuller, D.__, Najjar, M., Poirier Stephens, Z., Rancourt, G., Winters, M., Kestens, Y. Do travel modes contribute to well-being? A cross-sectional analysis considering enjoyment, gender, and education. Journal of Transport and Health.
10. Bird, M. Barnett, T.A. Mathieu, M-E. **Fuller, D.** Geetanjali D D. Multidimensional School Features Associated with Physical Activity among Youth at Risk of Obesity: An Exploratory Principal Component and Generalized Estimating Equation Analysis. Health and Place.
12. Alhassan J A K, Gauvin L, Judge A, __Fuller D__, Engler-Stringer R, Muhajarine R. Improving Health through Multisectoral Collaboration: Enablers and Barriers. Canadian Journal of Public Health

### <span style="color:#81112c">Letters to the Editor</span>
1. Paulsen, P., Fuller, D. Scrolling for data or doom during COVID-19?. Can J Public Health. 2020. 111, 490–491. [https://doi.org/10.17269/s41997-020-00376-5](https://doi.org/10.17269/s41997-020-00376-5)
1. Fuller, D., Potvin, L. Social media and the Canadian Journal of Public Health. Can J Public Health. 2020. 111, 149–150. [https://doi.org/10.17269/s41997-020-00301-w](https://doi.org/10.17269/s41997-020-00301-w)

### <span style="color:#81112c">Books or Book Chapters</span>

1.	Benmarhnia, T., **Fuller, D.**, McKinnon, B. (2018). Utilisation de methodes quasi experimentales pour evaluer l’effet de l’age egal minimum pour la consommation d'alcool sur la mortalite accidentelle chez les jeunes in Ridde, V., Dagenais, C. Eds.). 2015. Methodes avancees d’evaluation d’interventions de sante mondiale. *Code* here: https://github.com/walkabilly/methode_evaluation  
2. **Fuller, D.**, Hobin, E. Natural Experiments of Addressing Chronic Disease in Harrington, D. McLafferty, S. Elliott., J. (Eds.). 2016. Population Health Intervention Research: Geographical Perspective. Ashgate Books. 15 pages.

### <span style="color:#81112c">Published Abstracts</span>

1.	**Fuller, D.**, Gauvin, L., Kestens, Y. Sociodemographic correlates of public bicycle share program use: An intercept survey of users in Montreal, Canada. Journal of Science and Medicine in Sport. 2012, 15(6), S87.
1. **Fuller, D.**, Gauvin, L., Kestens, Y. Examining the spatial distribution and relationship between support for policies aimed at active living in transportation and transportation behavior. Annals of Behavioral Medicine. 2012, 43(S1), S153.
1. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Validity and Reliability of a Measure of Favorability to Active Living Friendly Policies. Annals of Behavioral Medicine. 2012, 39(S1), S62.
1. **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. Walking for active transportation: Using social cognitive theory to examine differences between successful and less successful users. Annals of Behavioral Medicine. 2009, 37(S1), S85.
1. **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. A prospective examination of social cognitive predictors of walking for active transportation. Journal of Sport and Exercise Psychology. 2009, 30, S146.
1. Bloomquist, C.D., **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S., & Bray, S.R. Active Transportation Use By Sufficiently and Insufficiently Active First-Year University Students. Annals of Behavioral Medicine. 2008, 35(S1), S218.
1. Gyurcsik, N.C., Brawley, L.R., Spink, K.S., Brittain, D.R., Chad, K., & **Fuller, D.** Managing arthritis using physical activity: Perceived barriers and self-regulatory efficacy predict activity in arthritic women. Annals of Behavioral Medicine. 2008, 35(S1), s28.

### <span style="color:#81112c">Technical Reports</span>

1. Holloway A, Chafe B, Fuller D.  Health and economic benefits of walking in St. John’s, Newfoundland and Labrador. [http://www.beaplab.com/home/wp-content/uploads/2020/08/HEAT-St-Johns.pdf](http://www.beaplab.com/home/wp-content/uploads/2020/08/HEAT-St-Johns.pdf)
1. Vanlaar W, Woods-Fry H, Mainegra Hing M, Robertson R, Laberee K, Ferster C, and  Nelson T. Bikemaps.org: Final report on the evaluation of a crowdsourced tool to compile, analyze and communicate data about cycling safety. 2020. Traffic Injury Research Foundation. 
1. Fuller D, Butt R. Report from the Bicycle Network Design Jam. 2018 ISBN: 978-0-88901-488-6. [http://www.beaplab.com/home/wp-content/uploads/2019/01/Design-Jam.pdf](http://www.beaplab.com/home/wp-content/uploads/2019/01/Design-Jam.pdf)
1. _Tobin M_, __Fuller D__. Developing Apps for Population Health Research. 2019. ISBN: 978-0-88901-487-9. [http://www.beaplab.com/home/wp-content/uploads/2019/01/App-Review.pdf](http://www.beaplab.com/home/wp-content/uploads/2019/01/App-Review.pdf)
1. Loucks-Atkinson, A, Yi, J.K., Hawkins, K., Loeffler, TA, **Fuller, D.** & Sullivan, A. 2017. A vision for an inclusive Newfoundland and Labrador. In R.E. Ommer, B. Neis, & D. Brake (Eds.), Asking the big questions: Reflections on a sustainable post oil-dependent Newfoundland and Labrador (pp. 46-54). St. John’s, NL: Harris Centre, Memorial University.
1. Neudrof, C., **Fuller, D.**, Neudorf, J., Lockhart, S., Plante, C., Williams-Roberts, H., Thurairasu, L. 2016. Changes in Social Inequalities in Health Over Time in Saskatchewan. [https://saskatchewanequitystudy.com/](https://saskatchewanequitystudy.com/)
1. **Fuller, D.**, Follwell, E. J., Jones, C., Sharp, K., Meili, R. 2015. Health in All Policies: Description of tools and practices with recommendations for the Government of Newfoundland and Labrador.
1. Neudorf, C., Kryzanowski, J., Marko, J., Ugolini C., Brown A., **Fuller, D.**, Murphy L. 2015. Better Health for All Series 6: Health behaviours and risk conditions. Saskatoon: Saskatoon Health Region. Accessed March 23, 2015: [https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2015_shr_series6_hsrfull.pdf](https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2015_shr_series6_hsrfull.pdf)
1. Neudorf, C., Kryzanowski, J., Turner, H., Cushon, J., **Fuller, D.**, Ugolini, C., Murphy, L., Marko, J. 2014. Better Health for All Series 3: Advancing Health Equity in Health Care. Saskatoon: Saskatoon Health Region. Accessed January 8, 2015: [https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2014_shr_phase3_advancing_healthequity_healthcare_series.pdf](https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2014_shr_phase3_advancing_healthequity_healthcare_series.pdf)

### <span style="color:#81112c">Blogs</span>
1. **Fuller, D.**, Huffman, S. This election can end Canada’s dark age. Upstream Blog. Accessed November 25, 2015 - [http://www.thinkupstream.net/darkage](http://www.thinkupstream.net/darkage).

## <span style="color:#81112c">Presentations</span>

### <span style="color:#81112c">Invited Presentations</span>
1. Friday December 4, 2020: **Fuller D**. The Health Costs and Benefits of Urban Planning. Atlantic Planners Institute.
1. Wednesday February 19, 2020: **Fuller D**. Emergency Panel on Pedestrian Safety in St. John's. Green New Drinks organized by the St. John's Social Justice Cooperative. 
1. Friday November 15, 2019: **Fuller D**. Canada Research Chair Panel on Health and Wellbeing. Memorial Univeristy of Newfoundland. 
1.  February 7-8, 2019: **Fuller D**. Methods development for cycling research in Canada. NSERC Workshop: Cycling Research Collaboration with Industry in Canadian Context. Calgary, Alberta. 
1. Friday October 26, 2018: **Fuller D**. Wearable Devices, Physical Activity, Machine Learning, and Automated Detection of Urban Environments. Urban Sustainability and Population Health: Turning Data into Insights. McGill University.
1.  February 8, 2018: **Fuller D**. Urban planning interventions to promote physical activity. Joint annual meeting of the Quebec Society of lipidology, nutrition and metabolism (SQLNM), the Cardiometabolic, Diabetes and Obesity network  (CMDO) and the Complications of Obesity at Laval and Sherbrooke Universities (COLosSUS). 
1. December 10, 2018. **Fuller D**. Urban Design for Healthy and Inclusive Cities. Knowledge Exchange on Universal Design and Social Procurement. Coalition of Persons with Disabilities Newfoundland and Labrador
1. May 10, 2018: **Fuller D**. Designing Health Cities Using Data and Policy. HKR Speaker Series, Memorial University of Newfoundland.
1. November 30, 2017: Kestens Y, **Fuller D**, Winters M. INTERACT: Interventions, Research and Action in Cities Team. CIHR-IPPH Healthy Cities Think Tank, Toronto, ON.
1. November 29, 2017: **Fuller D.** The Canadian Urban Environmental Health Research Consortium (CANUE). Urban Public Health Network Annual Meeting, Toronto, ON
1. November 21, 2017: **Fuller, D.** Family Medicine: A Population Approach with Health. Residency Research Day, Memorial Family Medicine. Memorial University.
1. September 28, 2017: Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax Baseline results. Presentation and meeting with local cycling advocates. Halifax Regional Municipality Transportation Standing Committee.
1. September 28, 2017: Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax Baseline results. Presentation and meeting with local cycling advocates. Representatives from the from the Halifax Cycling Coalition, Nova Social Cycles, Halifax Ecology Action Center, and Halifax Regional Health Authority.
1. September 25, 2017: **Fuller, D.** Cycling in Canadian Communities: From Planning to Implementation.  Invited oral presentation at the Transportation Association of Canada 2017 Fall Technical Meetings. St. John’s, Newfoundland
1. October 17, 2016: **Fuller, D.** Urban Environments and Health. Invited oral presentation at the Nexus Centre Urban Panel. St. John’s, Newfoundland
1. April 15, 2015:	**Fuller, D.** Bike share impacts on health. Ontario Public Health Association.
1. February 19, 2015: **Fuller, D.** Are we succeeding or failing to increase physical activity in the population? Memorial University of Newfoundland.
1. October 23, 2014: **Fuller, D.** Preliminary Results from the Saskatchewan Equity Study: Focus on Diabetes and Injury. Saskatchewan Epidemiological Association Conference.
1. October 10, 2014: **Fuller, D.** Cycling in Cities. Western Regional Training Program – University of Saskatchewan. 
1. July 17, 2013: **Fuller, D.** Cycling in Cities. Shad Valley – University of Saskatchewan. 
1. April 12, 2013: **Fuller, D.** Walkability and bikeability for community development. Literally PlaceMaking Conference, Centre for Civic Governance. 
1. March 26, 2013: **Fuller, D.** Les iniquites sociales en sante à Saskatoon entre 1998 et 2011. Forum du Savoir, ACFAS Saskatchewan. 
1. November 6, 2012: **Fuller, D.** Conceptual, methodological and statistical reflections on evaluating a natural intervention with the potential to increase cycling. Sansom Institute Lecture, University of South Australia. 
1. February 23, 2012: **Fuller, D.** Physical activity and public health: Do we speak the same language or are we miles apart. Russ Kisby Memorial Lecture, College of Kinesiology, University of Saskatchewan. 
1. April 9, 2011: **Fuller, D.** For a priori to post hoc and back again: A discussion on the planning process and evaluation of a complex intervention involving the implementation of a public bicycle share program in Montreal, Canada. Medical Research Council Epidemiology Research Seminar, Cambridge, England. 
1. March 30, 2011: **Fuller, D.** For a priori to post hoc and back again: A discussion on the planning process and evaluation of a complex intervention involving the implementation of a public bicycle share program in Montreal, Canada. London School of Hygiene and Tropical Medicine Complex Interventions Seminar, London, England. 
1. February 12, 2011: **Fuller, D.** Les Interventions Naturelles et la Sante: Le cas de BIXI. Association Francophone pour le Savoir, Saskatoon, Canada.
1. May 10, 2010: **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Facteurs comportementaux associes a la connaissance et l’utilisation des velos en libre-service : Potentiel pour la modification des habitudes de transport et l’augmentation du transport actif. Association Francophone pour le Savoir, Montreal, Canada.
1. October 1, 2010: **Fuller, D.** BIXI is the new fixie: The public bike share explosion in North American. TEDxMontrealQuartierLatin, Montreal, Canada.

### <span style="color:#81112c">Peer Reviewed Conferences</span>

1. _Maher, R.A._, Wadden, K., Twells, L., Basset, F., Murphy, S., Murphy, F., Fuller, D., McGowan, E. Exercise Interventions and Fertility Outcomes for Women Experiencing Obesity and Infertility: A Narrative Review. 7th Canadian Obesity Summit. Online.
1. Basset, R. Kelly, L. _Behnamfar, D._ Fuller, D. Self-chosen pace displays a better walking economy when expressed in caloric unit cost. Integrative Physiology of Exercise. American Physiological Association. 
1. Diaz F, Abbassi J, __Fuller D__, Diab E. Canadian Transit Agencies Response to COVID-19: Understanding Strategies, Information Accessibility and the Use of Social Media. Transportation Research Board Annual Meeting. 
1. 2020 April: __Fuller D__, Luan H, Alfosool A, Chen Y. Time weighted approaches for combining GPS and area level data to create individual exposure measures. American Association of Geographers. (Cancelled due to COVID-19). 
1. 2020 February: _Hosford K_, Laberee K, **Fuller D**, Kestens Y, Winters M. Are They Really Interested but Concerned? A Mixed Methods Exploration of the Geller Bicyclist Typology. Transportation Research Board Annual Meeting. 
1. 2020 February: _Bree S_, __Fuller D__, Diab E. Access to Transit? Validating Local Transit Accessibility Measures Using Transit Ridership.  Transportation Research Board Annual Meeting. 
1. 2019 July: **Fuller, D.** Re-visioning Transport and Health Conference and Hackathon. Cambridge, England. https://sites.google.com/view/transportcam2019/home/workshop
1. 2019 June: *Breslin, S.*, Shareck, M., **Fuller, D.** Research ethics for mobile sensing device use by vulnerable populations. At the Intersection of Culture and Method: Designing Feminist Action (DIS 2019).
1. 2019 April: **Fuller, D.**, Zhang, R., Bell, S., Stanely, K. Representative Features of Geospatial Mobility. American Association of Geographers Conference. Washington, DC.
1. 2018 October: Nolan, R., Burton, M., **Fuller, D.**. Smart Cities Challenge: Building a Healthy and Happy City through Collaboration. People, Place, Public Engagement Conference, Memorial University of Newfoundland.
1. 2018 October: **Fuller, D.**, Luan, H., Dorani, F., Rahimipour Anaraki, J., Beheshti Mohtasham, M. Predicting sleep, sedentary behaviour, and physical activity from commercially available wearable devices using Rotation Forest models. International Society for Physical Activity and Health. London, England. 
1. 2018 June: *Lotoski L*, **Fuller D**, Stanley K, Rainham D, Muhajarine N. Precipitation, demographics and built environment features are associated with sedentary behaviour in 9-14-year-old children. 5th International One Health Congress. Saskatoon, Saskatchewan.
1. 2018 June: Mooney, S J. **Fuller, D.** Westreich, J D. Data Sharing in Big Data Epidemiology: 2 Novel-ish Approaches. Society for Epidemiological Research. Baltimore, Maryland.
1. 2018 May: Sones M, Kestens Y, Winters M, **Fuller D**, Muhajarine N, Marriott P, Datta G, Stanley K, Drouin L. Can bigger and better data make healthier cities? Symposium at: Canadian Public Health Association Conference, Montreal, QC.
1. 2018 May: Laberee K, Sones M, Nelson T, Kestens Y, **Fuller D**, Winters M. Recruiting participants for a cohort study on the health impacts of an urban form intervention: Lessons learned. Presentation at: Canadian Public Health Association Conference, Montreal, QC. 
1. 2018 May: Kestens Y, **Fuller D**, Winters M, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Wasfi R, Shareck M, Berscheid J, Gough M, Laberee K, Ottoni C, Poirier Stephens Z, Pugh C, Sones M, Thierry B, Brondeel R. INTERACT: A Comprehensive Urban Intervention Research Framework for Healthy and Sustainable Cities. Canadian Public Health Association Conference, Montreal, QC. 
1. 2018 May: Sones M, Winters M, **Fuller D**, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Kestens Y. Let's INTERACT - Mobilizing data, cities, and citizens for evidence and action on healthy, equitable cities. FUSE Conference on Knowledge Exchange in Public Health, Vancouver, BC.
1. 2018 February: Kestens Y, Fuller D, Winters M, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Wasfi R, Shareck M, Berscheid J, Gough M, Laberee K, Ottoni C, Poirier Stephens Z, Pugh C, Sones M, Thierry B, Brondeel R, Thigpen C, Luan H. Monitoring The Impact of Urban Form Changes on Health and Inequality: The INTERACT Methodology. Active Living Research Conference, Banff, AB. (First prize for poster presentation)
1. 2018 January: Sones M, Winters M, Kestens Y, **Fuller D**, McKay H, Sims-Gould, J, Lewis P, Datta G, Wasfi R, Lord S, Morency C, Cantinotti M, Muhajarine N, Bell S, Stanley K, Nelson T. Monitoring the Impact of Urban Form Changes on Health and Inequality: The INTERACT Methodology. Cascadia conference. Abbotsford, BC. 
1. 2017 September: Winters M, **Fuller D**, Nelson T, Gauvin L, Whitehurst D, Rusch M, Fyfe M. Impacts of Bicycle Infrastructure in Mid-Sized Cities: Baseline Results. Oral presentation at the Small and Adaptive Cities Conference 2017, St. John's, Canada.
1. 2017 September: Luan, H. **Fuller D.** Developing a National Urban Sprawl Indicator for Canada. Oral presentation at the Small and Adaptive Cities Conference 2017, St. John’s, Canada.
1. 2017 July: Winters M, Fischer J, Therrien S, **Fuller D**, Gauvin L, Whitehurst D, Nelson T. Who benefits? Spatial access to cycling infrastructure in Canadian cities. International Medical Geography Symposium 2017. Angers, France.
1. 2017 June: **Fuller D**, Winters M, Kestens Y, Rondier P. A tale of three cities: A concept mapping exercise to understand the context for urban form changes. Oral presentation at International Society of Behavioral Nutrition and Physical Activity; June 10 2017; Victoria, BC. 
1. 2017 June:	Winters M, **Fuller D**. Income inequalities in Bike Score and bicycle to work mode share in Canadian cities. Poster at the International Society for Behavioral Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 10, 2017.
1. 2017 June: 	Winters M, Therrien S, Branion-Calles M, **Fuller D**, Gauvin L, Whitehurst D, Nelson T. Laying down the context: Baseline findings from natural experiment study of Biketoria, a city-wide cycling network in Victoria, British Columbia. Poster at the International Society for Behavioral Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 10, 2017.
1. 2017 June:	Hosford K, **Fuller D**, Gauvin L, Brauer M, Teschke K, Winters M. Assessing the Modal Impacts of Public Bikeshare Systems: A Comparison of Survey Tools. Poster at the International Society for Behavioural Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 7-10 2017.
1. 2017 June:	**Fuller, D.**., McGowan, E., Cutumisu, N., North, S., & Courneya, K. (2017, June). The Role of the Built Environment in a Randomized Controlled Trial to Increase Physical Activity among Men with Prostate Cancer: The PROMOTE Trial. Poster at the International Society for Behavioural Nutrition and Physical Activity (ISBNPA) 2017 Annual Meeting, Victoria, British Columbia.
1. 2016 November: **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teshcke, K. Evaluating the impact of implementing public bicycle share programs on cycling: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Congress on Physical Activity and Public Health. Bangkok, Thailand. 
1. 2016 November: **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teshcke, K. Evaluating the impact of implementing public bicycle share programs on collisions: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Congress on Physical Activity and Public Health. Bangkok, Thailand. 
1. 2016 May:	Bernatchez, A.C., Dube, A.S, Gauvin, L., **Fuller, D.**, Drouin, L. Knowing About a Public Share Program in Montreal, Canada : Is Diffusion of Innovation and Proximity Enough for Equitable Awareness? Student Conference in Population Health. University of Ottawa.
1. 2016 June:	Ramsay, D., **Fuller, D.** The impact of social position on the relationship between active travel use and body mass index in a sample of urban Canadians. Canadian Public Health Association.
1. 2016 June:	Alphonsus, K., **Fuller, D.**, Waldner, C.. Examining the Association between Area Level Deprivation and Severity of Vehicle Collisions. Canadian Public Health Association.
1. 2015 November:	**Fuller, D.**, Ness, E., Joseph, M., Pswarayi, H., Van Nest, J., Grewal, J., Amery, A., Anstruther. S. Values and the measurement of social inequalities in health. Saskatchewan Epidemiology Association Conference, Regina, Saskatchewan. 
1. 2015 July:	**Fuller, D.**, Shareck, M. Canada Post community mailboxes: Implications for health research. International Medical Geography Symposium, Vancouver, Canada. 
1. 2015 April: **Fuller, D.**, Pabayo, R. The relationship between utilitarian walking, utilitarian cycling, and body mass index in a population based cohort study of adults: Comparing random intercepts and fixed effects models. Transportation Research Board, Washington, DC. 
1. 2015 March:	Lotoski, L., Muhajarine, N., Ridalls, T., **Fuller, D.**, Katapally, T., Stanley, K., A 4-season longitudinal study examining the association between seasonality and sedentary behaviour in 8-11 year old Canadian children. Poster presentation at the Health & Life Sciences Research Conference, Saskatoon, Saskatchewan.
1. 2014 October:	Bandara, T., Williams-Roberts, H., Lockhart, S., Thurairasu, L., **Fuller, D.**, Neudorf, C. Assessing the Effects of the Social Determinants of Health in Rural Saskatchewan.  Oral presentation at the 2014 Safety & Health in Agricultural & Rural Populations: Global Perspectives (SHARP), Saskatoon, Saskatchewan.
1. 2014 March:	**Fuller, D.** Modeling the Impact of Built Environment Interventions: An Introduction to Causal Modeling.  Workshop presentation at the 2014 Active Living Research Conference, San Diego, California.
1. 2013 July:	Datta, G., Barnett, T., **Fuller, D.** Are physical activity opportunities at school associated with self-reported and accelerometry estimated physical activity among elementary school students? Poster presentation at the 2013 Society for Epidemiological Research Conference, Boston, Massachusetts.
1. 2012 November:	**Fuller, D.**, Gauvin, L., Kestens, Y. Sociodemographic correlates of public bicycle share program use: An intercept survey of users in Montreal, Canada. Oral presentation at the 2012 International Congress of Physical Activity and Public Health, Sydney, Australia.
1. 2012 June:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining the impact of the BIXI public bicycle share program on the likelihood collisions and quasi-collisions. Oral presentation at the 2012 Velo City International Conference, Vancouver, Canada. 
1. 2012 April:	**Fuller, D.**, Gauvin, L., Datta, T. Kestens, Y., Lacroix, G., Strumpf, E., Kestens, Y., Haddad, S. Studying the impact of natural built environment interventions: Approximating a randomised controlled trial using the regression discontinuity design. Oral presentation at the 2012 Population Health Methods and Challenges conference, Birmingham, England.
1. 2012 April:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining the spatial distribution and relationship between support for policies aimed at active living in transportation and transportation behavior. Oral presentation at the Society of Behavioral Medicine Conference, New Orleans.
1. 2012 March:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining Individual and Neighborhood Level Disparities in Access to the Road Network, Public Transit, and a Public Bicycle Share Program in Montreal, Canada. Oral presentation at the Active Living Research Conference, San Diego. 
1. 2011 June:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. From modal shift to multi-modal transportation – Complexity of transportation behaviours associated with implementation of the BIXI public bicycle share program in Montreal. Oral presentation at the Canadian Public Health Association Conference, Montreal, Canada. 
1. 2011 February:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. Evaluating the impact of implementing a public bicycle share program on utilitarian cycling: The case of BIXI in Montreal, Canada. Oral presentation at the Active Living Research Conference, San Diego, California. 
1. 2010 October:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. Prevalence and predictors of use a city-sponsored public bicycle share program in Montreal, Canada: The case of BIXI. Oral presentation at the 9th International Conference on Urban Health, New York.
1. 2010 July: **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Tracking the reach of a cycling intervention: The case of a large-scale public bicycle share program. Oral presentation at the World Conference of the International Union for Health Promotion and Education, Geneva, Switzerland.
1. 2010 April:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Validity and Reliability of a Measure of Favorability to Active Living Friendly Policies. Oral presentation at the Society of Behavioral Medicine Conference, Seattle, Washington. 
1. 2010 May:	**Fuller, D.**, Sabiston, C., Karp, I., Barnett, T., O’Loughlin, J. School sport opportunities influence physical activity in secondary school and beyond. Poster presentation at the International Congress on Physical Activity and Public Health, Toronto, Ontario.
1. 2010 February: **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Behavioral Correlates of Awareness of a Large-scale, Self-service Bicycle Program: Potential for a Modal Shift Toward Active Transportation. Poster presentation at the Active Living Research Conference, San Diego, California.
1. 2009 March:	**Fuller, D.**, Gough, R., Meili, R. (March 2009). Evaluation of student experiences in the Making the Links project. Oral presentation at the International Research conference on Service-Learning and Community Engagement, Ottawa, Ontario.
1. 2009 April:	**Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. Walking for active transportation: Using social cognitive theory to examine differences between successful and less successful users. Poster presentation at the annual Society for Behavioral Medicine Conference, Montreal, QC. 
1. 2008 October:	Forbes, D. A., Bangma, J. Bingham, M., Forbes, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. First Province in Canada to Provide Access to The Cochrane Library: Lessons Learned. XVI Cochrane Colloquium, Freiburg, Germany. 
1. 2008 June: **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. A prospective examination of social cognitive predictors of walking for active transportation. Poster presentation at the North American Society for the Psychology of Sport and Physical Activity Conference, Niagra Falls, ON.
1. 2008 March:	Bloomquist, C.D., **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S., & Bray, S.R. Active Transportation Use By Sufficiently and Insufficiently Active First-Year University Students. Poster presentation at the Society of Behavioral Medicine Conference, San Diego, CA.
1. 2008 March:	Gyurcsik, N.C., Brawley, L.R., Spink, K.S., Brittain, D.R., Chad, K., & **Fuller, D.** Managing arthritis using physical activity: Perceived barriers and self-regulatory efficacy predict activity in arthritic women. Oral presentation at the Society of Behavioral Medicine Conference, San Diego, CA.
1. 2007 October:	Forbes, D. A., Bangma, J. Bingham, M., Forbes, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. Promoting and evaluating access to the Cochrane Library. Oral presentation at the Cochrane Colloquium, Sao Paulo, Brazil. 
1. 2007 March: Bloomquist, C. D. & **Fuller, D.** Active Transportation: Sustainable physical activity options for university students. Poster presentation at the Health & Life Sciences Research Conference, Saskatoon, Saskatchewan.
1. 2006 October:	Forbes, D. A., Bangma, Neilson, C., **Fuller, D.**, Adamson, J.,Bingham, M. Strategies that promote the use of the Cochrane Library. Oral presentation at the Cochrane Colloquium, Dublin, Ireland. 
1. 2005 November:	**Fuller, D.**, & Gyurcsik, N. C. The coach-athlete relationship: Perceptions of coaching behaviour in individual sports. Oral presentation at the Sport Leadership Conference, Quebec, Quebec. 
1. 2005 December:	Forbes, D. A., Bangma, J. Bingham, M., Adamson, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. Do province-wide access to the Cochrane Library and training sessions make a difference? Oral presentation at the Canadian Cochrane Symposium, Montreal, Quebec. 

## <span style="color:#81112c">Open Source Software</span>

* _Brondeel R_, _Rahimipour Anaraki J_, _KhataeiPour S_, __Fuller D__. activityCounts: Generate ActiLife Counts. [https://cran.r-project.org/web/packages/activityCounts/index.html](https://cran.r-project.org/web/packages/activityCounts/index.html)

## <span style="color:#81112c">Partner and Non-Academic Audience Presentations</span>

* January 24, 2020. **Fuller D**. Population Physical Activity Research: Applications to Staff Wellness. Memorial University Health Science Librarians.
* May 28, 2018. Laberee K, Nelson T, Ferster C. Fischer J, **Fuller D**, Winters M. BikeMaps.org – A national view on bicycling safety and ridership in Canada. Presentation at the Canada Bikes National Summit in Ottawa.
* October 28, 2017. Winters M, **Fuller D**, Fischer J, Branion-Calles M, Therrien, S, Gauvin L, Whitehurst DGT, and Nelson T.  Impacts of bicycle infrastructure in mid-sized cities study: Baseline results. Presentation at the Greater Victoria Bike to Work Week Society Annual General Meeting.  In attendance: 40 including representatives from the Greater Victoria Bike to Work Week Society, Greater Victoria Cycling Coalition and the CRD. 
* September 29, 2017. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Baseline results. Presentation to Halifax Road Safety Advisory Committee.  In attendance: 5. 
* September 28, 2017. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax Baseline results. Presentation and meeting with local cycling advocates.  In attendance 10: including representatives from the from the Halifax Cycling Coalition, Nova Social Cycles, Halifax Ecology Action Centre, and Halifax Regional Health Authority. 
* September 28, 2017. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax baseline results. Halifax Regional Municipality Transportation Standing Committee.  In attendance: 15, including 3 councilors, city planners and engineers, and CBC reporter. 
* September 28, 2017. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax baseline results. Evening public event and panel discussion hosted by Halifax Cycling Coalition, Nova Social Cycles, Halifax Ecology Action Centre, and Halifax Regional Health Authority.  In attendance: 30 live + ~75 livestream.  Halifax Central Library. . 

## <span style="color:#81112c">Invited Researchers</span>

1. Dr. Amy Auchincloss, Professor, School of Public Health, Drexel University. October 20th - November 3rd, 2016. 
2. Dr. Kevin Stanley, Professor, Department of Computer Science, University of Saskatchewan. September 26, 2016.
3. Dr. Steven Hoffman, CIHR Institute of Population and Public Health, York University. October 17-18, 2016.

## <span style="color:#81112c">Hosted Workshops</span>

1. "How to write a conceptual paper" workshop. Attended by 9 students from Universite de Montreal. November 4, 2019.
1. "The Future of Walkability Measurement in Canada" workshop. Attended by 18 researchers from across Canada. November 16 and 17, 2017
2. "Itinerum Smartphone App" workshop with Dr. Zachary Patterson from Concordia University. Approximately 20 students attended. October 20th 2017. 
3."R: Data analysis and report writing for HKR" workshop in 2017 attended by 17 students and faculty members. Tuesday April 25, 2017.
4."BikeMaps.org" workshop in 2017 attended by 9 community members and hosted in collaboration with Safety NL. Thursday February 2, 2017.  

## <span style="color:#81112c">Grants</span>

### <span style="color:#81112c">Awarded Grants</span>

| Role | Year | Title | Funder |  Amount | MUN Amount |
|------|--------|--------|--------|------|------|
|  Co-Applicant  | September 2020-March 2024 | Examining the impacts of the downtown Sherbrooke (QC) revitalization project on health equity among young adults: a mixed- methods evaluation | CIHR | $100,000 | $ |
|  Co-Applicant  | September 2020-March 2024 | CentrES | CIHR | $100,000 | $ |

|  Co-Applicant  | September 2020-March 2024 | Citizen Mapping of Microscale Barriers to Mobility | Public Health Agency of Canada - Enhanced Surveillance for Chronic Disease Program | $681,992 | $40,000 |

|  Co-Applicant  | September 2020-March 2024 | Citizen Mapping of Microscale Barriers to Mobility | Public Health Agency of Canada - Enhanced Surveillance for Chronic Disease Program | $681,992 | $40,000 |
|  Co-Applicant  | June 2020-June 2021 | Dietary change during COVID-19: A population-based study in Atlantic Canada to build evidence for government economic and social policy responses | CIHR COVID-19 Rapid Research - Social Policy and Public Health Response | $267,020 | $0 |
|  Co-Applicant  | August 2019 - August 2024 | AI for public health (AI4PH): A focus on equity and prevention | Operating Grant: CIHR Summer Institute on Equitable AI for Public Health | $525,000 | $0 |
|  Co-Applicant  | October 2019-October 2022 | Impacts of the new Réseau Express Métropolitain (REM) on mobility, health and equity: A pre-post intervention study | CIHR-NSERC Collaborative Health Research Projects | $441,002 | $0 |
|  Co-Applicant  | February 2020-October 2020 | Training for Healthy INterdisciplinary Knowledge in Cities (THINK-Cities)  | Training Grant : CIHR-NSERC-SSHRC Healthy Cities Research Training Platform (HCRTP) | $25,000 | $0 |
| Principal Investigator  | March 2019-March 2020 | Creating and comparing activity space measures to understand how walkability, urban sprawl, and public transit accessibility are associated with location based physical activity in 4 Canadian cities | CIHR | $100,000 | $100,000 |
| Co-Applicant | May 2019 – April 2020 | Smart Cities, Healthy Citizens? Optimizing Health and Equity in City Policy Making | CIHR | $24,985 | $0 |
| Co-Applicant | March 2019-March 2023 | Sustainable Healthy Cities: The Interplay between Urban Interventions, Gentrification, and Population Health | CIHR | $527,851 | $6000 |
| Team Lead | April 2017-April 2021 | Canadian Urban Environmental Health Research Consortium | CIHR | $5 Million | $45,000 |
| Co-Principal Investigator | December 2017 to December 2021 | Environments and Health INTERACT: INTErventions, Research, and Action in Cities Team | CIHR | $2 Million | $106,256 |
| Principal Investigator | August 2016 to August 2021 | Canada Research Chair in Population Physical Activity | CRC  | $500,000 | $500,000 |
| Principal Investigator | August 2016 to August 2021 | Newfoundland Research and Development Corporation CRC Leverage | RDC | $100,000 | $100,000 |
| Principal Investigator | August 2016 to August 2018 | Canadian Foundation for Innovation John R. Evans Leaders Fund | CFI | $252,638 | $252,638 |
| Principal Investigator | August 2016 to August 2018 | Newfoundland Research and Development Corporation CFI Leverage Grant | RDC | $100,000 | $100,000 |
| Co-Applicant | August 2016 to August 2021 | Impacts of City-Wide Bicycle Infrastructure Investment on Population Health & Health Equity | CIHR | $428,400 | $0 |
| Co-Applicant | December 2017 to December 2021 | Multisectoral Urban Systems for health and Equity in Canadian cities | CIHR | $2 Million | $0 |
| | | | Total | $12,291,896 | $1,353,638 |

### <span style="color:#81112c">Grants Under Review</span>
None

### <span style="color:#81112c">Unsuccessful Grants</span>
1. **Fuller D**, Arbour-Nicitopoulos K, Basset F, Kestens Y, Winters M, Martin Ginis K, Voss C, Schaffel A, Stanley K. (2018) PAS App – A system to scale up physical activity and sedentary behaviour surveillance among diverse populations in Canada. CIHR Project Grant. $CAD 950,000. 
1. **Fuller D**, Arbour-Nicitopoulos K, Basset F, Kestens Y, Winters M, Martin Ginis K, Voss C, Schaffel A, Stanley K. (2018) PAS App – A system to scale up physical activity and sedentary behaviour surveillance among diverse populations in Canada. Public Health Agency of Canada Chronic Disease Surveillance Grant. $CAD 1,000,000. 
1. **Fuller D**, Winters M, Kestens Y. (2018) INTERACT St. John's. CIHR Project Scheme Grant. $CAD 680,000.
1. Staniland, A. **Fuller, D.**, Vardy, A. (2018). Immersive Audio and Virtual Reality Infrastructure. Canada Foundation for Innovation. $250,000
1. Kestens, Y., Murua, A., Lord, S., **Fuller, D.**, Stanley, K., Gebru, T., Brondeel, R. (2017) Caracterisation des environnements urbains pour la recherche en sante: De la machine à l'humain. Programme intersectoriel AUDACE, FRQSC. $CAD 100,000.
1. City of St. John's & Happy City. (2018). Smart Cities Challenge. Infrastructure Canada. $5M.
1. Patterson, Z., Gaspar, V., Donaher, G., Hain, M., Chapman, O., Gueheneuc, Y-G., Renzi, A., Yu, J Y., Cloutier, M-S., **Fuller, D.,** Tessier, M-A., Hamzeh, H., Bilal, F., Winters, M., Plouffe, C., Farber, S., Widener, M. The Itinerum Open Smartphone Travel Survey Platform Partnership. (2018). SSHRC Partnership Grant. $2M. 
1. **Fuller, D.**, Kestens, Y., Winters, M., Luan, H., Stanley, K., Tremblay, M. (2017). A machine learning and artificial intelligence for physical activity working group for population level physical activity measurement using wearable devices. CIHR Planning and Dissemination Grant. $20,000.
1. **Fuller, D.**, Chen, Y., Cameron, E., Gyurcsik, N., Hu, T., Basset, F. Labelling data and leveraging opportunities for sex and gender identity specific physical activity counselling using wearable devices. CIHR Personalized Health Catalyst Grant. *Principal Applicant*. $200,000.
1. Kestens, Y., Brondeel, R., Stanley, K., Mathieu, M-E., **Fuller. D.**, Stanley, K. (2017) Developing a machine learning based toolkit for derivation of physical activity indicators based on smartphone sensor data. CIHR Personalized Health Catalyst Grant. *Co-Applicant*. $136,291.
1. Kestens, Y., Murua, A., Mathieu, M-E., Fuller, D., Stanley, K., Brondeel, R. (2017) Developing a machine learning based toolkit for derivation of physical activity indicators based on smartphone sensor data. IVADO. $CAD 100,000. 
1. **Fuller, D.** CIHR Institute of Population and Public Health Trailblazer Award. *Principal Applicant*. $17,000.
1. McGowan, E., **Fuller. D.**, McCarthy, J., Yi, D., Browne, S. Capturing real-time association between cancer specific symptoms, sleep, and physical activity among breast cancer survivors undergoing treatment. NL Support. *Co-Principal Applicant*. $75,000.

### <span style="color:#81112c">Completed Grants</span>

* __Fuller, D.__, Chen, Y. Developing a public open source walkability measure for Newfoundland. $10,000. Memorial University Seed, Bridge, Multidiscplinary Fund. April 2017-April 2019.
* __Fuller, D.__, Kestens, Y. Luan, H. Winters, M. HEROX: The Healthy Behaviour Data Challenge. $10,000. CIHR - Planning Grant. January 2018-January 2020.
* Winters, M. Kestens. Y. __Fuller, D.__. Policy Action for Healthy Cities. $10,000. CIHR - Planning Grant. January 2018-January 2020.
* Kestens. Y. __Fuller, D.__, Winters, M. INTervention Research Across Cities Team. $10,000. CIHR - Planning Grant. January 2018-January 2020.
* __Fuller, D.__, Kestens, Y. Luan, H. Brook, J. Winters, M. Transportation and Health Impact Modelling for Healthy Cities. $10,000. CIHR - Planning Grant. January 2018-January 2020.
* Kestens, Y. Brondeel, R. __Fuller, D.__, Stanley, K. Winters, M. Documenting Urban Change for Health Research using Artificial Intelligence. $20,000. CIHR - Planning Grant. $20,000. January 2018-January 2020.
* Ross, N. Precup, D. Brazeau, A-S. Dasgupta, K.  Elrick, T. __Fuller, D.__ Law, R. Mandryk, E. The “Quantified Self” and the Quantified Place: Developing an Artificial Intelligence System From Smart Phone and Geo- Spatial Data to Lower Dietary and Physical Inactivity Disease Burden. $20,000. CIHR - Planning Grant.  January 2018-January 2020.
*	Muhajarine, N., **Fuller, D.**, Katapally, T., Osgood, N., Rainhan, D., Stanley, K. A Step towards Creating Active Urban Communities: Informing Policy by Identifying and Mapping Locations of Seasonal Activity Accumulation, $194,378, CIHR Operating Grant - Population and Public Health, September 2013 – September 2016.
*	Engler-Stringer, R., Muhajarine, N., Abonyi, S., Neudorf, C., Vatanparast, H., Walker, R., Whiting, S. J., **Fuller, D.** The Good Food Junction: A Community-Based Food Intervention to Reduce Nutritional Health Inequities, $200,00, CIHR Operating Grant - Population Health Intervention Research, December 2012 – December 2014.
*	Winters, M., Edwards, S., Teschke, K., Brauer, M., Gauvin, L., **Fuller, D.**, Frank, LDF., Kestens. Y., $200,000, Health Promotion through Active Transportation – A Pre-Post Evaluation of a Vancouver-Based Public Bikeshare Program, CIHR Operating Grant - Population Health Intervention Research, December 2011 – December 2016.
*	Gauvin, L., **Fuller, D.**, Drouin, L., Winters, M., Edwards, S., Teschke, K. A Multi-City Study of the Impact of Public Bicycle Share Programs on Active Transportation and Risk of Injury, $199,526, CIHR Operating Grant - Population Health Intervention Research, December 2011 – December 2014.
*	Gauvin, L., **Fuller, D.**, Drouin, L., Morency, P., Kestens, Y., $249,603, Impact of an Intervention Designed to Increase the Accessibility and User-Friendliness of an Active Mode of Transportation on Population Health: The Case of BIXI Montreal, CIHR Operating Grant- Population Health Intervention Research, April 2009 - April 2012.

## <span style="color:#81112c">Teaching</span>

### <span style="color:#81112c">Courses Taught</span>

| Institution | Year | Term | Course | Topic | Role |
|-------------|------|------|--------|-------|------|
| Memorial University  | 2020 | Winter | HKR 6000 | Quantitative Methods in Physical Education | Instructor |
|  | 2020 | Winter | HKR 6134 | Seminar | Instructor |
|  | 2019 | Fall | HKR 6130 | Computer Applications for Physical Activity Measurement and Intervention | Instructor |
|  | 2019 | Fall | HKR 6134 | Seminar | Instructor |
|  | 2019 | Fall | HKR 6134 | Seminar | Instructor |
| | 2019 | Winter | HKR 3400 | Social Determinants of Health | Instructor | 
|  | 2018 | Winter | HKR 6134 | Seminar | Instructor |
|  | 2019 | Fall | HKR 4600 | Research Methods | Instructor | 
|  | 2018 | Fall | HKR 6134 | Seminar | Instructor |
|  | 2018 | Winter | HKR 3400 | Social Determinants of Health | Instructor | 
|  | 2018 | Winter | HKR 6134 | Seminar | Instructor |
|  | 2017 | Fall | HKR 6130 | Computer Applications for Physical Activity Measurement and Intervention | Instructor |
|  | 2017 | Fall | HKR 6134 | Seminar | Instructor |
|  | 2017 | Summer | HKR 3400 | Social Determinants of Health | Instructor | 
|  | 2017 | Winter | HKR 6134 | Seminar | Instructor | 
|  | 2016 | Fall | HKR 6134 | Seminar | Instructor | 
| University of Saskatchewan | 2016 | Winter | PUBH 840 | Public Health Practice | Instructor | 
|  | 2016 | Fall | PUBH 840 | Public Health Practice | Instructor | 
|  | 2016 | Fall | PUBH 898 | Social Epidemiology | Instructor | 
|  | 2015 | Winter | PUBH 840 | Public Health Practice | Instructor | 
|  | 2015 | Summer | PUBH 804 | Foundations of Public Health | Instructor | 
|  | 2014 | Fall | PUBH 840 | Public Health Practice | Instructor | 
|  | 2014 | Fall | CHEP 898 | Population Health Intervention Research | Instructor | 
| Universite de Montreal | 2011 | Winter | MSO 6068c | Multilevel Modeling | Co-Instructor | 

### <span style="color:#81112c">Guest Lectures</span>

| Course | Instructor | Lecture | Year | Institution | 
|--------|------------|---------|------|-------------|
| HKR 2000 | Dr. Kevin Power | Big data and Physical Activity | 2019 | Memorial University | 
| HKR 2000 | Dr. Kevin Power | Physical Activity Epidemiology | 2018 | Memorial University | 
| HKR 2000 | Dr. Kevin Power | Population Approach to Physical Activity | 2017 | Memorial University | 
| HKR 2000 | Dr. Kevin Power | Social Inequalities in Health | 2017 | Memorial University | 
| Health Informatics | Dr. Saeed Samet | Physical Activity Data and Healthcare | 2017 | Memorial University | 
| HKR 6000 | Dr. Kevin Power | Physical Activity Epidemiology | 2017 | Memorial University | 
| MED 6270 | Dr. James Valcour | Social Epidemiology | 2017 | Memorial University | 
| KIN 223 | Dr. Serene Smyth | Contemporary Health Issues | 2013 | University of Saskatchewan | 
| KIN 6848 | Dr. Suzanne Laberge | Health Promotion and Physical Activity | 2011 | Universite de Montreal | 
| KIN 6848 | Dr. Suzanne Laberge | Healths Promotion and Physical Activity | 2010 | Universite de Montreal | 
| MSO 6134 | Dr. Lise Gauvin | Individual Behaviour and Public Health | 2010 | Universite de Montreal | 
| MSO 6048 | Dr. Geetanjali Datta | Thesis Seminar in Public Health | 2010 | Universite de Montreal | 
| MSO 6134 | Dr. Lise Gauvin | Individual Behaviour and Public Health | 2009 | Universite de Montreal | 

### <span style="color:#81112c">Unscheduled Mentorship Activity</span>

Scholarship Writing Mentorship Program, Department of Social and Preventive Medicine, Universite de Montreal, 2009 to 2011.

## <span style="color:#81112c">Undergraduate Student Supervision</span>

| Name | Program | Project | Term |
|------|--------|--------|------|
| Nana Abekah | Computer Science | BSc | Fall 2019 Winter 2020 |
| Utsav Koju | Computer Science | BSc | Fall 2019 |
| Sydney Hector | Human Kinetics and Recreation | Undergraduate Honours | 2018 |
| Harshal Deshpande  | Human Kinetics and Recreation | BSc | Fall 2018 Winter 2019 |
| Levi Moulton  | Human Kinetics and Recreation | BSc | Fall 2018 Winter 2019 |
| Logan Slade | Human Kinetics and Recreation | MUCEP | Fall 2018 |
| Abbie Humphreys | Humanities and Social Sciences | MUCEP | Summer 2018 |
| Desiree van Heerden | Engineering | Co-op Student | Summer 2017 |
| Mehnaz Tabassum | Business | MUCEP | Summer 2017 |
| Melissa Tobin | Human Kinetics and Recreation | Undergraduate Honours | 2017 |
| Alyssa Milley | Human Kinetics and Recreation | Undergraduate Honours | 2017 |
| Hilary Gosse | Human Kinetics and Recreation | Undergraduate Honours | 2017 |

## <span style="color:#81112c">Graduate Student Supervision</span>  

#### <span style="color:#81112c">Supervisor</span>  
* 2020: Ryan Ellis. _Thesis title TBD_. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University.
* 2020: Summayah Mussa. _Thesis title TBD_. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2020: Asia Holloway. Masters of Public Health Practicum. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2019: Rebecca Maher. _Thesis title TBD_. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University.
* 2019: Jonathan Slaney. _Thesis title TBD_. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2019: SeyedJavad KhataeiPour. Superior Performance of Machine Learning Algorithms in Metabolic Equivalent (MET) Prediction Using Cell Phone Accelerometer Data. MSc Co-Op. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2018: Machel Rayner. Masters of Public Health Practicum. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2017: Kassia Orychock. Association between BMI and WalkScore, Dining and Drinking Score and Grocery Score in a multi-city sample of adults: A cross sectional analysis. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2017: Bo Simango. Improving the accuracy of activity intensity classification using machine learning and commercial wearable device data. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University 
* 2017: Melissa Tobin. Examining the association between cycling infrastructure and cycling: Baseline results from INTERACT Victoria. MSc Program. Supervisor. School of Human Kinetics and Recreation. Memorial University
* 2017: Nathan Taylor. Masters of Public Health Practicum. Supervisor. Neighbourhood Active Living Potential on the Avalon Peninsula. Memorial University
* 2014:	Satyadeva Challa. Masters of Public Health Practicum. Supervisor. Stress Mapping and Network Connectivity Analysis. School of Public Health. University of Saskatchewan.
* 2013:	Anna Chen. Masters of Public Health Practicum. Supervisor. Analyzing road surface conditions, time of the day, and road structural factors associated with bicycle collisions from 2000 to 2010 in Saskatoon, Saskatchewan. School of Public Health. University of Saskatchewan.

#### <span style="color:#81112c">Committee Member</span>  

* 2020: Ryan Collins. Associations between Circadian Rhythm, Physical Activity, Mood, and Cognitive Function During the First Year of Treatment for Breast Cancer. PhD Program. Committee Member. Department of Psychology. Memorial University. 
* 2019: Kole Phillips. Novel measures of physical activity: String Analysis of Behavior Log Elements (StABLE). MSc Program. Committee Member. Department of Computer Science. University of Saskatchewan. 2019.
* 2018: Pablo Navarro. The Government of Newfoundland and Labrador’s implementation of a “Health in All Policies”. PhD Program. Committee Member. Faculty of Medicine, Division of Community Health and Humanities. Memorial University. 
* 2018: Ali Alfosool.  Road Importance Using Complex-Networks, Graph Reduction & Interpolation. PhD Program. Committee Member. Department of Computer Science. Memorial University. 
* 2017: Se’era Anstruthers. PhD Program. Committee Member. The Influence of Socioeconomic Factors and Location on the Impact of Children in Healthy Start-Depart Sante. Department of Nutrition. University of Saskatchewan. 
* 2016: Adriana Fonseca. PhD Program. Committee Member.  Physical activity and chronic back disorders in Canadian adults. Department of Community Health and Epidemiology. University of Saskatchewan.
* 2016: Kate Hosford. MSc Program. Committee Member. Impacts of a Public Bike Share Program in Vancouver, BC: Changes in Population Cycling Levels and Program Perceptions and Attitudes. Faculty of Health Sciences, Simon Fraser University.
* 2015: Larisa Lotoski. PhD Program. Committee Member. A 4-season longitudinal study examining the association between seasonality and sedentary behaviour in 8-11 year old Canadian children. Department of Community Health and Epidemiology. University of Saskatchewan. 
* 2013:	Lisa Thurairasu. MSc Program. Committee Member. Examining Individual and Area Level Income Inequalities in Urban Saskatchewan: A Case of Diabetes. Department of Community Health and Epidemiology. University of Saskatchewan.
* 2011:	Mariève Thetreault-Deslands. MPH Program. Committee Member. Utilitarian walking and diabetes: a cross-sectionnal study in Montreal, Canada. Departement de Medecine sociale et preventive. Faculte de Medecine. Universite de Montreal.
* 2010:	Geneviève Boily. MPH Program. Committee Member. L’association entre l’utilisation du transport actif et l’etat de sante auto-rapporte chez des adultes montrealais. Departement de Medecine sociale et preventive. Faculte de Medecine. Universite de Montreal.

## <span style="color:#81112c">Post Doctoral Fellows</span>

| Name | Program  | Completion | Institution | 
|------|---------|------------|-------------| 
| Hui (Henry) Luan | Post Doctoral Fellow | 2018 | Memorial University | 

#### <span style="color:#81112c">Research Assistants</span>  

| Name | Program  | Department | Institution | Time Frame |
|------|---------|------------|-------------| --------- |
| Megan Devries | MSc Student | Political Science | Memorial University | 2019
| Javad Rahimipour Anaraki | PhD Student | Computer Science | Memorial University | 2017-2019
| Wei Liu | PhD Student | Geography | Memorial University | 2019
| Emily Collwell | MSc Student | Kinesiology | Memorial University | 2017-2019
| Arastoo Borzogi | PhD Student | Computer Science | Memorial University | 2017-2020
| Majid Beheshtimoh | MSc Student | Computer Science | Memorial University | 2018
| Maria Yulmetova | MSc Student | Geography | Memorial University | 2018
| Richard Buote | PhD Student | Community Health | Memorial University | 2016-2018
| Samantha Breslin | PhD Student | Anthropology | Memorial University | 2018
| Jonathan Low | MSc Student | Kinesiology | Memorial University | 2016-2018
| Faramarz Dorani | MSc Student | Computer Science | Memorial University | 2016-2018

### <span style="color:#81112c">Graduate Thesis Revisions</span>

* 2020: Ryan Pretty. Barriers To Recruitment And Participation In Physical Rehabilitation Research: A Mixed Methods Study Among People With Multiple Sclerosis. MSc Medicine. Memorial University.
* 2019: Kenneth Joshua. The association between physical active leisure, mental and physical health and life satisfaction among Canadian imnmigrants? MSc Human Kinetics and Recreation. Memorial University.
* 2018: John Snow. Can tri-axial accelrometers improve current clinical measures of spinal mobility in patients with axial spondyloarthiritis? MSc Clinical Epidemiology. Memorial University.
* 2017: Amita Goyal. Association and mediators of leasure time physical activity and mental health among people with spinal cord injury.MSc Human Kinetics and Recreation. Memorial University.

### <span style="color:#81112c">New or Revised Teaching Materials</span>
* 2017:	HKR 6130 Computer Applications for Physical Activity Measurement and Intervention. School of Human Kinetics and Recreation. Memorial University. 
* 2015:	PUBH 898 Social Epidemiology. School of Public Health. University of Saskatchewan.
* 2014:	PUBH 840 Interdisciplinary Public Health Practice. School of Public Health. University of Saskatchewan.
* 2011:	CHEP 898 Population Health Intervention Research Reading course. Department of Community Health and Epidemiology. University of Saskatchewan.

### <span style="color:#81112c">Teaching Improvement</span>
* 2019:	An Introduction to Documenting Teaching Activity and Effectiveness. Centre for Innovation in Teaching and Learning, Memorial University. 
* 2017:	Transformational Teaching and Learning Day. Centre for Innovation in Teaching and Learning, Memorial University. 
* 2014:	Teaching Improvement Project System (TIPS) Course. College of Medicine, University of Saskatchewan.
* 2014:	How People Learn: Seven Research-Based Principles for Smart Teaching, College of Medicine, University of Saskatchewan.
* 2008:	What the best college teachers do, Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.
* 2007	Graduate Studies and Research 987: Science, Scientists, and Science-Societal Interactions: An introduction to the dynamics of science, Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.
* 2007:	Making Teaching Visible: Practical principles for peer review of teaching, Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.
* 2007:	Teaching… if only we knew the questions? Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.

### <span style="color:#81112c">Teaching Awards</span>

##### 2016 Most Effective Professor. School of Public Health Student Association. University of Saskatchewan.

### <span style="color:#81112c">Media</span>

1. Asia Holloway. August 21, 2020. Investing in a Walk-able City Pays for Itself. [https://theindependent.ca/2020/08/21/letter-investing-in-a-walk-able-city-pays-for-itself/](https://theindependent.ca/2020/08/21/letter-investing-in-a-walk-able-city-pays-for-itself/)
1. VOCM News, August 25, 2020. [https://soundcloud.com/vocm/asia-holloway-masters-of-a-public-health-student-with-the-mun-beap-lab-health-economic-benefits-of-walking-in-st-johns?in=vocm/sets/vocm-morning-show](https://soundcloud.com/vocm/asia-holloway-masters-of-a-public-health-student-with-the-mun-beap-lab-health-economic-benefits-of-walking-in-st-johns?in=vocm/sets/vocm-morning-show)
1. VOCM News, August 25, 2020. [Walking in St. John’s Would Help Economy, says MUN Study](Walking in St. John’s Would Help Economy, says MUN Study)
1.  Mark Quinn, August 26, 2020. Making St. John's more walkable worth more than $100M over 10 years, say MUN researchers. [https://www.cbc.ca/news/canada/newfoundland-labrador/value-of-walking-1.5698911?__vfz=medium%3Dsharebar](https://www.cbc.ca/news/canada/newfoundland-labrador/value-of-walking-1.5698911?__vfz=medium%3Dsharebar)
1. CBC National Syndication. Obesity in Canada. February 13, 2020. 
    * CBC Cape Breton - Steve Sutherland 
    * Ontario AM - Wei Chen
    * Island Morning - Mitch Cormier
    * Windsor Morning - Tony Doucette
    * Newfoundland Morning - Bernice Hillier
    * St. John's Morning Show - Anthony Germain
    * The Trailbreaker - Loren McGinnis
    * Yukon Morning - Chris Walker
    * Kitchener-Waterloo - Craig Norris
    * Daybreak North - Carolina DeRyk
    * The Early Edition - Steven Quinn
1. Brett Bundale, February 7, 2020. A day in the life of a crossing guard. [https://www.thechronicleherald.ca/news/local/a-day-in-the-life-of-a-crossing-guard-its-a-precarious-profession-408524/](https://www.thechronicleherald.ca/news/local/a-day-in-the-life-of-a-crossing-guard-its-a-precarious-profession-408524/)
1. Jaimie Fitzpatrick, February 3, 2020. Vision Zero traffic safety policy. [https://www.cbc.ca/listen/live-radio/1-56-st-johns-morning-show/clip/15758803-vision-zero-traffic-safety-policy](https://www.cbc.ca/listen/live-radio/1-56-st-johns-morning-show/clip/15758803-vision-zero-traffic-safety-policy)
1. Jennifer Quesnel November 25, 2019. Interventions, Research, and Action in Cities Team Wave 1 results. [https://www.cbc.ca/news/canada/saskatoon/study-finds-half-of-riders-in-saskatoon-unaware-of-coming-bus-rapid-transit-1.5372445](https://www.cbc.ca/news/canada/saskatoon/study-finds-half-of-riders-in-saskatoon-unaware-of-coming-bus-rapid-transit-1.5372445)
1. Ariana Kelland. March 25, 2019. After immigration trouble, this St. John's trainer is back to helping others [https://www.cbc.ca/news/canada/newfoundland-labrador/update-machel-rayner-1.5064383](https://www.cbc.ca/news/canada/newfoundland-labrador/update-machel-rayner-1.5064383)
2. CBC Cross Talk. Do you feel safe riding a bicycle? June 21, 2018. 
3. Juanita Mercer. N.L. urban residents advised to take the bus to better health. May 27, 2017.
[http://www.thetelegram.com/news/local/nl-urban-residents-advised-to-take-the-bus-to-better-health-213473/](http://www.thetelegram.com/news/local/nl-urban-residents-advised-to-take-the-bus-to-better-health-213473/)
4. Ted Blades. Taking the bus is better for your health. June 8, 2018.  [http://www.cbc.ca/listen/shows/on-the-go/episode/15549559](http://www.cbc.ca/listen/shows/on-the-go/episode/15549559)
5. Mark Quinn. Bike map aims to help St. John's cyclists steer clear of trouble. March 8, 2018. [http://www.cbc.ca/news/canada/newfoundland-labrador/bike-map-st-john-s-1.4567225](http://www.cbc.ca/news/canada/newfoundland-labrador/bike-map-st-john-s-1.4567225)
6. Andrea Kelly. Collisions and Close Calls. February 28, 2018 [https://gazette.mun.ca/research/collisions-and-close-calls/](https://gazette.mun.ca/research/collisions-and-close-calls/)
7. Susan Flagan. Walkability factors. June 6, 2017. [https://gazette.mun.ca/research/walkability-factors/](https://gazette.mun.ca/research/walkability-factors/)
8. CBC Cross Talk. Do activity trackers increase physical activity. October 25, 2016. 

## <span style="color:#81112c">CIHR Leadership and Service</span>

1. CIHR-IPPH Artificial Intelligence for Public Health Consultation Meeting. January 18, 2018. Toronto, Ontario.
1. CIHR-IPPH Healthy Cities Consultation Meeting. November 31-December 1, 2017. Toronto, Ontario.
1. CIHR-IPPH Advisory Board Meeting. September 21-22, 2017, Toronto, Ontario.
2. CIHR-INMD Think Tank. September 11, 2016. Toronto, Ontario.

### <span style="color:#81112c">Funding Reviews</span>

1. 2020 Tier 2 Canada Research Chair Renewal in Physical Activity and Health
1. 2020 Tier 2 Canada Research Chair Application in  Artificial Intelligence for Complex Health Data
1. 2020 MITACS Accelerate. Title: La navette autonome de la Petite Bourgogne répond-elle aux besoins de la communaute?
2. 2020 MITACS Accelerate. Title: Investigation of supportive policy for Active School Travel: Evidence- based recommendations for policies to promote active transportation for school journeys
3. 2020 European Science Foundation. Title: Data mining for real-time bicycle collisions control in cycling cities.
4. 2019 NSERC Discovery Grant Reviewer. Title: Merging measurement theory and technology for more accurate assessment of physical activity

### <span style="color:#81112c">Peer Reviews</span>

| Number of Reviews | Year | Example Journals |
|---------|------|-------------------|
| 3 | 2020 | British Medical Journal, Journal of Transportation and Health | 
| 8 | 2019 | British Medical Journal, Journal of Transportation and Health | 
| 2 | 2018 | Canadian Journal of Public Health | 
| 6 | 2017 | Nature - Science Reports, American Journal of Preventive Medicine | 
| 2 | 2016 | Canadian Journal of Public Health | 
| 4 | 2015 | Journal of Epidemiology and Community Health | 
| 2 | 2014 | Transportation Research Board | 
| 4 | 2013 | American Journal of Public Health | 
| 5 | 2011 | Social Science and Medicine | 
| 2 | 2011 | Annals of Behavioral Medicine | 

## <span style="color:#81112c">Consulting</span>

* 2014: Fuller, D. Saskatoon Health Region Employee Health Survey Data Presentation. Conduct analysis and develop interactive website to present employee health data to staff. Fee of $75/hour.
* 2014 Fuller, D. Founded Good Fit Data (www.goodfitdata.com)
* 2014 Fuller, D. Philadelphia Bicycle Share Study. Develop research protocol for Philadelphia Bikeshare Study lead by Dr. Amy Auchincloss. Fee of $500/hour.
* 2009 Fuller, D. Neighbourhood Active Living Potential (NALP). Training session for the use of the NALP. Smart Cities, Healthy Kids Project (CIHR, Heart and Stroke Foundation of Canada), May 19-22, Saskatoon, Canada. Fee of $50/hour.

## <span style="color:#81112c">Unit Level Committees</span>

| Name of Committee | Period | Institution |
|-------------------|--------|-------------|
| Search Committee - Lockheed Martin Chair | 2018 - 2019 | Marine Institute - Memorial University | 
| Search Committee Chair | 2018 - 2019 | Memorial University | 
| Dean Search Committee | 2017 - 2018 | Memorial University | 
| Search Committee | 2017 - 2018 | Memorial University | 
| Graduate Studies Committee | 2016 - 2018 | Memorial University | 
| Awards Committee | 2016 - ongoing | Memorial University | 
| Faculty Council | 2016 - ongoing | Memorial University | 
| Academic Council | 2016 - ongoing | Memorial University | 
| Epidemiology Program Advisory Committee | 2016 | University of Saskatchewan | 
| PhD Program Committee, Student Member | 2008-2010 | Universite de Montreal | 
| PhD Admissions Committee, Student Member | 2008-2010 | Universite de Montreal | 
| Universite de Montreal Public Health Graduate Student Society | 2008-2010 | Universite de Montreal | 
| College of Kinesiology Graduate Society | 2006-2008 | Universite de Montreal | 

### <span style="color:#81112c">Other Unit Level Activities</span>

* 2017 - Curriculum Vitae and Resume Workshop, Memorial HKR Grad Student Society
* 2017 - Scholarship Writing Workshop, Memorial HKR Grad Student Society
* 2016 - Developped mentorship document for untenured faculty (see Appendix A)
* Ongoing - Academic unit planning sessions
* Ongoing - Academic unit planning sub-group meetings
* Ongoing - Funded $250 award to HKR Student Conference

## <span style="color:#81112c">University Committees</span>

| Name of Committee | Period | Institution |
|-------------------|--------|-------------|
| School of Public Health Committee, Student Member | 2008-2010 | Universite de Montreal | 

## <span style="color:#81112c">Professional Activity Outside University</span>

* 2020-2023: Social Media Associated Editor, Canadian Journal of Public Health 
* 2019: Associated Editor, Canadian Journal of Public Health 
    - Associate Editor for 5 manuscripts 
* 2018-2019: Associated Editor, BMC Public Health 
    - Associate Editor for 13 manuscripts 
* 2015-2017: Board Member, Saskatchewan Epidemiology Association.
* 2015: Scientific Committee, Food Environments in Canada Symposium and Workshop.
* 2014: Scientific Committee, Active Living Research Conference.
* 2009-2011: Board Member, International Union of Health Promotion Student and Early Career Network (ISECN).
* 2009-2011: Board Member, Canadian Public Health Association Student Ad Hoc Committee.