---
title: 'Service: Promotion and Tenure Document'
author: "Daniel Fuller"
date: '2017-09-12'
output:
  html_document:
    keep_md: yes
    toc: true
    toc_depth: 2
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Daniel Fuller, Ph.D.  
Canada Research Chair in Population Physical Activity  
Assistant Professor  
School of Human Kinetics and Recreation   
Physical Education Building PE 2024 Memorial   
University of Newfoundland St. John’s, NL  
A1C 5S7  
Tel: (709) 864-7270    
E-mail: dfuller@mun.ca    
Web: [http://www.walkabilly.ca/](http://www.walkabilly.ca/)  

# <span style="color:#81112c">Service Overview</span>

My service activities are focused on contributing to two broad themes. First, enhancing student success in research. Second, creating linkages between my work and the community. These two themes contribute to my research programs mission *"to conduct research that will help design urban and rural environments that equitably increase physical activity for the entire population"* by creating structures through my service that enhance opportunities for highly qualified personnel and by linking my research with the community. 

# <span style="color:#81112c">Service at Memorial University</span>

## <span style="color:#81112c">Cross Appointments</span>

I am cross appointed with the Faculty of Medicine, Department of Community Health and Humanities and the Faculty of Science, Department of Computer Science. These cross appointments have allowed me to be a committee member for Pablo Navarro's PhD in Community Health and Humanities. I am also a co-supervisor with Dr. Yuanzhu Chen of Ali Alfosool's PhD in Computer Science titled "Road Importance Using Complex-Networks, Graph Reduction & Interpolation."

## <span style="color:#81112c">Committees</span>

Since beginning in the School of Human Kinetics & Recreation at Memorial University on August 1 , 2016, I have made efforts to serve the School of Human Kinetics and Recreation. I will briefly describe the work of each of the committees that I have served on and, where relevant, outline specific duties or roles that I have taken on within these committees.

| Name of Committee | Period | Institution | Role |
|-------------------|--------|-------------| -------------|
| Faculty Council | 2016 - ongoing | Memorial University | Regular Meetings and School decision making | 
| Academic Council | 2016 - ongoing | Memorial University | Regular Meetings and School decision making |
| Library Committee | 2019 - 2020 | Memorial University |  |
| Search Committee - Lockheed Martin Chair | 2018 - 2020 | Marine Institute - Memorial University | Search community for an industry funded Chair position |
| Search Committee Chair | 2018 - 2019 | Memorial University | Hired 2 positions. Coordinated interviews for 6 people and reviewed 78 applications |
| Dean Search Committee | 2017 - 2018 | Memorial University | Hired Dean position. Worked with Vice President Academic |
| Search Committee | 2017 - 2018 | Memorial University | Hired 1 position. Worked with search committee members |
| Graduate Studies Committee | 2016 - 2018 | Memorial University | Decision making around graduate programs and began implementing updates to the program |
| Awards Committee | 2016 - 2018 | Memorial University | Decision making about student awards |
| Epidemiology Program Advisory Committee | 2016 | University of Saskatchewan |  |
| PhD Program Committee, Student Member | 2008-2010 | Universite de Montreal |  |
| PhD Admissions Committee, Student Member | 2008-2010 | Universite de Montreal |  |
| Universite de Montreal Public Health Graduate Student Society | 2008-2010 | Universite de Montreal |  |
| College of Kinesiology Graduate Society | 2006-2008 | Universite de Montreal |  |

### <span style="color:#81112c">Other Activities</span>

* 2017 - Curriculum Vitae and Resume Workshop, Memorial HKR Grad Student Society
* 2017 - Scholarship Writing Workshop, Memorial HKR Grad Student Society
* 2016 - Developped mentorship document for untenured faculty (see Appendix A)
* Ongoing - Academic unit planning sessions
* Ongoing - Academic unit planning sub-group meetings
* Ongoing - Funded $250 award to HKR Student Conference

# <span style="color:#81112c">External Service</span>

In my external service roles I have focused on positions with journals that I respect and where I think I can make a contribution. I am currently the social media editor for the Canadian Journal of Public Health. This role was newly created by me and the CJPH editor. It allows me to engage with students and the general public on social media and promote the journal. For example, I have published 2 letters to editor in my role as social media associate editor. 

* _Paulsen, P._, __Fuller, D__. Scrolling for data or doom during COVID-19?. Can J Public Health. 2020. 111, 490–491. [https://doi.org/10.17269/s41997-020-00376-5](https://doi.org/10.17269/s41997-020-00376-5)
* __Fuller, D.__, Potvin, L. Social media and the Canadian Journal of Public Health. Can J Public Health. 2020. 111, 149–150. [https://doi.org/10.17269/s41997-020-00301-w](https://doi.org/10.17269/s41997-020-00301-w)

I am also regularly asked to funding reviews for external organizations. As a result of my chair and my experience with large grants, I have reviewed for Canada Research Chairs Secretariat, the European Science Foundation, and MITACS. 

### <span style="color:#81112c">List of External Service</span>

* 2020-2023: Social Media Associated Editor, Canadian Journal of Public Health 
* 2019: Associate Editor, Canadian Journal of Public Health 
    - Associate Editor for 5 manuscripts 
* 2018-2019: Associated Editor, BMC Public Health 
    - Associate Editor for 13 manuscripts 
* 2015-2017: Board Member, Saskatchewan Epidemiology Association.
* 2015: Scientific Committee, Food Environments in Canada Symposium and Workshop.
* 2014: Scientific Committee, Active Living Research Conference.
* 2009-2011: Board Member, International Union of Health Promotion Student and Early Career Network (ISECN).
* 2009-2011: Board Member, Canadian Public Health Association Student Ad Hoc Committee.

## <span style="color:#81112c">Funding Reviews</span>

1. 2020 Tier 2 Canada Research Chair Renewal in Physical Activity and Health
1. 2020 Tier 2 Canada Research Chair Application in  Artificial Intelligence for Complex Health Data
1. 2020 MITACS Accelerate. Title: La navette autonome de la Petite Bourgogne répond-elle aux besoins de la communaute?
2. 2020 MITACS Accelerate. Title: Investigation of supportive policy for Active School Travel: Evidence- based recommendations for policies to promote active transportation for school journeys
3. 2020 European Science Foundation. Title: Data mining for real-time bicycle collisions control in cycling cities.
4. 2019 NSERC Discovery Grant Reviewer. Title: Merging measurement theory and technology for more accurate assessment of physical activity

## <span style="color:#81112c">Scientific Peer Review</span>

| Number of Reviews | Year | Example Journals |
|---------|------|-------------------|
| 3 | 2020 | British Medical Journal, Journal of Transportation and Health | 
| 8 | 2019 | British Medical Journal, Journal of Transportation and Health | 
| 2 | 2018 | Canadian Journal of Public Health | 
| 6 | 2017 | Nature - Science Reports, American Journal of Preventive Medicine | 
| 2 | 2016 | Canadian Journal of Public Health | 
| 4 | 2015 | Journal of Epidemiology and Community Health | 
| 2 | 2014 | Transportation Research Board | 
| 4 | 2013 | American Journal of Public Health | 
| 5 | 2011 | Social Science and Medicine | 
| 2 | 2011 | Annals of Behavioral Medicine | 

## <span style="color:#81112c">Expert Reviewers</span>

* 2018 - Canadian Institue of Planners - Policy Statement on Healthy Communities.  
* 2017 - Hybrid Active Living Potential Scale (HALPS) for the Canadian Armed Forces for Dr. Michael Spivock.  

## <span style="color:#81112c">Graduate Thesis Revisions</span>

* 2020: Ryan Pretty. Barriers To Recruitment And Participation In Physical Rehabilitation Research: A Mixed Methods Study Among People With Multiple Sclerosis. MSc Medicine. Memorial University.
* 2019: Kenneth Joshua. The association between physical active leisure, mental and physical health and life satisfaction among Canadian imnmigrants? MSc Human Kinetics and Recreation. Memorial University.
* 2018: John Snow. Can tri-axial accelrometers improve current clinical measures of spinal mobility in patients with axial spondyloarthiritis? MSc Clinical Epidemiology. Memorial University.
* 2017: Amita Goyal. Association and mediators of leasure time physical activity and mental health among people with spinal cord injury.MSc Human Kinetics and Recreation. Memorial University.

## <span style="color:#81112c">Media</span>

1. Asia Holloway. August 21, 2020. Investing in a Walk-able City Pays for Itself. [https://theindependent.ca/2020/08/21/letter-investing-in-a-walk-able-city-pays-for-itself/](https://theindependent.ca/2020/08/21/letter-investing-in-a-walk-able-city-pays-for-itself/)
1. VOCM News, August 25, 2020. [https://soundcloud.com/vocm/asia-holloway-masters-of-a-public-health-student-with-the-mun-beap-lab-health-economic-benefits-of-walking-in-st-johns?in=vocm/sets/vocm-morning-show](https://soundcloud.com/vocm/asia-holloway-masters-of-a-public-health-student-with-the-mun-beap-lab-health-economic-benefits-of-walking-in-st-johns?in=vocm/sets/vocm-morning-show)
1. VOCM News, August 25, 2020. [Walking in St. John’s Would Help Economy, says MUN Study](Walking in St. John’s Would Help Economy, says MUN Study)
1.  Mark Quinn, August 26, 2020. Making St. John's more walkable worth more than $100M over 10 years, say MUN researchers. [https://www.cbc.ca/news/canada/newfoundland-labrador/value-of-walking-1.5698911?__vfz=medium%3Dsharebar](https://www.cbc.ca/news/canada/newfoundland-labrador/value-of-walking-1.5698911?__vfz=medium%3Dsharebar)
1. CBC National Syndication. Obesity in Canada. February 13, 2020. 
    * CBC Cape Breton - Steve Sutherland 
    * Ontario AM - Wei Chen
    * Island Morning - Mitch Cormier
    * Windsor Morning - Tony Doucette
    * Newfoundland Morning - Bernice Hillier
    * St. John's Morning Show - Anthony Germain
    * The Trailbreaker - Loren McGinnis
    * Yukon Morning - Chris Walker
    * Kitchener-Waterloo - Craig Norris
    * Daybreak North - Carolina DeRyk
    * The Early Edition - Steven Quinn
1. Brett Bundale, February 7, 2020. A day in the life of a crossing guard. [https://www.thechronicleherald.ca/news/local/a-day-in-the-life-of-a-crossing-guard-its-a-precarious-profession-408524/](https://www.thechronicleherald.ca/news/local/a-day-in-the-life-of-a-crossing-guard-its-a-precarious-profession-408524/)
1. Jaimie Fitzpatrick, February 3, 2020. Vision Zero traffic safety policy. [https://www.cbc.ca/listen/live-radio/1-56-st-johns-morning-show/clip/15758803-vision-zero-traffic-safety-policy](https://www.cbc.ca/listen/live-radio/1-56-st-johns-morning-show/clip/15758803-vision-zero-traffic-safety-policy)
1. Jennifer Quesnel November 25, 2019. Interventions, Research, and Action in Cities Team Wave 1 results. [https://www.cbc.ca/news/canada/saskatoon/study-finds-half-of-riders-in-saskatoon-unaware-of-coming-bus-rapid-transit-1.5372445][https://www.cbc.ca/news/canada/saskatoon/study-finds-half-of-riders-in-saskatoon-unaware-of-coming-bus-rapid-transit-1.5372445
1. Ariana Kelland. March 25, 2019. After immigration trouble, this St. John's trainer is back to helping others [https://www.cbc.ca/news/canada/newfoundland-labrador/update-machel-rayner-1.5064383](https://www.cbc.ca/news/canada/newfoundland-labrador/update-machel-rayner-1.5064383)
2. CBC Cross Talk. Do you feel safe riding a bicycle? June 21, 2018. 
3. Juanita Mercer. N.L. urban residents advised to take the bus to better health. May 27, 2017.
[http://www.thetelegram.com/news/local/nl-urban-residents-advised-to-take-the-bus-to-better-health-213473/](http://www.thetelegram.com/news/local/nl-urban-residents-advised-to-take-the-bus-to-better-health-213473/)
4. Ted Blades. Taking the bus is better for your health. June 8, 2018.  http://www.cbc.ca/listen/shows/on-the-go/episode/15549559
5. Mark Quinn. Bike map aims to help St. John's cyclists steer clear of trouble. March 8, 2018. [http://www.cbc.ca/news/canada/newfoundland-labrador/bike-map-st-john-s-1.4567225](http://www.cbc.ca/news/canada/newfoundland-labrador/bike-map-st-john-s-1.4567225)
6. Andrea Kelly. Collisions and Close Calls. February 28, 2018 [https://gazette.mun.ca/research/collisions-and-close-calls/](https://gazette.mun.ca/research/collisions-and-close-calls/)
7. Susan Flagan. Walkability factors. June 6, 2017. [https://gazette.mun.ca/research/walkability-factors/](https://gazette.mun.ca/research/walkability-factors/)
8. CBC Cross Talk. Do activity trackers increase physical activity. October 25, 2016. 

## <span style="color:#81112c">Social Media</span>

* [Facebook](https://www.facebook.com/walkabilly): I have 99 followers on my Facebook page. The average reach per day of my Facebook page in August and September 2020 was 406 views, likes, and comments.
* [Twitter](https://twitter.com/walkabilly): I have 1541 followers on Twitter. I get on average 50,000 impressions on my Twitter page per month. 
* [Website](http://walkabilly.ca/home/): My website received 19,378 unique visitors in the past year. 

## <span style="color:#81112c">Community Collaborations</span>

I have done considerable work in the community of St. John's and area. Typically, I try and use my expertise in data analysis and healthy cities to help inform discussion about urban planning and traffic issues in St. John's.

For example, in winter of 2019-2020 there were a large number of fatal and severe injuries to pedestrians in St. John's. One of people was Dr. John Shirokoff an Engineering Professor at Memorial University. I was contacted by his sister about how to be involved in advocacy for pedestrian saftey in St. John's (see Appendix 1). As a result,  I conducted some data analysis of pedestrian crashes [https://github.com/walkabilly/sj_crashes/blob/master/avalon_collisions.md](https://github.com/walkabilly/sj_crashes/blob/master/avalon_collisions.md) and was asked to speak at an Emergency Panel on Pedestrian Safety in St. John's organized by the St. John's Social Justice Cooperative. As part of this type of work I often receive communication 

Similarly, a student of mine Asia Holloway released a report titled "Health and economic benefits of walking in St. John’s, Newfoundland and Labrador." The report garnered considerable of media attention. I received correspondence from a Newfoundlander now living in Ottawa who wanted to retire in NL but was concerned that they would not be able to walk safely in their beloved community (see Appendix 2). 

Finally, I was also a member of the Building Healthy Communities Provincial Linkages Committee from 2017 to 2019. This group was convened by the provincial government to plan healthy community initiatives throughout Newfoundland and Labrador. 




