---
title: "Curriculum vitae"
author: "Daniel Fuller"
output:
  html_document: 
    keep_md: yes
    toc: true
    toc_depth: 2
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Daniel Fuller, Ph.D.  
Associate Professor  
Department of Community Health and Epidemiology  
College of Medicine  
University of Saskatchewan  
104 Clinic Place  
Saskatoon, Saskatchewan, Canada S7N 2Z4  
E-mail: daniel.fuller@usask.ca  

## 1. PERSONAL

Employee ID: 

## 2. DEGREES

* Post-Doctoral Fellowship, University of Saskatchewan, 2014, Department of Community Health and Epidemiology, Public Health.
* Ph.D. Universite de Montreal, 2012, Department de Medecine Sociale et Preventive, Public Health.
* M.Sc. University of Saskatchewan, 2008, College of Kinesiology, Kinesiology.
* B.Sc. University of Saskatchewan, 2006, College of Kinesiology, Kinesiology.

## 3. CREDENTIALS
* _Nil_

## 4. APPOINTMENTS (INCLUDING JOINT) AND PROMOTIONS AT THE UNIVERSITY OF SASKATCHEWAN   
* Associate Professor, Department of Community Health and Epidemiology, University of Saskatchewan, July 2022 to present.  
* Assistant Professor (Term), School of Public Health, University of Saskatchewan, September 2014 to April 2016.  

## 5. MEMBERSHIPS AND AFFILIATIONS

__5.1 Associate Memberships at the University of Saskatchewan__    
* Associate Member, Department Computer Science, University of Saskatchewan, July 2022 to present

__5.2 Adjunct Appointments at Other Institutions__      
* Associate Member, Dalla Lana School of Public Health, University of Toronto, July 2019 to present
* Associate Member, School of Human Kinetics and Recreation, Memorial University, July 2022 to July 2025
* Member, College of Graduate and Postdoctoral Studies, University of Saskatchewan, September 2016 to present

__5.3 Affiliations__    
* Canadian Public Health Association
* International Society for Behavioral Nutrition and Physical Activity
* International Society for Physical Activity and Health

## 6. PREVIOUS POSITIONS RELEVANT TO UNIVERSITY OF SASKATCHEWAN EMPLOYMENT
* Associate Professor, School of Human Kinetics and Recreation, Memorial University, July 2021 to June 2022
* Assistant Professor, School of Human Kinetics and Recreation, Memorial University, August 2016 to June June 2021

## 7. LEAVES   
* Parental Leave, May 1, 2016 to July 30, 2016  
* Parental Leave, July 1, 2013 to December 1, 2013  

## 8. RECOGNITIONS

__Personal Recognitions__

* Canada Research Chair (Tier 2); CIHR; $500,000, 2021    
* Canada Research Chair (Tier 2); CIHR; $500,000, 2016     
* Travel Award; CIHR Institute of Population and Public Health; $900, 2012       
* Top Post-Doctoral Fellowship Award (Socio-Health); Saskatchewan Health Research Foundation; $0, 2012     
* Post-Doctoral Fellowships; CIHR; $45,000 × 2 years, 2012       
* Post-Doctoral Fellowships; Saskatchewan Health Research Foundation; $10,000, 2012      
* Meritorious Student Abstract; Society for Behavioral Medicine Conference; $0, 2012    
* Student Travel Award; United Kingdom Medical Research Council; $1,000, 2012    
* Dr. John Hastings Award; Canadian Public Health Association; $0, 2012       
* Travel Award; CIHR Institute of Population and Public Health; $1,800, 2012       
* Michael Smith Foreign Study Supplement; Social Science and Humanities Research Council of Canada; $6,000, 2012    
* Student Presentation Award; International Conference on Urban Health; $0, 2010      
* International Conference Scholarship; Department of Social and Preventive Medicine, Université de Montréal; $1,500, 2010        
* Joseph-Armand Bombardier Scholarship; Social Science and Humanities Research Council of Canada; $30,000 × 4 years, 2008     
* First Place Poster; University of Saskatchewan Life & Health Science Research Conference; $0, 2007    
* College of Kinesiology Graduate Scholarship; University of Saskatchewan; $15,000 × 2 years, 2007       
* Centennial Leadership Award; Government of Saskatchewan; $0, 2006    
* Book Award; College of Kinesiology, University of Saskatchewan; $500, 2005    

__Student Recognitions__

* Patricia Salazar, Best Student Presentation, Spatial Knowledge and Information Conference, $0, 2025    
* Meherun Nahar, Best Student Presentation, Saskatchewan Epidemiology Association Conference, $0, 2024    
* Bernard Asante, Artificial Intellgience for Public Health MSc Scholarship, $17,500 x 2 years, 2024    
* Katrina Pearman, CIHR MSc Scholarship, $17,500 x 2 years, 2023    
* Hiroshi Mamyia, Artificial Intellgience for Public Health Postdoctoral Scholarship, $25,000 x 2 years, 2022    

## 9. TEACHING ACTIVITIES

__9.1 Scheduled Instructional Activity__

| Year | Course Number, Title | Instructional Type | Enrollment | Yearly Instructional Hours | YCSH | 
|------|----------------|-------|--------------------|------------|----------------------------|-----|
| 2025-2026 | CHEP 898.3, Machine Learning Methods in Health Science | Co-Instructor | 9 | 36  | 324 |
| 2025-2026 | CHEP 801.3, Epidemiology 2 | Instructor | 8 | 36  | 288  |
| 2025-2026 | CHEP 990.1, Graduate Seminar | Instructor | 56 | 12 | 672 |
| 2025-2026 | CHEP 898.1, Introduction to R | Instructor | 20 | 12 | 240 |
| 2024-2025 | CHEP 898.3, Data Science for Epidemiology | Instructor | 7 | 36 | 252 |
| 2024-2025 | CHEP 990.1, Graduate Seminar | Instructor | 56 | 12 | 672 |
| 2024-2025 | CHEP 898.1, Introduction to R | Instructor | 20 | 12 | 240 |
| 2024-2025 | CHEP 990.1, Graduate Seminar | Instructor | 46  | 12  | 552 |
| 2024-2025 | CHEP 801.3, Epidemiology 2 | Instructor | 12 | 36  | 432 |
| 2023-2024 | CHEP 990.1, Graduate Seminar | Instructor | 57 | 12 | 684 |
| 2023-2024 | CHEP 816.3, Population Health Intervention Research | Instructor | 5  | 36 | 180 |
| 2023-2024 | CHEP 990.1, Graduate Seminar | Instructor | 57 | 12 | 684 |
| 2023-2024 | CHEP 801.3, Epidemiology 2 | Instructor | 6 | 36 | 216 |
| 2022-2023 | CHEP 990.1, Graduate Seminar | Instructor | 58 | 12 | 696 |
| 2022-2023 | CHEP 816.3, Population Health Intervention Research | Instructor | 4 | 36 | 144 |
| 2021-2022 | CHEP 990.1, Graduate Seminar | Instructor | 58 | 12 | 696 |
| 2021-2022 | CHEP 811.3, Professional Research Skills in Community and Population Health Research | Co-Instructor | 18 | 36 | 648 |

_Pre-appointment:_

| Year | Course Number, Title | Instructional Type | Yearly Instructional Hours |
|------|----------------|-------|--------------------|------------|
| 2021 | HKR 6130.3, Computer Applications for Physical Activity Measurement and Intervention | Instructor |  36 |  
| 2021 | HKR 6000.3,  Quantitative Methods in Physical Education | Instructor |  36 |
| 2020 | HKR 6000.3, Quantitative Methods in Physical Education | Instructor | 36 | 
| 2020 | HKR 6134.1, Grad Seminar | Instructor | 12 |  
| 2019 | HKR 6130.3, Computer Applications for Physical Activity Measurement and Intervention | Instructor | 36  |  
| 2019 | HKR 6134.1, Grad Seminar | Instructor | 12 |
| 2019 | HKR 6134.1,  Grad Seminar | Instructor | 12 |  
| 2019 | HKR 3400.3, Social Determinants of Health | Instructor | 36 |
| 2018 | HKR 6134.3, Seminar | Instructor | 36  |
| 2019 | HKR 4600.3, Research Methods | Instructor | 36 | 
| 2018 | HKR 6134.1, Grad Seminar | Instructor | 12  |  
| 2018 | HKR 3400.3,  Social Determinants of Health | Instructor | 36  |  
| 2018 | HKR 6134.1,  Grad Seminar | Instructor | 12 |  
| 2017 | HKR 6130.3, Computer Applications for Physical Activity Measurement and Intervention | Instructor | 36 | 
| 2017 | HKR 6134.1,  Grad Seminar | Instructor | 12 |  
| 2017 | HKR 3400.3, Social Determinants of Health | Instructor | 36 | 
| 2017 | HKR 6134.1, Grad Seminar | Instructor | 12  | 
| 2016 | HKR 6134.1, Grad Seminar | Instructor | 12  |  
| 2016 | PUBH 840.3, Public Health Capstone | Instructor | 36 |  
| 2016 | PUBH 840.3, Public Health Capstone | Instructor | 36 |  
| 2016 | PUBH 898.3, Social Epidemiology | Instructor | 36 |
| 2015 | PUBH 840.3, Public Health Capstone | Instructor | 36  | 
| 2015 | PUBH 804.3, Foundations of Public Health | Instructor | 36 |
| 2014 | PUBH 840.3, Public Health Capstone | Instructor | 36 |  
| 2014 | CHEP 898.3, Population Health Intervention Research | Instructor | 36 |  
| 2011 | MSO 6068c.1, Multilevel Modeling | Co-Instructor | 12 | 

__9.2 Unscheduled Instructional Activity__


| Year | Course Number, Title | Instructional Type | Enrollment | Yearly Instructional Hours |
|------|----------------|--------------------|------------|----------------------------|
| 2025-2026 | Artificial Intelligence for Public Health, Foundations of Machine Learning and Artificial Intelligence | Instructor | 20 | 4 |
| 2025-2026 | Artificial Intelligence for Public Health, Foundations of Machine Learning and Artificial Intelligence | Instructor | 20 | 4 |
| 2024-2025 | Artificial Intelligence for Public Health, Analysis of Biosignal Data | Instructor | 20 | 4 |

__9.3 Course and Program Development__ 

* CHEP 898.3, Machine Learning Methods in Health Science, University of Saskatchewan, January 2026 to April 2026    
    + _Co-developed new course on machine learning with Dr. Erfan Hoque_.   
    
* CHEP 898.3, Data Science for Epidemiology, University of Saskatchewan, January 2025 to April 2025
    + _Developed new course on applied machine learning. This course was re-revised and became the Machine Learning Methods in Health Sciences course above_.    

* CHEP 898.1, Introduction to R, University of Saskatchewan, October 2026 to November 2026   
    + _Developed a new one credit course introducing the R programming language and basic statistical concepts_.    

* CHEP 801.3, Epidemiology 2, University of Saskatchewan, September 2023 to December 2023    
  + _Redeveloped and delivered an advanced epidemiology course focused on causal inference._    

_Pre-appointment:_

* HKR 6130 Computer Applications for Physical Activity Measurement and Intervention. 2017. School of Human Kinetics and Recreation. Memorial University.    
* PUBH 898 Social Epidemiology. 2015. School of Public Health. University of Saskatchewan.    
* PUBH 840 Interdisciplinary Public Health Practice. 2014. School of Public Health. University of Saskatchewan.      
* CHEP 898 Population Health Intervention Research Reading course. 2011. Department of Community Health and Epidemiology. University of Saskatchewan.    

__9.4 Teaching Materials__

* _Nil_

__9.5 Other Teaching-Related Activities__

* Post-Graduate Public Health and Preventive Medicine Residency program Epidemiology and Biostatistics lead. Approximately 90minutes of teaching per month a variety of Epidemiology and Biostatistics topics. [https://github.com/walkabilly/phpm_epi_training/](https://github.com/walkabilly/phpm_epi_training/)  
* Helping Your Students Use AI Tools Effectively. Gwenna Moss Center for Teaching and Learning. University of Saskatchewan. May 14, 2026.    
* AI Exists: Rethinking Assessments. Gwenna Moss Center for Teaching and Learning. University of Saskatchewan. October 30, 2025.   
* Introduction to Machine Learning for Epidemiologists. One day workshop at the 2024 Saskatchewan Epidemiology Association Conference. September 26, 2024. [https://github.com/walkabilly/machine_learning_for_epi](https://github.com/walkabilly/machine_learning_for_epi)    

_Pre-appointment:_

* An Introduction to Documenting Teaching Activity and Effectiveness. 2019 Centre for Innovation in Teaching and Learning, Memorial University. 
* Transformational Teaching and Learning Day. 2017. Centre for Innovation in Teaching and Learning, Memorial University.     
* Teaching Improvement Project System (TIPS) Course. 2014. College of Medicine, University of Saskatchewan.    
* How People Learn: Seven Research-Based Principles for Smart Teaching. 2014. College of Medicine, University of Saskatchewan.    
* What the best college teachers do. Gwena Moss Center for Teaching Effectiveness. 2014. University of Saskatchewan.    
* Graduate Studies and Research 987: Science, Scientists, and Science-Societal Interactions: An introduction to the dynamics of science. Gwena Moss Center for Teaching Effectiveness. 2007. University of Saskatchewan.    
* Making Teaching Visible: Practical principles for peer review of teaching. 2007. Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.    
Teaching… if only we knew the questions? 2007. Gwena Moss Center for Teaching Effectiveness, University of Saskatchewan.    
* Most Effective Professor. 2016. School of Public Health Student Association. University of Saskatchewan.

## 10. SUPERVISION AND ADVISORY ACTIVITIES

__10.1 Undergraduate Student Supervision__

1. Claire Vo, USask Student Undergraduate Research Experience (SURE), Supervisor, 2023 (completed)
2. Pushpita Bohmik, USask Student Undergraduate Research Experience (SURE), Supervisor, 2023 (completed)

__10.2 Graduate Student Supervision__

1. Gavelin, Kade. Master's of Public Health Practicum. Supervisor. Community Health and Epidemiology. 2025- present (in progress).
1. Ramirez, Hector. MSc. Supervisor. Community Health and Epidemiology. 2025- present (in progress).
2. Salazar, Patricia. MSc. Supervisor. Community Health and Epidemiology. 2024- present (in progress).
3.  Asante, Bernard. MSc. Supervisor. Community Health and Epidemiology. 2024- present (in progress).
4. Pittman, Tyler. PhD. Supervisor. Community Health and Epidemiology. 2023- present (in progress).

__10.3 Graduate Theses Supervised__

1. Collins, Ryan. Psy D. Co-Supervisor. Associations between Circadian Rhythm, Physical Activity, Mood, and Cognitive Function During the First Year of Treatment for Breast Cancer. January 2026.
1. Pearman, Katrina. M.Sc. Supervisor. Community Health and Epidemiology. Examination of commercial wearable devices for children and youth who use manual wheelchairs. October 2025.
1. Sturrock, Shelby. PhD. Co-Supervisor. Dalla Lana School of Public Health. University of Toronto. The Impact of COVID-19 restrictions on Physical Activity in Canada. August 2025.
1. Nahar, Meherun. M.Sc., Supervisor. Community Health and Epidemiology. Association Between Public Transit Use and Happiness Across Four Canadian Cities: A Multilevel Analysis Using Longitudinal Data. June 2025.

__10.4 Post-Doctoral Supervision__

1. Lee, Naomi (Suela) Post-Doctoral Fellow. Supervisor, 2025- Ongoing
1. Mamiya, Hiroshi. Post-Doctoral Fellow. Supervisor, 2022-2023

__10.5 Staff Supervision__

1. Meridith Sones, Research Officer, Supervisor, 2025- ongoing
1. Karen Laberee, Research Officer, Supervisor, 2023- ongoing
1. Meisam Ghasedi, Research Assistant, Supervisor, 2024-2026

__10.6 Other Advisory Activities__

1. Casmir, Ibeh. MSc. Committee Member. Community Health and Epidemiology. 2023- 2025.
2. Ruporto, Raissa. MSc. Committee Member. Community Health and Epidemiology. 2023- 2025.
3. Jannati, Nazanin. PhD. Committee Member. Community Health and Epidemiology. 2023- ongoing.
4. Omot, Abang. MSc. Committee Member. Community Health and Epidemiology. 2023- ongoing.
5. Khrebtishcheva, Olha. MSc. MITACS. Community Health and Epidemiology. 2022- 2023.
6. Verity, Wendy. PhD. Committee Member. Community Health and Epidemiology. 2021- 2025.
7. Carter, Tori. Masters of Public Health Practicum. Supervisor. Community Health and Epidemiology. 2022.
8. Liu, Stephanie Masters of Public Health Practicum. Supervisor. Community Health and Epidemiology. 2022.

## 11. BOOKS AND CHAPTERS IN BOOKS

__11.1 Authored Books__

__Accepted:__   

* _Nil_

__Published:__  

* _Nil_

__11.2 Edited Books__

__Accepted:__   

* _Nil_

__Published:__   

* _Nil_

__11.3 Chapters in Books__

__Accepted:__   

1. Alhassan JAK, _Chima C_, & __Fuller D__. Health impacts of fare free transportation initiatives around the world: A scoping review of existing evidence. Health on the move. Volume 3. 

__Published:__   

* _Nil_


## 12. PAPERS IN REFEREED JOURNALS

Trainees supervised/co-supervised by Daniel Fuller _italics_  
Daniel Fuller __bold__  

__Accepted:__   

1. Singh J, Coleman T, Nyambi A, _Pittman T_, Dogget A, Andre F, Dupuis J, __Fuller D__. Collaboratively Building Teaching Resources for EDI in Epidemiology and Biostatistics. Canadian Journal of Public Health. Manuscript ID: CJPH-S-25-00649. 
    * __Contribution:__  I lead the workshop that was used to develop this publication. Japteg Singh a trainee from McGill lead the writing process.  Contribution 30%.
1. Lara D, Alaniz-Cantu E, Siddalingaiah S, Oliveira I, Chávez-Iñiguez A, DeJesus E, __Fuller D__, Marquez D, Vásquez D, Li D, McIntosh S, Ossip D, Cupertino A P, Cartujano-Barrera F. Actívatexto: Feasibility and acceptability of a mobile intervention that promotes smoking cessation and physical activity among Latinos. Cancer Research Communications. Manuscript Number: CRC-23-0519R.
    * __Contribution:__  I am consultant on this work related to wearables and machine learning.  Contribution 5%.
1. Chavez Uceda V, Orfin RH, Panizoni E, LanzDuret-Hernandez J, Hurtado-de-Mendoza A, Chávez-Iñiguez A, __Fuller D__, Marquez DX, Ossip DJ, Li D, Vasquez E, Ramos-Santiago JW, Carter-Bawa L, Aleese RM, Yousefi Nooraie R, McIntosh S, Cupertino AP, Cartujano-Barrera F. Feasibility of using a patient portal to recruit Latino adults into a smoking cessation and physical activity randomized clinical trial: A secondary analysis. Tobacco Induced Diseases. 2026. TID-01903-2026-02.
    * __Contribution:__  I am consultant on this work related to wearables and machine learning.  Contribution 5%.

__Published:__   

1. __Fuller D__, Ghasedi M, Achot G, Ross N. Can-ALE 2.0: Development of an open-source pipeline for the replication and extension of the Canadian Active Living Environments measure. Health Reports. [https://www.doi.org/10.25318/82-003-x202600600001-eng](https://www.doi.org/10.25318/82-003-x202600600001-eng).
    * __Contribution:__ I fully lead the study and supervised Meisam Ghasedi through the analysis. Contribution 60%.
1. __Fuller D__, Stanley K G. Discussion on 'INTACT: A method for integration of longitudinal physical activity data from multiple sources' by Jingru Zhang, Erjia Cui, Hongzhe Li, and Haochang Shou". Biometrics. 82(2). 2026. [https://doi.org/10.1093/biomtc/ujag114](https://doi.org/10.1093/biomtc/ujag114).
    * __Contribution:__ I lead the study and was the invited author for the commentary. Contribution 60%.
1. _McCullogh E_, Moore S A, Maher R, Jannati N, Muosieryir M, Macpherson A, Beck B, __Fuller D__. Implementation science frameworks for active and sustainable transportation: A scoping review. Transportation Research Interdisciplinary Perspectives. 38. 2026. [https://doi.org/10.1016/j.trip.2026.102020](https://doi.org/10.1016/j.trip.2026.102020).
    * __Contribution:__ I supervised Emily McCullogh who lead the study. Contribution 40%.
1. Keadle K S, Strath S, Giurgiu M, __Fuller D__, Marti M, Doherty A, Ahmadi M, Hyde E, Troiano R, Matthews C. The PhasED Framework: A Measurement Theory–Based Approach to Algorithm Development and Evaluation. Journal for the Measurement of Physical Behaviour. 9(1). 2026. [https://doi.org/10.1123/jmpb.2025-0074](https://doi.org/10.1123/jmpb.2025-0074).
    * __Contribution:__ I contributed to the writing and conceptual development of the publication. Contribution 5%.
1. Lapointe Y, Kapur A, Sharma A, Panter J, __Fuller D__, Mamiya H. Non-reproducibility of wearable accelerometer methods in protective association between physical activity and cardiovascular disease: a cohort study. Preventive Medicine. 2026. 209, 108603. [https://doi.org/10.1016/j.ypmed.2026.108603](https://doi.org/10.1016/j.ypmed.2026.108603).
    * __Contribution:__ I co-developed this study, and helped write this paper. The lead author Hiroshi Mamiya is my former Post Doctoral fellow. Contribution 10%.
1. __Mamiya H__, Thierry B, Poirier Stephens Z, Bell S, Diab E, Kestens Y, Winters M,  __Fuller D.__ Temporal shifts in area-level access to cycling infrastructure for equity-deserving groups in three Canadian cities: a descriptive epidemiologic study. Canadian Journal of Public Health. 2026. [https://doi.org/10.17269/s41997-026-01209-7](https://doi.org/10.17269/s41997-026-01209-7).
    * __Contribution:__ I co-developed this study, lead all data collection and helped write this paper. The first author Hiroshi Mamiya is my former Post Doctoral fellow. Contribution 30%.
2. __Pittman T__, Carr T, Muhajarine M, __Fuller D.__ Ownership change in American nursing homes during the COVID-19 pandemic and the relationship with measures in Donabedian's model of care quality. The Gerontologist. 2026. 66, 5. [https://doi.org/10.1093/geront/gnag021](https://doi.org/10.1093/geront/gnag021).
    * __Contribution:__ I co-developed this study. The first author Tyler Pittman is my current PhD student. Contribution 30%.
3. Khezri S, Thierry B, __Fuller D__, Winters M, Kanning M, El Geneidy A, Kestens Y. Exposure to built and social environments and momentary well-being: A geographic ecological momentary assessment study in Montreal. Environment International. 2026. 209, 110159. [https://doi.org/10.1016/j.envint.2026.110159](https://doi.org/10.1016/j.envint.2026.110159).
    * __Contribution:__ I co-developed this study. The first author Tyler Pittman is my current PhD student. Contribution 30%.
4. Beauchamp M K, D’Amore C, Raina P, McIlroy B, Adesina N, Ahmadi M, Alcock L, Becker C,  Doherty A, Donnelly A, Eslinger D W, Fenton SAM, __Fuller D__, Garcia-Aymerich J, Hausdorff J M, Hesketh K, Hillsdon M, Prince S P, Richardson J, Schrack JA, Stamatakis E, Van Ooteghem K, Wainwright T M, Wanigatunga AA, Western M J, Stathi A.  Establishing global standards on wearable technology for measuring mobility in aging populations: an international consensus exercise. Age and Aging. 2026. 55, 1. [https://doi.org/10.1093/ageing/afaf376](https://doi.org/10.1093/ageing/afaf376).
    * __Contribution:__ I was an invited expert author and participated in the consensus meeting for this paper. Contribution 10%.
5. Sones M, __Fuller D,__ Kestens Y, Thierry B, Winters M. Evaluating the protective effect of public open space on social connectedness: Evidence from a natural experiment cohort study in three Canadian cities. Health & Place. 2025. 96, 103541. [https://doi.org/10.1016/j.healthplace.2025.103541](https://doi.org/10.1016/j.healthplace.2025.103541).
    * __Contribution:__ I am the nominated Principal Investigator the INTERACT cohort study. I worked with the PhD student Meridith Sones and their supervisor Meghan Winters on analysis and writing.  Contribution 30%.
6. __Mamiya H__, __Fuller, D.__  Quantifying the Uncertainty of Human Activity Recognition Using a Bayesian Machine Learning Method: A Prediction Study. Physical Activity and Nutrition. 2025, 29(3):8–12. [https://doi.org/10.20463/pan.2025.0020](https://doi.org/10.20463/pan.2025.0020)
    * __Contribution:__  I provided the data and supervised Hiroshi Mamyia. This paper was part of Dr. Mamyia's Post Doctoral fellowship.  Contribution 40%.
7. __Verity W__, Foulds H, McIlduff C, __Fuller D__, Leis A. Understanding and Evaluating Access to Group-Based Older Adult Exercise Programing: Demographics, Distributions, and Dimensions of Levesque’s Access to Healthcare Framework. Sage Open Ageing. 10, 2025. [https://doi.org/10.1177/30495334251388160](https://doi.org/10.1177/30495334251388160).
    * __Contribution:__  I was a member of the advisory committee for Dr. Wendy Verity's PhD dissertation. This paper was part of the dissertation. I contributed expertise in analysis for geographic data and contributed to writing. Contribution 20%.
8. Plante C, Datta Gupta S, Bandara T, Beland D, Blaser C, Camillo CA, de Villa E, Dutton D, __Fuller D__, Hasselback J, Lix LM, Marouzi A, Muhajarine N, Notten G, Reimer B, Wolfson M, Young M, Yupanqui Concha D, Neudorf C. Multilevel estimation of the relative impacts of social determinants on income-related health inequalities in urban Canada: Protocol for the Canadian Social Determinants Urban Laboratory. JMIR Research Protocols. 2025;14:e71929. [http://dx.doi.org/10.2196/71929](http://dx.doi.org/10.2196/71929)
    * __Contribution:__  I am a member of this research team and contribute to the grant writing and protocol development. Contribution 10%.
9. __Ibeh C C__, __Fuller D__, & Alhassan J A K (2025). The health and socioeconomic impacts of free transportation initiatives: A scoping review. Journal of Transport & Health, 44(June), 102139. [https://doi.org/10.1016/j.jth.2025.102139](https://doi.org/10.1016/j.jth.2025.102139).
    * __Contribution:__  I was a member of the supervisory committee for Casmir Ibeh. I particiated in the data extraction, and writing for this paper. Contribution 30%.
10. __Sturrock S__, Moineddin R, Gesink D, Woodruff S, __Fuller D__. 2025. The effect of software and hardware version on Apple Watch activity measurement: A secondary analysis of the COVFIT retrospective cohort study. PLOS Digital Health. 4(4): e0000727. [https://doi.org/10.1371/journal.pdig.0000727](https://doi.org/10.1371/journal.pdig.0000727)
    * __Contribution:__  I was the primary supervisor for Dr. Shelby Sturrock. I contributed to study design, data analysis, and writing. Contribution 40%.
11. __Verity W__, Poirier Stephens Z, Lin H, Ottoni C A, Bourgeois E, Kestens Y, __Fuller D__, Manaugh K, Winters M. Health and equity considerations in policy and practice related to sustainable transportation interventions in four Canadian cities. Journal of Transport & Health. Volume 41, March 2025, 102009. [https://doi.org/10.1016/j.jth.2025.102009](https://doi.org/10.1016/j.jth.2025.102009).
    * __Contribution:__  I was a member of the advisory committee for Dr. Wendy Verity's PhD dissertation. I also lead the INTERACT cohort study. Contribution 10%.
12. Ferster, C., Laberee, K., Nelson, T., Winters, M., Cloutier, M-S., and __Fuller, D__. 2024. Top pedestrian concerns mapped by on WalkRollMap.org. Canadian Geographies / Géographies canadiennes. [https://doi.org/10.1111/cag.70005](https://doi.org/10.1111/cag.70005).
    * __Contribution:__  I contributed to developing the WalkRollMap.org app based on a Public Health Agency of Canada Grant. Contribution 10%.
13. Alhassan JAK, __Fuller D__, Woytowich R. (2025). The promises and perils of a free rural inter ‑ city transportation scheme: A mixed ‑ methods study from Northern Saskatchewan. Canadian Journal of Public Health. [https://doi.org/10.17269/s41997-024-00986-3](https://doi.org/10.17269/s41997-024-00986-3)
    * __Contribution:__  I conducted quantitative analyses and contributed to writing. Contribution 40%.
    * __5-year Journal Impact Factor:__ 3.0
14. Sousa-Silva R, Kestens Y, Poirier Stephens Z, Thierry B, Schoenig D, __Fuller D__, Winters M, Smargiassi A. 2024. Associations between types of urban vegetation and well-being measures: a cross-sectional study in Montreal, Canada. People and Nature. [https://doi.org/10.1002/pan3.10771](https://doi.org/10.1002/pan3.10771)
    * __Contribution:__  I lead the INTERACT study and contributed to data analysis, and writing. Contribution 20%.
15. __Schweitzer A M__, __Fuller D__, Fliss M D, Mitchell C J. 2025. Perspective on Strategies for Matching Across Age and Sex in Physiology Research: "Recreationally Active" is Not Good Enough." Frontiers in Physiology. Volume 15. [https://doi.org/10.3389/fphys.2024.1517355](https://doi.org/10.3389/fphys.2024.1517355)
    * __Contribution:__  I conceptualized the study with the student, contributed to writing and data analysis. Contribution 40%.
16. _Sturrock S_, Gesink D, Moineddin R, Woodruff S, Kestens Y, Winters M, __Fuller D__. Changes in physical activity among Canadian adults more than 6 months into the COVID-19 pandemic: a secondary analysis of the INTERACT cohort study. BMJ Open. 2024;14:e081583. [https://doi.org/10.1136/bmjopen-2023-081583](https://doi.org/10.1136/bmjopen-2023-081583) 
    * __Contribution:__  I was the primary supervisor for Dr. Shelby Sturrock. I contributed to study design, data analysis, and writing. Contribution 40%.
17. _Maher R A_, Wadden K P, __Fuller D__, Basset F, McGowan E. The current landscape of exercise and female fertility research: a narrative review. Reproduction. 2024. 168(1):e220317. [https://doi.org/10.1530/REP-22-0317](https://doi.org/10.1530/REP-22-0317).
    * __Contribution:__  I was the primary supervisor for Dr. Rebecca Maher during their MSc. I contributed to study design, and writing. Contribution 30%.
18. Poirier Stephens Z, Firth L C, Cantinotti M, __Fuller D__, Winters M, Kestens Y. 2023. Imagining and implementing healthy city interventions: Combined results from parallel concept mapping exercises in Montreal with community members and stakeholders. Canadian Journal of Public Health. 2024. 115(599-610). [https://doi.org/10.17269/s41997-024-00883-9](https://doi.org/10.17269/s41997-024-00883-9).
    * __Contribution:__  Zoe Poirier Stephens was a staff member on the INTERACT team. Contribution 15%.
19. Wadden K P, Hollohan N, Furneaux T, Maher R, Barrett C, __Fuller D__, Basset F A, Murphy A, Murphy S, Healey S, McGowan R, Twells L. 2024. PRO-FIT-CARE Study: The Feasibility Assessment of a Pilot Online Exercise Intervention for Persons Living with Obesity and Female Infertility. Frontiers in Sports and Active Living. [https://doi.org/10.3389/fspor.2024.1332376](https://doi.org/10.3389/fspor.2024.1332376)
    * __Contribution:__  Katie Wadden was a postdoctoral fellow working Laurie Twells. I contributed to the data collection, analysis, and writing. Contribution 10%.
20. _Musa S B_, _Rocky A_, Stanley K, Basset F, _Mamiya H_, Mongeon K, __Fuller D.__  2024. Comparing accelerometer processing metrics and hyper-parameter optimization for physical activity classification accuracy using machine learning methods. Journal for the Measurement of Physical Behaviour. [https://doi.org/10.1123/jmpb.2023-0033](https://doi.org/10.1123/jmpb.2023-0033).
    * __Contribution:__  Sumayyah Musa was my MSc students and this publication was her MSc thesis work. This work work Sumayyah led with other many other trainees from my lab. Contribution 30%.
21. Winters, M., __Fuller, D.__, Cloutier, M-S, Harris, M.A., Howard, A., Kestens, Y., Kirk, S.F.L, Macpherson, A., Moore, S.A., Rothman, L., Shareck, M., Tomasone, J., Laberee, K., Poirier-Stephens, Z., Sones, M., Ayton, D., Batomen, B., Bell, S., Collins, P.A., Diab, E., Giles, A., Hagel, B.E., Harris, M.S., Harris, P., Lachapelle, U., Manaugh, K., Mitra, R., Muhajarine, N., Muller Myrdahl, T., Pettit, C.J., Pike, I., Skouteris, H., Wachsmuth, D., Whitehurst, D.G.T. & Beck, B. Accepted. Building CapaCITY/É for Sustainable Transportation: Protocol for an Implementation Science Research Program in Healthy Cities. BMJ Open. [https://doi.org/10.1136/bmjopen-2024-085850](https://doi.org/10.1136/bmjopen-2024-085850)
    * __Contribution:__  I am a co-lead along with Dr. Winters, and Dr. Cloutier of the CapaCITY/É implementation science team grant. Contribution 20%.
22. __Fuller, D__, Stanojevic, S., Watson-Creed, G., Laura, Anderson., Natalya, Mason., Jennifer, Walker. Incorporating equity, diversity, and inclusion into the epidemiology and biostatistics curriculum: A workshop report and implementation strategies recommendations. Can J Public Health. 2024. [https://doi.org/10.17269/s41997-024-00876-8](https://doi.org/10.17269/s41997-024-00876-8).
    * __Contribution:__  I lead this work publishing results from a workshop on teaching EDIA in Epidemiology. Contribution 50%.
23. Doiron D, Setton E N, Seyer J, Redivo A, McKee A, Noaeen M, Patel P, Booth G L, Brauer M, __Fuller D__, Kestens Y, Rosella L C, Stieb D, VilleneuveP, Brook J R. HealthyPlan.City: A Web Tool to Support Urban Environmental Equity and Public Health in Canadian Communities. 2024. Journal of Urban Health. [https://doi.org/10.1007/s11524-024-00855-x](https://doi.org/10.1007/s11524-024-00855-x).
    * __Contribution:__  I am a member of the advisory board for the HealthyPlan.City project. Contribution 10%.
24. _Kiani B_, Thierry B, Apparicio P, Firth C, __Fuller D__, Winters M, Kestens Y. Associations between gentrification, census tract-level socioeconomic status, and cycling infrastructure expansions in Montreal, Canada. SSM - Population Health. 25, March 2024, 101637. [https://doi.org/10.1016/j.ssmph.2024.101637](https://doi.org/10.1016/j.ssmph.2024.101637).
    * __Contribution:__  Dr. Kiani was a postdoctoral fellow working with the INTERACT project. I contributed to writing and analysis. Contribution 15%.
25. _Barua A_, __Fuller D__, Jiang X. Investigating The Effectiveness of Simple Heuristic Features in Solving Sensor Orientation and Sensor Placement Problems in Human Activity Recognition Using A Single Smartphone Accelerometer. BioMed Eng OnLine 23, 21 (2024). [https://doi.org/10.1186/s12938-024-01213-3](https://doi.org/10.1186/s12938-024-01213-3).
    * __Contribution:__  I was the co-supervisor for Arnab Barua's MSc thesis. This publication is one of his thesis publications. I contributed data, supervision, and consulted on analysis. Contribution 20%.
26. Bird, M. Barnett, T.A. Mathieu, M-E. **Fuller, D.** Geetanjali D D. Multidimensional School Features Associated with Physical Activity among Youth at Risk of Obesity: An Exploratory Principal Component and Generalized Estimating Equation Analysis. BMC Public Health. 2023 Oct 16;23(1):2010. [https://doi.org/10.1186/s12889-023-16889-w](https://doi.org/10.1186/s12889-023-16889-w)
    * __Contribution:__  I contributed data analysis and writing support. Contribution 10%. 
    
27. Prince SA, Lang JJ, de Groh M, Alacoque M, Badland H, Barnett A, Brandon N, Butler GP, Casu G, Cerin E, Colley RC, de Lannoy L, Demchenko I, Ellingwood H, Evenson K, Faulkner G, Fridman L, Friedenreich C, __Fuller DL__, Fuselli P, Giangregorio LM, Gupta N, Hino A, Hume C, Isernhagen B, Jalaludin B, Lakerveld J, Larouche R, Lemon S, Baugh Littlejohns L, Loucaides CA, Maddock J, McCormack G, Mehta A, Milton K, Mota J, Ngo VD, Owen N, Oyeyemi A, Palmeira A, Rainham D, Rhodes R, Ridgers N, Roosendaal I, Rosenberg D, Schipperijn J, Slater S, Storey K, Tremblay MS, Tully M, Vanderloo L, Veitch J, Vietinghoff C, Whiting S, Yang L, Geneau R. Prioritizing a research agenda on built environments and physical activity: a twin panel Delphi consensus process with researchers and knowledge users. Int J Behav Nutr Phys Act 20, 144 (2023). [https://doi.org/10.1186/s12966-023-01533-y](https://doi.org/10.1186/s12966-023-01533-y).
    * __Contribution:__  This was a large Delphy study. I was an expert participant and participants were invited to be authors. I reviewed the publication. Contribution 5%. 
28. __Fuller D__, Shareck M, Sersli S, Priebe C, Alfosool A, Lang J J, Wolfe Phillips E. Common measures of green and blue space for built environment, health equity and intervention research: a scoping review. 2023. Cities & Health. [https://doi.org/10.1080/23748834.2023.2260134](https://doi.org/10.1080/23748834.2023.2260134).
    * __Contribution:__  I led this paper with Dr. Shareck. I designed the study, conducted the review, analysis, and wrote the manuscript. Contribution 30%. 
29. Shareck M, __Fuller D__, Sersli S, Priebe C, Alfosool A, Lang J J, Wolfe Phillips E. Measuring walkability and bikeability for health equity and intervention research: a scoping review. 2023. Cities & Health. [https://doi.org/10.1080/23748834.2023.2260133](https://doi.org/10.1080/23748834.2023.2260133).
    * __Contribution:__  I led this paper with Dr. Shareck. I designed the study, conducted the review, analysis, and wrote the manuscript. Contribution 30%. 
30. Biswas A, Chen C, Dobson KG, Prince SA, Vahid Shahidi F, Smith PM, __Fuller D.__ Identifying the sociodemographic and work-related factors related to workers’ daily physical activity using a decision tree approach. BMC Public Health. 2023. 23: 1853.  [https://doi.org/10.1186/s12889-023-16747-9](https://doi.org/10.1186/s12889-023-16747-9).
    * __Contribution:__  I was invited to this paper for my exertise in machine learning. I consulted on analysis and reviewed the paper. Contribution 20%. 
31. _Kiani B_, Poirier-Stephens Z, Thierry B, Firth C, __Fuller D__, Winters M, Kestens Y. Gentrification, Neighborhood Socioeconomic Factors and Urban Vegetation Inequities: A Study of Greenspace and Tree Canopy Increases in Montreal, Canada. 2023. Landscape and Urban Planning. 240, 104871. [https://doi.org/10.1016/j.landurbplan.2023.104871](https://doi.org/10.1016/j.landurbplan.2023.104871)
    * __Contribution:__  Dr. Kiani was a postdoctoral fellow working with the INTERACT project. I contributed to writing and analysis. Contribution 15%.
32. Theirry B, Stanley K, Kestens Y, Winters M, __Fuller D.__ 2023. Comparing location data from smartphone and dedicated GPS devices: Implications for epidemiological research. American Journal of Epidemiology. [https://doi.org/10.1093/aje/kwad176](https://doi.org/10.1093/aje/kwad176).
    * __Contribution:__  I led the analysis and writing with Benoit Theirry who is a staff member for the INTERACT project. Contribution 40%.
33. _Kiani B_, Mamiya H, Thierry B, Firth C, __Fuller D__, Winters M, Kestens Y. The temporal sequence between gentrification and cycling infrastructure expansions in Montreal, Canada. Habitat International. 2023. 139, 102899. [https://doi.org/10.1016/j.habitatint.2023.102899](https://doi-org.cyber.usask.ca/10.1016/j.habitatint.2023.102899).
    * __Contribution:__  Dr. Kiani was a postdoctoral fellow working with the INTERACT project. I contributed to writing and analysis. Contribution 15%.
34. Youngbloom A J, Thierry B, __Fuller D__, Kestens Y, Winters M, Hirsch J A, Micheal Y L, Firth C L. Gentrification, perceptions of neighborhood change, and mental health in Montréal, Québec. 2023. SSM Population Health. Volume 22, 101406.[https://doi.org/10.1016/j.ssmph.2023.101406](https://doi.org/10.1016/j.ssmph.2023.101406).
    * __Contribution:__  As a lead for the INTERACT project I contributed project data and reviewed the paper. Contribution 5%.
35. Laberee K, Nelson T, Boss D, Ferster C, Hosford K, __Fuller D__, Cloutier M-S, and Winters M. WalkRollMap.org: Crowdsourcing barriers to mobility. Frontiers in Rehabilitation Science. 2023. Volume 4. [https://doi.org/10.3389/fresc.2023.1023582](https://doi.org/10.3389/fresc.2023.1023582)
    * __Contribution:__  I am a co-investigator on this project. I contributed analysis work and manuscript writing. Contribution 10%.
36. Flood S, Thompson B, Faulkner G, Vanderloo L M, Blackett B, Dolf M, Latimer-Cheung A, Duggan M, Di Sebastiano K M, Lane K N, Brouwers M C, McKenna J, Chulak-Bozzer T, __Fuller D__, Ruissen G R, Sturrock S L, Tomasone J R. Targeting Post-Secondary Students’ Movement Behaviours via the ParticipACTION App: Protocol for Using Intervention Mapping to Design and Implement an App-Based Intervention based on the 24-Hour Movement Guidelines. 2023. 12:e39977. JMIR Research Protocols. [https://doi.org/10.2196/39977](https://doi.org/10.2196/39977)
    * __Contribution:__  I am a co-investigator on this project. I contributed analysis work and manuscript writing. Contribution 5%.
36. Koohsari M J, McCormack G R, Nakaya T, Yasunaga A, __Fuller D__, Nagai Y, Oka K. The Metaverse, the built environment, and public health: Opportunities and uncertainties. JMIR. 2023. 25:e43549. [https://doi.org/10.2196/43549](https://doi.org/10.2196/43549).
    * __Contribution:__  I was invited to this paper as an expert on built environement and technology. Contribution 15%.
38. Hernández-Torres R, Alaniz-Cantu E, Bautista Rojas MV, Lara D, Merritt S, DeJesus E, D’Abundo ML, McIntosh S, Ossip DJ, Fuller D, Rivera MP, Cupertino AP, Cartujano-Barrera F. Understanding the perspectives of Latino adults who smoke on physical activity: A qualitative study. International Journal of Environmental Research and Public Health. 2023, 20(4), 3128; [https://doi.org/10.3390/ijerph20043128](https://doi.org/10.3390/ijerph20043128). 
    * __Contribution:__  I am a technology and machine learning consultant on this project. I contributed to study design and manuscript writing. Contribution 5%.
38. Plante C, Sandhu N, Bandara T, __Fuller D__, Neudorf C. Defining the “Local Public Health Unit” for Public Health Systems and Services Research in Canada. Canadian Journal of Public Health. 2023. 114, 5–9. [https://doi.org/10.17269/s41997-022-00714-9](https://doi.org/10.17269/s41997-022-00714-9)
    * __Contribution:__  I contributed conceptual expertise on spatial data and administrative boundaries. I also drafted sections of the manuscript.  Contribution 10%.
39. Karmann J, Najjar M, Ottoni C, Shareck M, Lord S, Winters M, __Fuller D__, Kestens Y. “They didn’t have to build that much”: A qualitative study on the emotional response to urban change in the Montreal context. Emotion, Space and Society. 2023, 26, 100937. [https://doi.org/10.1016/j.emospa.2022.100937](https://doi.org/10.1016/j.emospa.2022.100937)
    * __Contribution:__  Dr. Karmann is a former PhD student working with the INTERACT project. This paper was part of her PhD work. I reviewed drafts of the manuscript.  Contribution 5%.
40. _Musa S B_, Ellis R, Chafe B, Sturrock S L, Maher R A, Cullen K, __Fuller D__. Wearable device validity in measuring steps, energy expenditure, and heart rate across age, gender, and body mass index: Data analysis from a systematic review. Journal of Physical Activity and Health. 2023. [https://doi.org/10.1123/jpah.2022-0160](https://doi.org/10.1123/jpah.2022-0160)
    * __Contribution:__  Sumayyah Musa was my MSc student. This work was part of her MSc thesis.  Contribution 30%.
41. Doiron D, Setton E, Brook J, Kestens Y, McCormack G R, Winters M, Shooshtari M, Azami S, __Fuller D.__ Predicting walking-to-work using Google Street View imagery and deep learning in seven Canadian cities. Scientific Reports. 18380 (2022). [https://doi.org/10.1038/s41598-022-22630-1](https://doi.org/10.1038/s41598-022-22630-1).
    * __Contribution:__  I conducted analysis and contributed to several drafts of the manuscript.  Contribution 30%.
42. Auchincloss A H, Michael Y L, Niamatullah A, Li S, Melly S J, Pharis M L, __Fuller D__. Changes in physical activity after joining a bikeshare program: a cohort of new bikeshare users. International Journal of Behavioral Nutrition and Physical Activity. 19, 132. 2022. [https://doi.org/10.1186/s12966-022-01353-6](https://doi.org/10.1186/s12966-022-01353-6).
    * __Contribution:__  I was a collaborator on this project. I contributed to study design, data analysis, and manuscript preparation.  Contribution 20%.
43. _Phillips K_, Stanley K, __Fuller D__. A Theory-based Model of Cumulative Activity. Scientific Reports. 12, 15635. 2022. [https://doi.org/10.1038/s41598-022-18982-3](https://doi.org/10.1038/s41598-022-18982-3).
    * __Contribution:__  I was a co-supervsior for Kole Phillips MSc thesis. This publication is his MSc work.  Contribution 30%.
44. _Afosool A_, __Fuller D__, Chen Y. ALF-Score++, a novel approach to transfer knowledge and predict network-based walkability scores across cities. 2022. Scientific Reports. 12:14013. [https://doi.org/10.1038/s41598-022-17713-y](https://doi.org/10.1038/s41598-022-17713-y).
    * __Contribution:__  I was a co-supervsior for Ali Alfosool's PhD thesis. This publication is one of the publications from his PhD work.  Contribution 30%.
45. Barua A, __Fuller D__, Musa S B, Jiang X. Exploring Orientation Invariant Heuristic Features with Variant Window Length of 1D-CNN-LSTM in Human Activity Recognition. 2022. Biosensors, 12(7), 549. [https://doi.org/10.3390/bios12070549](https://doi.org/10.3390/bios12070549)
    * __Contribution:__  I was a co-supervsior for Arnab Barua's MSc thesis. This publication is one of the publications from his MSc work.  Contribution 30%.
46. _Firth C L_, Kestens Y, Winters M, Stanley K, Bell S, Thierry B, Phillips K, Poirier-Stephens Z, __Fuller D__. Using combined Global Position System and accelerometer data points to examine how built environments and gentrification are associated with physical activity in four Canadian cities. 2022. International Journal of Behavioral Nutrition and Physical Activity, 19, 78. [https://doi.org/10.1186/s12966-022-01306-z](https://doi.org/10.1186/s12966-022-01306-z).
    * __Contribution:__  Dr. Firth was a postdoctoral fellow working with the INTERACT project. We developed the study design, analysis, and wrote the manuscript together. Contribution 40%.
47. _Afosool A_, __Fuller D__, Chen Y. ALF-Score - A novel approach to build a predictive network-based walkability scoring system. PLOS ONE 17(6): e0270098. [https://doi.org/10.1371/journal.pone.0270098](https://doi.org/10.1371/journal.pone.0270098).
    * __Contribution:__  I was a co-supervsior for Ali Alfosool's PhD thesis. This publication is one of the publications from his PhD work.  Contribution 30%.
48. _Khataeipour S_, Rahimipour Anaraki J, Bozorgi A, Rayner M, Basset F, __Fuller D__. Predicting Movement Types Using Smartphone Accelerometers at Three Different Wear Locations; Hands, Pants Pocket, Backpack. BMJ Open Sport & Exercise. 2022;8:e001242. [https://bmjopensem.bmj.com/content/8/2/e001242](https://bmjopensem.bmj.com/content/8/2/e001242)
    * __Contribution:__  I was a supervsior for SeyedJavad Khataeipour's co-op placement in Computer Science. This publication is from his co-op placement.  Contribution 30%.
49. Mah C L. Foster K, Jago E, Hajizadeh M, Luongo G, Taylor N, __Fuller D__, Yi Y, Esan K, Lukic R, MacDonald B, Boyd H, McIver H, Khederi A, Clarke M, Wranik D, Brimblecombe J, Peeters A. Study protocol for CELLAR: population-based observational study to monitor dietary intakes and purchasing during COVID-19 in four Canadian provinces. BMJ Open. 2022;12(4):e061660. [https://pubmed.ncbi.nlm.nih.gov/35477873/](https://pubmed.ncbi.nlm.nih.gov/35477873/).
    * __Contribution:__  I am a collaborator on the CELLAR. I contributed to study design and manuscript writing.  Contribution 5%.
50. _Roy A_, __Fuller D__, Kendron P, Nelson T. Assessing the role of geographic context in transportation mode detection from GPS data. Journal of Transport Geography. 2022;100:103330. [https://doi.org/10.1016/j.jtrangeo.2022.103330](https://doi.org/10.1016/j.jtrangeo.2022.103330)
    * __Contribution:__  I am a collaborator on the CELLAR. I contributed to study design and manuscript writing.  Contribution 5%.
51. __Fuller D__, Ferber R, Stanley K. Why Machine Learning (ML) has failed physical activity research and how we can improve. BMJ Open Sport & Exercise. 2022;8:e001259. [https://doi.org/10.1136/bmjsem-2021-001259](https://doi.org/10.1136/bmjsem-2021-001259) 
    * __Contribution:__  I lead the conceptual drafting and writing of this manuscript.  Contribution 80%.
52. _Tobin M_, _Orychock K_, Ross N, Hajna S, DeVries M, Villeneuve P J, Frank L D, McCormack G, Wasfi R, Steinmetz-Wood M, Gilliland J, Booth GL, Winters M, Kestens Y, Manaugh K, Rainham D, Gauvin L, Widener M J, Muhajarine N, _Luan H_, __Fuller D__. Active Living Environments: Re-Framing and Defining the Concept of Walkability. BMC Public Health. 2022. 22, Article number: 450. [https://doi.org/10.1186/s12889-022-12747-3](https://doi.org/10.1186/s12889-022-12747-3)
    * __Contribution:__  I lead the workshop that was used to develop this publication. My MSc students Melissa Tobin and Kassia Orychock wrote the paper with the support of my postdoctoral fellow Dr. Luan.  Contribution 30%.

_Pre-appointment:_

59. _Luan H_, __Fuller D__. Urban form in Canada at a small-area level: quantifying “compactness” and “sprawl” with Bayesian multivariate spatial factor analysis. Environment and Planning B: Urban Analytics and City Science. December 2021.  [https://doi.org/10.1177%2F23998083211062901](https://doi.org/10.1177%2F23998083211062901)
54. Wasfi R, Poirier Stephens Z, Sones M, Laberee K, Gough M, Pugh C, __Fuller D__, Winters M, Kestens Y. Recruiting Participants for Population Health Intervention Research: Effectiveness and Costs of Recruitment Methods for the INTErventions, Research, and Action in Cities Team (INTERACT) study. Journal of Medical Internet Research.  Vol 23, No 11. [https://doi.org/10.2196/21142](https://doi.org/10.2196/21142)
55. Diaz F, Abbasi J, __Fuller D__, Diab E. Canadian Transit Agencies Response to COVID-19: Understanding Strategies, Information Accessibility and the Use of Social Media. Transportation Research Interdisciplinary Perspectives. 2021: 12, 100465. [https://doi.org/10.1016/j.trip.2021.100465](https://doi.org/10.1016/j.trip.2021.100465).
56. __Fuller D__, Bell S, Firth C L, Muhajarine N, Nelson T, Stanley K S, Sones M, Smith J, Thierry B, Laberee K, Poirier Stephens Z, Philips K, Kestens Y, Winters M. Wave 1 results of the INTerventions, Research, and Action in Cities Team (INTERACT) cohort study: Examining the spatio-temporal measures for urban environments and health. Health & Place. [https://doi.org/10.1016/j.healthplace.2021.102646](https://doi.org/10.1016/j.healthplace.2021.102646)
57. __Fuller D__, Rahimipour Anaraki J, _Simango B_, Dorani F, Bozorgi F, _Luan D_, Basset F. 2021. Predicting lying, sitting, walking, and running using Apple Watch and Fitbit data. BMJ Open Sport & Exercise Medicine. 2021;7:e001004. [doi.org/10.1136/bmjsem-2020-001004](doi.org/10.1136/bmjsem-2020-001004).
57. Sones M, Firth CL, __Fuller D__, Holden M, Kestens Y, Winters M. Situating social connectedness in healthy cities: A conceptual primer for research and policy. Cities and Health. 6:6, 1179-1192. [https://doi.org/10.1080/23748834.2021.1926657](https://doi.org/10.1080/23748834.2021.1926657)
59. _Brondeel, R._, Kestens, Y., _Rahimipour Anaraki, J._, Stanley, K., Thierry, B., __Fuller, D.__ Converting raw accelerometer data to activity counts using open source code in MATLAB, Python, and R – a comparison to ActiLife activity counts. Journal for the Measurement of Physical Behaviour. 2021;(4)3, 205–211. [https://doi.org/10.1123/jmpb.2019-0063](https://doi.org/10.1123/jmpb.2019-0063)
60. Alhassan J A K, Gauvin L, Muhajarine N, __Fuller D__. Improving health through multisectoral collaboration: enablers and barriers. Canadian Journal of Public Health. [doi.org/10.17269/s41997-021-00534-3](doi.org/10.17269/s41997-021-00534-3)
61. Firth, C.L., Thierry, B., __Fuller, D.__, Winters, M., Kestens, Y. Gentrification, Urban Interventions, and Equity (GENUINE): a map-based gentrification tool for Canadian Metropolitan Areas. 2021. Health Reports. [https://www.doi.org/10.25318/82-003-x202100500002-eng](https://www.doi.org/10.25318/82-003-x202100500002-eng)
62. _Lotoski L_, **Fuller D**, Stanley K, Rainham D, Muhajarine N.The effect of season and neighbourhood built environment on GPS-derived home area sedentary behaviour in 9-14 year old children. 2021. International Journal of Environmental Research and Public Health. 2021, 18(4), 1968 [https://doi.org/10.3390/ijerph18041968](https://doi.org/10.3390/ijerph18041968).
63. Whitehurst, D., DeVries, D., __Fuller, D.__, Winters, M. An economic analysis of health-related benefits of bicycle infrastructure investment in three Canadian cities. 2021. PLOS One. 2021, 16(2): e0246419. [https://doi.org/10.1371/journal.pone.0246419](https://doi.org/10.1371/journal.pone.0246419)
64. Firth CL, Poirier Stephens Z,  Cantinotti, M,  __Fuller D,__ Kestens Y, Winters M. Successes and failures of built environment interventions: using concept mapping to assess stakeholder perspectives in four Canadian cities. Social Science and Medicine. 2021;268:113383. [https://doi.org/10.1016/j.socscimed.2020.113383](https://doi.org/10.1016/j.socscimed.2020.113383)
65. Bree. S., __Fuller. D.__, Diab, E. Access to Transit? Validating Local Transit Accessibility Measures Using Transit Ridership. Transportation Research Part A: Policy and Practice. 2020;141:430-442. [https://doi.org/10.1016/j.tra.2020.09.019](https://doi.org/10.1016/j.tra.2020.09.019)
66. _Hosford, K._ Laberee, K. __Fuller, D.__ Kestens, Y. Winters, M. Are They Really Interested but Concerned? A Mixed Methods Exploration of the Geller Bicyclist Typology. Transportation Research Part F: Psychology and Behaviour. 2020;75:26-36. [https://doi.org/10.1016/j.trf.2020.09.018](https://doi.org/10.1016/j.trf.2020.09.018)
67. __Fuller, D.__, Colwell, E., Low, J., _Orychock, K._, _Tobin, M._, _Simango, B._, Buote, R., _van Heerden, D._, _Slade, L._, _Luan, H._, _Taylor, G. A. N._, Cullen, K. Systematic Review of the Reliability and Validity of Commercially Available Wearable Devices for Measuring Steps, Energy Expenditure, and Heart Rate. JMIR MHealth. JMIR Mhealth Uhealth 2020;8(9):e18694. [http://dx.doi.org/10.2196/18694](http://dx.doi.org/10.2196/18694)
68. Brandon Calles M, Hosford K, Winters M, Gauvin L, __Fuller D__. The impact of implementing public bicycle share programs on bicycle crashes: the International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). Transport Findings. 2020. September. [https://doi.org/10.32866/001c.16724](https://doi.org/10.32866/001c.16724)
69. _Roy A_, __Fuller D__, Stanley K, Nelson T. Classifying Transportation Mode from Global Positioning Systems and accelerometer data: A machine learning approach. Transport Findings. 2020. September. [https://doi.org/10.32866/001c.14520](https://doi.org/10.32866/001c.14520)
70. Nelson, T., Ferster, C., Laberee, K. __Fuller, D.__, Winters, M. Crowdsourced data for bicycling research and practice. Transport Reviews. 2020.  [https://doi.org/10.1080/01441647.2020.1806943](https://doi.org/10.1080/01441647.2020.1806943)
71. Firth CL, __Fuller D,__ Wasfi R, Kestens Y, Winters M. Causally speaking: challenges in measuring gentrification for population health research. Health & Place. 2020. 63, 102350. [https://doi.org/10.1016/j.healthplace.2020.102350](https://doi.org/10.1016/j.healthplace.2020.102350).
72. Auchincloss, A., Michael, Y., __Fuller, D.__, Li, S., Niamatullah, S., Fillmore, C., Setubal, C.,  Bettigole, C. Designing bikeshare to promote equity: baseline analysis of the Drexel Neighborhood Transportation Study (DNTS) cohort. Journal of Transportation and Health. 2020, 16, 100836. [https://doi.org/10.1016/j.jth.2020.100836](https://doi.org/10.1016/j.jth.2020.100836)
73. _Zhang R_, Stanley K, **Fuller D,** Bell S. Differentiating Population Spatial Behavior using Representative Features of Geospatial Mobility (ReFGeM). Transactions on Spatial Algorithms and Systems. 2020:6(1). [https://dl.acm.org/doi/10.1145/3362063](https://dl.acm.org/doi/10.1145/3362063)
74. _Hosford, K._, Winters, M., Gauvin, L., Camden, A., Dube, A-S., Friedman, S. M., __Fuller, D.__. Evaluating the impact of implementing public bicycle share programs on cycling: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Journal of Behavioural Nutrition and Physical Activity. 2019:16, 107. [https://doi.org/10.1186/s12966-019-0871-9](https://doi.org/10.1186/s12966-019-0871-9)
75. _Hosford, K._, Winters, M., __Fuller, D.__. Commentary on: Burn Calories, Not Fuel! The effects of bikeshare programs on obesity rates. Transportation Research Part D: Transport and Environment. 2019:75, 121-122. [https://doi.org/10.1016/j.trd.2019.08.028](https://doi.org/10.1016/j.trd.2019.08.028) 
76. __Fuller, D.__, Stanley, K. G. The future of activity space and health research. Journal of Health and Place. 2019:58, 102131. [https://doi.org/10.1016/j.healthplace.2019.05.009](https://doi.org/10.1016/j.healthplace.2019.05.009)
77. Thigpen, C. Winters, M. **Fuller, D.** Gauvin, L. Therrien, Nelson, T. Who is ready to bicycle?: Categorizing and mapping bicyclists with behavior change theory. Transport Policy. 2019:83, 11-17. [https://doi.org/10.1016/j.tranpol.2019.07.011](https://doi.org/10.1016/j.tranpol.2019.07.011)
78. Engler-Stringer, R. **Fuller, D.** Abeykoon, A.M. H. Olauson, C. Muhajarine, N. Perspectives on the Failure of New Grocery Store Interventions in Former Food Deserts. Health Education and Behaviour. 2019, 45(5). [https://doi.org/10.1177/1090198119853009](https://doi.org/10.1177/1090198119853009)
79. *Breslin, S.*, Shareck, M., **Fuller, D.** Research ethics for mobile sensing device use by vulnerable populations. Social Science and Medicine. 2019;232:50-57. [https://doi.org/10.1016/j.socscimed.2019.04.035](https://doi.org/10.1016/j.socscimed.2019.04.035)
80. __Fuller, D.,__ *Luan, H.,* Buote, R., Auchincloss, A. H. Impact of a public transit strike on public bicycle share use: An interrupted time series natural experiment study. Journal of Transportation and Health. 2019;13:137-142. [https://doi.org/10.1016/j.jth.2019.03.018](https://doi.org/10.1016/j.jth.2019.03.018)
81. *Luan, H*., *Ramsay, D.*, **Fuller, D.** Household income, active travel, and their interacting impact on body mass index in a sample of urban Canadians: A Bayesian spatial analysis. International Journal of Health Geographics. 2019;18(4). [https://doi.org/10.1186/s12942-019-0168-x](https://doi.org/10.1186/s12942-019-0168-x)
82. Branion-Calles M, Nelson T, **Fuller D**, Gauvin L, Winters M. Associations between spatial access to bicycle-specific infrastructure, sociodemographic characteristics, and city-wide safety perceptions of bicycling: a cross-sectional survey of bicyclists in 6 Canadian and U.S. cities. Transportation Research Part A: Policy and Practice. 2019, 123: 229-239. [https://doi.org/10.1016/j.tra.2018.10.024](https://doi.org/10.1016/j.tra.2018.10.024) 
83. Kestens Y, Winters M, **Fuller D,** Bell S, Berscheid J, Brondeel R, Cantinotti M, Datta G, Gauvin L, Gough M, Laberee K, Lewis P, Lord S, Luan H, McKay H, Morency C, Muhajarine N, Nelson T, Ottoni C, Poirier Stephens Z, Pugh C, Rancourt G, Shareck M, Sims-Gould J, Sones M, Stanley K, Thierry B, Thigpen C, Wasfi R. INTERACT: A comprehensive approach to assess urban form interventions through natural experiments. BMC Public Health. 2019;19(1):51. [https://doi.org/10.1186/s12889-018-6339-z](https://doi.org/10.1186/s12889-018-6339-z)
84. __Fuller D__, Neudorf J, Lockhart S, Plante C, Roberts H, Bandara T, Neudorf C. Individual- and area-level socioeconomic inequalities in diabetes mellitus in Saskatchewan between 2007 and 2012: a cross-sectional analysis. Canadian Medical Association Journal Open. 2019;7(1):E33-E39. [https://doi.org/10.9778/cmajo.20180042](https://doi.org/10.9778/cmajo.20180042)
85. *Hosford, K*., Lear, S A., **Fuller, D**., Teschke, Therrien, S., Winters. Who is in the near market for bicycle sharing? Identifying current, potential, and unlikely users of a public bicycle share program in Vancouver, Canada. BMC Public Health. 2018, 18: 1326. [https://doi.org/10.1186/s12889-018-6246-3](https://doi.org/10.1186/s12889-018-6246-3)
86. Winters M, Fischer J, **Fuller D**, Gauvin L, Whitehurst DGT, Nelson T. Equity In Spatial Access To Bicycling Infrastructure In Mid-Sized Canadian Cities. Transportation Research Board. 2018, 2672:36. [https://doi.org/10.1177/0361198118791630](https://doi.org/10.1177/0361198118791630) 
87. *Hosford, K*., **Fuller, D**., Lear, S A., Teschke, K., Gauvin, L., Brauer, M., Winters. Evaluation of the impact of a public bicycle share program on population bicycling in Vancouver, BC. Preventive Medicine Reports. 2018, 12:176-181. [https://doi.org/10.1016/j.pmedr.2018.09.014](https://doi.org/10.1016/j.pmedr.2018.09.014) 
88. Winters M, Branion-Calles M, Therrien S, **Fuller D**, Gauvin L, Whitehurst DGT, & Nelson T. Impacts of Bicycle Infrastructure in Mid-Sized Cities (IBIMS): protocol for a natural experiment study in three Canadian cities. BMJ Open 2018;8:e019130. [https://dx.doi.org/10.1136/bmjopen-2017-019130](https://dx.doi.org/10.1136/bmjopen-2017-019130)
89. *Alphonsus, K.*, Waldner, C., **Fuller D**. Examining the Association between Area Level Deprivation and Vehicle Collisions. Canadian Journal of Public Health. 2018, 109:43–51. [https://dx.doi.org/10.17269/s41997-018-0036-7](https://dx.doi.org/10.17269/s41997-018-0036-7)
90. Brook JR, Setton EM, Seed E, Shooshtari M, Doiron D, and the CANUE – The Canadian Urban Environmental Health Research Consortium. The Canadian Urban Environmental Health Research Consortium – a protocol for building a national environmental exposure data platform for integrated analyses of urban form and health. BMC Public Health. 2018, 18:114. [https://doi.org/10.1186/s12889-017-5001-5](https://doi.org/10.1186/s12889-017-5001-5)
91. Sones M, **Fuller D**, Kestens Y, Winters M. If we built it, who will come? The case for attention to equity in healthy community design. British Journal of Sports Medicine. 2018, 53(8). [http://dx.doi.org/10.1136/bjsports-2018-099667](http://dx.doi.org/10.1136/bjsports-2018-099667)
92. Pabayo, R., **Fuller, D.**, Lee, E.Y., Horino, M., Kawachi, I. State-level income inequality and meeting physical activity guidelines; differential associations among US men and women, Journal of Public Health. 2018, 2:229–236. [https://doi.org/10.1093/pubmed/fdx082](https://doi.org/10.1093/pubmed/fdx082)
93. **Fuller D.**, Winters M. Income inequalities in Bike Score and bicycle to work mode share in Canadian cities. Journal of Transportation and Health. 2017, 7(B): 264-268. https://doi.org/10.1016/j.jth.2017.09.005 
94. **Fuller D.**, Shareck M, Stanley C. Ethical implications of tracking participants for health research studies with mobile sensing devices. Social Science and Medicine. 2017, 191, 84-88 [https://doi.org/10.1016/j.socscimed.2017.08.043](https://doi.org/10.1016/j.socscimed.2017.08.043)
95. **Fuller, D.**, Buote, R., Stanley, K. A Glossary for Big Data in Population and Public Health: Discussion and Commentary on Terminology and Research Methods. Journal of Epidemiology and Community Health. 2017, 71:1113-1117. [http://dx.doi.org/10.1136/jech-2017-209608](http://dx.doi.org/10.1136/jech-2017-209608) 
96. *Hasselback*, J., Schwandt, M., **Fuller, D.** Choosing Tools for Building Health Spaces: A Global Overview. Cities and Health. 2017, 1: 31-37. [http://dx.doi.org/10.1080/23748834.2017.1309091](http://dx.doi.org/10.1080/23748834.2017.1309091)
97. McGowan, E., **Fuller, D.**, Cutumisu, N., North, S., & Courneya, K. Examining Whether Built Environment Factors are Effect Modifiers in a Randomized Controlled Trial to Increase Physical Activity among Men with Prostate Cancer: The PROMOTE Trial. Supportive Care in Cancer. 2017, 25(10), 2993–2996. [https://doi.org/10.1007/s00520-017-3798-1](https://doi.org/10.1007/s00520-017-3798-1)
98. Pabayo, R., **Fuller, D.**, Goldstein, R.B., Kawachi, I., Gilman, S.E. Income inequality among American states and the conditional risk of post-traumatic stress disorder. Soc Psychiatry Psychiatr Epidemiol 2017, 52: 1195. [https://doi.org/10.1007/s00127-017-1413-x](https://doi.org/10.1007/s00127-017-1413-x) 
99. **Fuller, D.**, Engler-Stringer, R., Muhajarine, N. Retail food environments research: Promising future with more work to be done. Canadian Journal of Public Health. 2016, 107(0): 5622. [http://dx.doi.org/10.17269/cjph.107.5622](http://dx.doi.org/10.17269/cjph.107.5622)
100. Sullivan, E., **Fuller, D.**, Paterson, Q. S., Huffman, S., Challa, S., Woods, R. Emergency Physicians as human billboards for injury prevention: A randomized controlled trial. Canadian Journal of Emergency Medicine. 2016, 19(4):277-284. [http://dx.doi.org/10.1017/cem.2016.366](http://dx.doi.org/10.1017/cem.2016.366)
101. Winters, M., Teschke, K., Brauer, M., **Fuller, D.** Bike Score®: Associations between urban bikeability and cycling behavior in 24 cities. International Journal of Behavioral Nutrition and Physical Activity. 2016, 13:18 [https://doi.org/10.1186/s12966-016-0339-0](https://doi.org/10.1186/s12966-016-0339-0) 
102. **Fuller, D.**, Neudorf, J., Bermedo-Carrasco, S., Neudorf, C. Classifying the population by socio-economic factors associated with support for policies to reduce social inequalities in health. Journal of Public Health.  2016, 38(4), 635-643. [http://www.dx.doi.org/10.1093/pubmed/fdv201](http://www.dx.doi.org/10.1093/pubmed/fdv201) 
103. **Fuller, D.**, Engler-Stringer, R., Muhajarine, N. Examining food purchasing patterns from sales data at a full-service grocery store intervention in a former food desert. Preventive Medicine Reports. 2015, 2:164-169. [https://doi.org/10.1016/j.pmedr.2015.02.012](https://doi.org/10.1016/j.pmedr.2015.02.012)
104. Neudorf, C., **Fuller, D.**, Cushon, J., Glew, R., Turner, H., Ugolini, C. An analytic approach for describing, prioritizing and acting on health inequities at the local level in Canada. CMAJ Open. 2015, 3(4): E366-E372. [http://www.dx.doi.org/10.9778/cmajo.20150049](http://www.dx.doi.org/10.9778/cmajo.20150049) 
105. Muhajarine, N., Katapally, T R., **Fuller, D.**, Stanley, K., Rainham, D. Longitudinal active living research to address obesity in children in transition from preadolescence to adolescence. BMC Public Health. 2015, 15:495 [https://doi.org/10.1186/s12889-015-1822-2](https://doi.org/10.1186/s12889-015-1822-2) 
106. Therrien, S., Winters, M., Teschke, K., **Fuller, D.**, Gauvin, L., Brauer, M. Investigation population-level readiness to use a public bike share systems in Vancouver, BC. Transportation Research Record. 2014, (2468):74-83. [http://docs.trb.org/prp/14-3524.pdf](http://docs.trb.org/prp/14-3524.pdf)
107. **Fuller, D.**, Shareck, M. Canada Post community mailboxes: Implications for health research. Canadian Journal of Public Health. 2014, 105(6):e453-e455. [http://dx.doi.org/10.17269/cjph.105.4721](http://dx.doi.org/10.17269/cjph.105.4721)
108. **Fuller, D.**, Pabayo, R. The relationship between utilitarian walking, utilitarian cycling, and body mass index in a population based cohort study of adults: Comparing random intercepts and fixed effects models. Preventive Medicine. 2014, 69:261-266. [https://doi.org/10.1016/j.ypmed.2014.10.022](https://doi.org/10.1016/j.ypmed.2014.10.022)
109. **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teschke, K., Russo, E. T., Camden, A., Mee, C., Friedman, S. M. Evaluating the impact of environmental interventions across 2 countries: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS) Study protocol. BMC Public Health. 2014, 14:1103. [https://doi.org/10.1186/1471-2458-14-1103](https://doi.org/10.1186/1471-2458-14-1103) 
110. Belanger-Gravel, A., **Fuller, D.**, Gauvin, L., Drouin, L. Implementing a Public Bicycle Share Program: Impact on Perceptions and Support for Public Policies for Active Transportation. Journal of Physical Activity and Health. 2014, 12(4),  477-482. [https://doi.org/10.1123/jpah.2013-0206](https://doi.org/10.1123/jpah.2013-0206)
111. Belanger-Gravel, A., **Fuller, D.**, Gauvin, L., Drouin, L. Association of implementation of a public bicycle share program with intention and self-efficacy: The moderating role of socioeconomic status. Journal of Health Psychology. 2014, 21(6):944-53. [https://doi.org/10.1177/1359105314542820](https://doi.org/10.1177/1359105314542820) 
112. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., & Drouin, L. Impact of implementing a public bicycle share program on the likelihood of collisions and quasi-collisions in Montreal, Canada. Preventive Medicine. 2013, 57(6):920–924. [https://doi.org/10.1016/j.ypmed.2013.05.028](https://doi.org/10.1016/j.ypmed.2013.05.028)
113. **Fuller, D.**, Morency, P. Could a population approach to traffic collisions influence road injury prevention and city planning? Journal of Environmental and Public Health.  2013, 3:1-5. [http://dx.doi.org/10.1155/2013/916460](http://dx.doi.org/10.1155/2013/916460)
114. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. The potential modal shift and health benefits of implementing a public bicycle share program in Montreal, Canada. International Journal of Behavioral Nutrition and Physical Activity,  2013, 10:66. [https://doi.org/10.1186/1479-5868-10-66](https://doi.org/10.1186/1479-5868-10-66)
115. **Fuller, D.** Focus on methods key for advancing population health intervention research. Canadian Journal of Public Health, 2013, 104(1) e95. [http://dx.doi.org/10.17269/cjph.104.3799](http://dx.doi.org/10.17269/cjph.104.3799)
116. **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Impact evaluation of a public bicycle share program on cycling: A case example of BIXI in Montreal, Canada. American Journal of Public Health. 2013, 103(3):e85-92. [http://dx.doi.org/10.2105/AJPH.2012.300917](http://dx.doi.org/10.2105/AJPH.2012.300917) 
117.	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., & Drouin, L. Individual- and Area-Level Disparities in Access to the Road Network, Subway System, and a Public Bicycle Share Program on the Island of Montreal, Canada. Annals of Behavioral Medicine. 2013, 45(1), 95-100.  [http://dx.doi.org/10.1007/s12160-012-9433-y](http://dx.doi.org/10.1007/s12160-012-9433-y) 
118.	**Fuller, D.**, Cummins, S., Matthews S. A. Does transportation mode modify associations between distance to food store, fruit and vegetable consumption and BMI in low income neighborhoods? American Journal of Clinical Nutrition, 2013, 97(1), 167-72. [http://dx.doi.org/10.3945/ajcn.112.036392](http://dx.doi.org/10.3945/ajcn.112.036392) 
119. **Fuller, D.**, Teschke, K., Winters, M., Zanotto, M. (2012) Helmets and bicycling deaths: the importance of context. Canadian Medical Association Journal. 2012. [http://dx.doi.org/10.1503/cmaj.120988](http://www.cmaj.ca/content/184/17/E921/reply#cmaj_el_713394)
120. **Fuller, D.**, Gyurcsik, N.C., Spink, K.S., Brawley, L.R. Prospective examination of self-regulatory efficacy in predicting walking for active transportation: A social cognitive theory approach. Journal of Applied Social Psychology. 2012, 42 (12), 2817-2932. [http://dx.doi.org/10.1111/j.1559-1816.2012.00968.x](http://dx.doi.org/10.1111/j.1559-1816.2012.00968.x)
121. **Fuller, D.**, Potvin, L. Context by treatment interactions as the primary object of study in cluster randomized controlled trials of population health intervention. International Journal of Public Health. 2012, 57(3), 633-636. [http://dx.doi.org/10.1007/s00038-012-0357-x](http://dx.doi.org/10.1007/s00038-012-0357-x)
122.	**Fuller, D.**, Gauvin, L., Fournier, M., Kestens, Y., Daniel, M., Morency, P., & Drouin, L. Reliability and Validity of a Self-Report Measure of Favorability towards Active Living-Friendly Policies (ALF-P) in a Population-based, Cross-sectional Sample of Adults. Journal of Urban Health.  2012, 89(2), 258-269. [http://dx.doi.org/10.1007/s11524-011-9650-x](http://dx.doi.org/10.1007/s11524-011-9650-x)
123.	**Fuller, D.**, Sahlqvist, S., Cummins, S., Ogilvie, D. The impact of public transportation strikes on use of a bicycle share program in London: interrupted time series design. Preventive Medicine. 2012, 54, 74–76. [https://doi.org/10.1016/j.ypmed.2011.09.021](https://doi.org/10.1016/j.ypmed.2011.09.021)
124. **Fuller, D.**, Gauvin, L., Kestens, Y., Daniel, M., Fournier, M., Morency, P., & Drouin, L. Use of a New Public Bicycle Share Program in Montreal, Canada. American Journal of Preventive Medicine. 2011, 41(1), 80–83. [https://doi.org/10.1016/j.amepre.2011.03.002](https://doi.org/10.1016/j.amepre.2011.03.002)
125.	**Fuller, D.**, Sabiston, C., Karp, I., Barnett, T., O’Loughlin, J. School sport opportunities influence physical activity in secondary school and beyond. Journal of School Health, 2011, 81(8), 449-454. [https://doi.org/10.1111/j.1746-1561.2011.00613.x](https://doi.org/10.1111/j.1746-1561.2011.00613.x)
126.	**Fuller, D.**, Hobin, E. P., Hystad, P. & Shareck, M. (Joint Authorship). Challenges to interdisciplinary training for junior space, place and health researchers. Critical Public Health. 2011, 22(1), 1-7. [http://dx.doi.org/10.1080/09581596.2010.520010](http://dx.doi.org/10.1080/09581596.2010.520010)
127.	Meili, R., **Fuller, D.**, & Lydiate, J. Teaching Social Accountability by Making the Links: Qualitative evaluation of student experiences in a service-learning project. Medical Teacher. 2011, 33(8), 659-666. [http://dx.doi.org/10.3109/0142159X.2010.530308](http://dx.doi.org/10.3109/0142159X.2010.530308)
128.	**Fuller, D.**, Muhajarine, N., and Smart Cities, Healthy Kids Research Team. Replication of the Neighborhood Active Living Potential Measure in Saskatoon, Canada. American Journal of Preventive Medicine. 2010, 39(4), 364-367. [https://doi.org/10.1016/j.amepre.2010.05.015](https://doi.org/10.1016/j.amepre.2010.05.015)
129.	Gyurcsik, N.C., Brawley, L.R., Spink, K.S., Brittain, D.R., **Fuller, D.**, & Chad, K. Physical activity in women with arthritis: Examining perceived barriers and self-regulatory efficacy to cope. Arthritis Care and Research. 2009, 61(8), 1087-1094. [https://doi.org/10.1002/art.24697](https://doi.org/10.1002/art.24697)
130.	Forbes, S., **Fuller, D.**, Little, J.P., Krentz, J. Anthropometric and physiological predictors of flat-water 1000m kayak performance in young adolescents and the effectiveness of a high volume training camp. International Journal of Exercise Science. 2008, 2, 106-114. [http://digitalcommons.wku.edu/ijes/vol2/iss2/4/](http://digitalcommons.wku.edu/ijes/vol2/iss2/4/)
131.	Forbes, D. A., Bangma, J., Neilson, C., Forbes, J., **Fuller, D.**, & Furniss, S. Saskatchewan residents’ access to the Cochrane Library. Canadian Journal of Library and Information Practice and Research. 2007, 2(2).

## 13. ARTISTIC WORKS

* _Nil_

## 14. REFEREED CONFERENCE PUBLICATIONS

__Accepted:__   

* _Nil_

__Published:__   

* _Nil_

## 15. PRESENTATIONS

__15.1 Invited Presentations__

1. **Fuller D**. Wearable devices for epidemiologic research. University of Saskatchewan Department of Computer Science. Saskatoon. March 25, 2026.
1. **Fuller D**. Canadian Active Living Environments (Can-ALE 2.0). Public Health Agency of Canada and Infrastructure Canada. Online. February 23, 2026.
1. **Fuller D**. Understanding human mobility. Governement of Manitoba Data Working Group. Online. July 23, 2025.
1. **Fuller D**. 4th Expert meeting on physical activity measurement and the integration of  wearable technology into population health monitoring systems. World Health Organization. Utretch. November 26, 2025.
1. **Fuller D**. Developing Global Guidance on the Use of Wearable Devices for Assessment of Physical Activity, Sedentary, and Sleep Behaviours. World Health Organization. Montreal. June 11, 2025.
1. **Fuller D**. Understanding changes in infrastructure and mobility over time: Examples using Can-ALE and Google Maps. Public Health Agency of Canada. Online. February 26, 2025. 
1. **Fuller D**. Road Safety in Saskatchewan - Panel Presentation. Institute for Transportation Engineers, Saskatchewan Chapter. Saskatoon. October 20, 2025.
1. **Fuller D**. Data Love Week. University of Saskatchewan Data Love Week Webinar. Saskatoon. February 10, 2025.
1. **Fuller D**. International consensus meeting on wearables for measuring mobility in aging populations. Burlington. November 25 & 26, 2024.
1. **Fuller D**. Combining Mass Rapid Transit and Active Transportation for Physical Activity Promotion. Public Health Agency of Canada Active Transportation Group. September 19, 2024.
1. **Fuller D**. Wearable devices for epidemiologic research. McGill University Epidemiology, Biostatistics and Occupational Health Seminar Series. Montreal. March 25, 2024.
1. **Fuller D**. Standardization across devices & applications to public health.., or... What are we doing with our lives? CIHR Institute for Musculoskeletal Health and Arthtitis, Digital Health & Physical Activity Workshop. Vancouver. May 1, 2024.
1. **Fuller D**. Digital Epidemiology: Skills, methods, and lessons for an evolving field. Saskatchewan Epidemiology Association Conference. Regina. October 18th, 2023.
1. **Fuller D**. INTerventions, Equity, Research and Action in Cities Team (INTERACT): Research and knowledge translation for scaling our understanding of health and the built environment. National Collaborating Center for Environments and Health. Online Webinar. November 22nd, 2023.
1. **Fuller D**. CIHR Let's Talk Science. Online. February 10, 2023.
1. **Fuller D**. Diabetes Canada: Managing Obesity with Public Health Interventions. Online November 21, 2022.

_Pre-appointment:_

17. **Fuller D**. Walkability, Health, and Urban Planning. Keep Rolling: An event to promote diversity, inclusion in Saskatoon's cycling community. Saskatoon Cycles. Saturday October 16, 2021.
1. **Fuller D**. The Health Costs and Benefits of Urban Planning. Atlantic Planners Institute. Friday December 4, 2020.
1. **Fuller D**. Emergency Panel on Pedestrian Safety in St. John's. Green New Drinks organized by the St. John's Social Justice Cooperative. Wednesday February 19, 2020.
1. **Fuller D**. Canada Research Chair Panel on Health and Wellbeing. Memorial Univeristy of Newfoundland. Friday November 15, 2019.
1. **Fuller D**. Methods development for cycling research in Canada. NSERC Workshop: Cycling Research Collaboration with Industry in Canadian Context. Calgary, Alberta. February 7-8, 2019.
1. **Fuller D**. Wearable Devices, Physical Activity, Machine Learning, and Automated Detection of Urban Environments. Urban Sustainability and Population Health: Turning Data into Insights. McGill University. Friday October 26, 2018.
1. **Fuller D**. Urban planning interventions to promote physical activity. Joint annual meeting of the Quebec Society of lipidology, nutrition and metabolism (SQLNM), the Cardiometabolic, Diabetes and Obesity network  (CMDO) and the Complications of Obesity at Laval and Sherbrooke Universities (COLosSUS). February 8, 2018. 
1. **Fuller D**. Urban Design for Healthy and Inclusive Cities. Knowledge Exchange on Universal Design and Social Procurement. Coalition of Persons with Disabilities Newfoundland and Labrador. December 10, 2018.
1. **Fuller D**. Designing Health Cities Using Data and Policy. HKR Speaker Series, Memorial University of Newfoundland. May 10, 2018. 
1. Kestens Y, **Fuller D**, Winters M. INTERACT: Interventions, Research and Action in Cities Team. CIHR-IPPH Healthy Cities Think Tank, Toronto, ON. November 30, 2017. 
1. **Fuller D.** The Canadian Urban Environmental Health Research Consortium (CANUE). Urban Public Health Network Annual Meeting, Toronto, ON. November 29, 2017.
1. **Fuller, D.** Family Medicine: A Population Approach with Health. Residency Research Day, Memorial Family Medicine. Memorial University. November 21, 2017. 
1. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax Baseline results. Presentation and meeting with local cycling advocates. Halifax Regional Municipality Transportation Standing Committee. September 28, 2017. 
1. Winters, M, **Fuller, D.** Impacts of bicycle infrastructure in mid-sized cities study: Halifax Baseline results. Presentation and meeting with local cycling advocates. Representatives from the from the Halifax Cycling Coalition, Nova Social Cycles, Halifax Ecology Action Center, and Halifax Regional Health Authority. September 28, 2017. 
1. **Fuller, D.** Cycling in Canadian Communities: From Planning to Implementation.  Invited oral presentation at the Transportation Association of Canada 2017 Fall Technical Meetings. St. John’s, Newfoundland. September 25, 2017.
1. **Fuller, D.** Urban Environments and Health. Invited oral presentation at the Nexus Centre Urban Panel. St. John’s, Newfoundland. October 17, 2016.
1.	**Fuller, D.** Bike share impacts on health. Ontario Public Health Association. April 15, 2015. 
1. **Fuller, D.** Are we succeeding or failing to increase physical activity in the population? Memorial University of Newfoundland. February 19, 2015. 
1. **Fuller, D.** Preliminary Results from the Saskatchewan Equity Study: Focus on Diabetes and Injury. Saskatchewan Epidemiological Association Conference. October 23, 2014. 
1. **Fuller, D.** Cycling in Cities. Western Regional Training Program – University of Saskatchewan. October 10, 2014.  
1. **Fuller, D.** Cycling in Cities. Shad Valley – University of Saskatchewan. July 17, 2013. 
1.**Fuller, D.** Walkability and bikeability for community development. Literally PlaceMaking Conference, Centre for Civic Governance. April 12, 2013.
1.  **Fuller, D.** Les iniquites sociales en sante à Saskatoon entre 1998 et 2011. Forum du Savoir, ACFAS Saskatchewan. March 26, 2013. 
1. **Fuller, D.** Conceptual, methodological and statistical reflections on evaluating a natural intervention with the potential to increase cycling. Sansom Institute Lecture, University of South Australia. November 6, 2012.
1.  **Fuller, D.** Physical activity and public health: Do we speak the same language or are we miles apart. Russ Kisby Memorial Lecture, College of Kinesiology, University of Saskatchewan. February 23, 2012.
1. **Fuller, D.** For a priori to post hoc and back again: A discussion on the planning process and evaluation of a complex intervention involving the implementation of a public bicycle share program in Montreal, Canada. Medical Research Council Epidemiology Research Seminar, Cambridge, England. April 9, 2011. 
1. **Fuller, D.** For a priori to post hoc and back again: A discussion on the planning process and evaluation of a complex intervention involving the implementation of a public bicycle share program in Montreal, Canada. London School of Hygiene and Tropical Medicine Complex Interventions Seminar, London, England. March 30, 2011. 
1. **Fuller, D.** Les Interventions Naturelles et la Sante: Le cas de BIXI. Association Francophone pour le Savoir, Saskatoon, Canada. February 12, 2011. 
1.  **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Facteurs comportementaux associes a la connaissance et l’utilisation des velos en libre-service : Potentiel pour la modification des habitudes de transport et l’augmentation du transport actif. Association Francophone pour le Savoir, Montreal, Canada. May 10, 2010. 
1. **Fuller, D.** BIXI is the new fixie: The public bike share explosion in North American. TEDxMontrealQuartierLatin, Montreal, Canada. October 1, 2010.

__15.2 Contributed Presentations__

1. __Fuller, D.,__, Zhang R, Han J, Stanley K, Bell S. Caractéristiques représentatives de la mobilité géospatiale humaines. ACFAS - Saskatchewan. Saskatoon. March 28, 2026.
1. __Fuller, D.__. AI for Health and Health for AI - Panel Moderator. USask PAW Conference. Saskatoon. October 22, 2025
1. **Fuller, D.** Wearables and Equity. Canadian Engineering Leadership Conference. St. John's. January 5, 2024.
1. Thierry B, Stanley K, Kestens Y, Winters M, __Fuller D.__ Comparing location data from smartphone and dedicated GPS devices. Spatial Knowledge and Information Conference. Banff. Feburary 17, 2023.
1. **Fuller, D.** The Future of Environments and Health Research Capacity: Perspectives from Canada’s
Funding Bodies and Relevant Ministries. CIHR Environments and Health Research Summit. Ottawa. April 17, 2023.
1. **Fuller, D.,** _Ellis R_, Mongeon K. Predicting sleep, Changes in Step Count Accuracy of Wearable Devices with the Continuous Development of New Technology. Canadian Society for Exercise Physiology Conference. Calgary. October 14, 2023.
1. **Fuller, D.** Équité et ville en santé. ACFAS Saskatchewan. Saskatoon. October 4, 2023.

_Pre-appointment:_

8. 2021 October: __Fuller, D.__, Colwell, E., Low, J., _Orychock, K._, _Tobin, M._, _Simango, B._, Buote, R., _van Heerden, D._, _Slade, L._, _Luan, H._, _Taylor, G. A. N._, Cullen, K. Systematic Review of the Reliability and Validity of Commercially Available Wearable Devices for Measuring Steps, Energy Expenditure, and Heart Rate. International Society for Physical Activity and Health (ISPAH).
1. 2021 October: __Fuller D__, __Stanley K__, __Voss C__, __Winters M__, __Firth C__, __Kestens Y__. Combining Global Positioning System and Accelerometer Data: tools, methods, and headaches. International Society for Physical Activity and Health (ISPAH).
1. 2020 October: _Maher, R.A._, Wadden, K., Twells, L., Basset, F., Murphy, S., Murphy, F., Fuller, D., McGowan, E. Exercise Interventions and Fertility Outcomes for Women Experiencing Obesity and Infertility: A Narrative Review. 7th Canadian Obesity Summit. Online.
1. 2020 August: Basset, R. Kelly, L. _Behnamfar, D._ Fuller, D. Self-chosen pace displays a better walking economy when expressed in caloric unit cost. Integrative Physiology of Exercise. American Physiological Association. 
1. 2020 August: Diaz F, Abbassi J, __Fuller D__, Diab E. Canadian Transit Agencies Response to COVID-19: Understanding Strategies, Information Accessibility and the Use of Social Media. Transportation Research Board Annual Meeting. 
1. 2020 April: __Fuller D__, Luan H, Alfosool A, Chen Y. Time weighted approaches for combining GPS and area level data to create individual exposure measures. American Association of Geographers. (Cancelled due to COVID-19). 
1. 2020 February: _Hosford K_, Laberee K, **Fuller D**, Kestens Y, Winters M. Are They Really Interested but Concerned? A Mixed Methods Exploration of the Geller Bicyclist Typology. Transportation Research Board Annual Meeting. 
1. 2020 February: _Bree S_, __Fuller D__, Diab E. Access to Transit? Validating Local Transit Accessibility Measures Using Transit Ridership.  Transportation Research Board Annual Meeting. 
1. 2019 July: **Fuller, D.** Re-visioning Transport and Health Conference and Hackathon. Cambridge, England. https://sites.google.com/view/transportcam2019/home/workshop
1. 2019 June: *Breslin, S.*, Shareck, M., **Fuller, D.** Research ethics for mobile sensing device use by vulnerable populations. At the Intersection of Culture and Method: Designing Feminist Action (DIS 2019).
1. 2019 April: **Fuller, D.**, Zhang, R., Bell, S., Stanely, K. Representative Features of Geospatial Mobility. American Association of Geographers Conference. Washington, DC.
1. 2018 October: Nolan, R., Burton, M., **Fuller, D.**. Smart Cities Challenge: Building a Healthy and Happy City through Collaboration. People, Place, Public Engagement Conference, Memorial University of Newfoundland.
1. 2018 October: **Fuller, D.**, Luan, H., Dorani, F., Rahimipour Anaraki, J., Beheshti Mohtasham, M. Predicting sleep, sedentary behaviour, and physical activity from commercially available wearable devices using Rotation Forest models. International Society for Physical Activity and Health. London, England. 
1. 2018 June: *Lotoski L*, **Fuller D**, Stanley K, Rainham D, Muhajarine N. Precipitation, demographics and built environment features are associated with sedentary behaviour in 9-14-year-old children. 5th International One Health Congress. Saskatoon, Saskatchewan.
1. 2018 June: Mooney, S J. **Fuller, D.** Westreich, J D. Data Sharing in Big Data Epidemiology: 2 Novel-ish Approaches. Society for Epidemiological Research. Baltimore, Maryland.
1. 2018 May: Sones M, Kestens Y, Winters M, **Fuller D**, Muhajarine N, Marriott P, Datta G, Stanley K, Drouin L. Can bigger and better data make healthier cities? Symposium at: Canadian Public Health Association Conference, Montreal, QC.
1. 2018 May: Laberee K, Sones M, Nelson T, Kestens Y, **Fuller D**, Winters M. Recruiting participants for a cohort study on the health impacts of an urban form intervention: Lessons learned. Presentation at: Canadian Public Health Association Conference, Montreal, QC. 
1. 2018 May: Kestens Y, **Fuller D**, Winters M, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Wasfi R, Shareck M, Berscheid J, Gough M, Laberee K, Ottoni C, Poirier Stephens Z, Pugh C, Sones M, Thierry B, Brondeel R. INTERACT: A Comprehensive Urban Intervention Research Framework for Healthy and Sustainable Cities. Canadian Public Health Association Conference, Montreal, QC. 
1. 2018 May: Sones M, Winters M, **Fuller D**, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Kestens Y. Let's INTERACT - Mobilizing data, cities, and citizens for evidence and action on healthy, equitable cities. FUSE Conference on Knowledge Exchange in Public Health, Vancouver, BC.
1. 2018 January: Sones M, Winters M, Kestens Y, **Fuller D**, McKay H, Sims-Gould, J, Lewis P, Datta G, Wasfi R, Lord S, Morency C, Cantinotti M, Muhajarine N, Bell S, Stanley K, Nelson T. Monitoring the Impact of Urban Form Changes on Health and Inequality: The INTERACT Methodology. Cascadia conference. Abbotsford, BC. 
1. 2017 September: Winters M, **Fuller D**, Nelson T, Gauvin L, Whitehurst D, Rusch M, Fyfe M. Impacts of Bicycle Infrastructure in Mid-Sized Cities: Baseline Results. Oral presentation at the Small and Adaptive Cities Conference 2017, St. John's, Canada.
1. 2017 September: Luan, H. **Fuller D.** Developing a National Urban Sprawl Indicator for Canada. Oral presentation at the Small and Adaptive Cities Conference 2017, St. John’s, Canada.
1. 2017 July: Winters M, Fischer J, Therrien S, **Fuller D**, Gauvin L, Whitehurst D, Nelson T. Who benefits? Spatial access to cycling infrastructure in Canadian cities. International Medical Geography Symposium 2017. Angers, France.
1. 2017 June: **Fuller D**, Winters M, Kestens Y, Rondier P. A tale of three cities: A concept mapping exercise to understand the context for urban form changes. Oral presentation at International Society of Behavioral Nutrition and Physical Activity; June 10 2017; Victoria, BC. 
1. 2014 October:	Bandara, T., Williams-Roberts, H., Lockhart, S., Thurairasu, L., **Fuller, D.**, Neudorf, C. Assessing the Effects of the Social Determinants of Health in Rural Saskatchewan.  Oral presentation at the 2014 Safety & Health in Agricultural & Rural Populations: Global Perspectives (SHARP), Saskatoon, Saskatchewan.
1. 2014 March:	**Fuller, D.** Modeling the Impact of Built Environment Interventions: An Introduction to Causal Modeling.  Workshop presentation at the 2014 Active Living Research Conference, San Diego, California.
1. 2012 November:	**Fuller, D.**, Gauvin, L., Kestens, Y. Sociodemographic correlates of public bicycle share program use: An intercept survey of users in Montreal, Canada. Oral presentation at the 2012 International Congress of Physical Activity and Public Health, Sydney, Australia.
1. 2012 June:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining the impact of the BIXI public bicycle share program on the likelihood collisions and quasi-collisions. Oral presentation at the 2012 Velo City International Conference, Vancouver, Canada. 
1. 2012 April:	**Fuller, D.**, Gauvin, L., Datta, T. Kestens, Y., Lacroix, G., Strumpf, E., Kestens, Y., Haddad, S. Studying the impact of natural built environment interventions: Approximating a randomised controlled trial using the regression discontinuity design. Oral presentation at the 2012 Population Health Methods and Challenges conference, Birmingham, England.
1. 2012 April:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining the spatial distribution and relationship between support for policies aimed at active living in transportation and transportation behavior. Oral presentation at the Society of Behavioral Medicine Conference, New Orleans.
1. 2012 March:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Examining Individual and Neighborhood Level Disparities in Access to the Road Network, Public Transit, and a Public Bicycle Share Program in Montreal, Canada. Oral presentation at the Active Living Research Conference, San Diego. 
1. 2011 June:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. From modal shift to multi-modal transportation – Complexity of transportation behaviours associated with implementation of the BIXI public bicycle share program in Montreal. Oral presentation at the Canadian Public Health Association Conference, Montreal, Canada. 
1. 2011 February:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. Evaluating the impact of implementing a public bicycle share program on utilitarian cycling: The case of BIXI in Montreal, Canada. Oral presentation at the Active Living Research Conference, San Diego, California. 
1. 2010 October:	**Fuller, D.**, Gauvin, L., Kestens, Y., Fournier, M., Morency, P., Daniel, M., & Drouin, L. Prevalence and predictors of use a city-sponsored public bicycle share program in Montreal, Canada: The case of BIXI. Oral presentation at the 9th International Conference on Urban Health, New York.
1. 2010 July: **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Tracking the reach of a cycling intervention: The case of a large-scale public bicycle share program. Oral presentation at the World Conference of the International Union for Health Promotion and Education, Geneva, Switzerland.
1. 2010 April:	**Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Validity and Reliability of a Measure of Favorability to Active Living Friendly Policies. Oral presentation at the Society of Behavioral Medicine Conference, Seattle, Washington. 
1. 2009 March:	**Fuller, D.**, Gough, R., Meili, R. (March 2009). Evaluation of student experiences in the Making the Links project. Oral presentation at the International Research conference on Service-Learning and Community Engagement, Ottawa, Ontario.
1. 2008 October:	Forbes, D. A., Bangma, J. Bingham, M., Forbes, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. First Province in Canada to Provide Access to The Cochrane Library: Lessons Learned. XVI Cochrane Colloquium, Freiburg, Germany. 
1. 2008 March:	Gyurcsik, N.C., Brawley, L.R., Spink, K.S., Brittain, D.R., Chad, K., & **Fuller, D.** Managing arthritis using physical activity: Perceived barriers and self-regulatory efficacy predict activity in arthritic women. Oral presentation at the Society of Behavioral Medicine Conference, San Diego, CA.
1. 2007 October:	Forbes, D. A., Bangma, J. Bingham, M., Forbes, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. Promoting and evaluating access to the Cochrane Library. Oral presentation at the Cochrane Colloquium, Sao Paulo, Brazil. 
1. 2006 October:	Forbes, D. A., Bangma, Neilson, C., **Fuller, D.**, Adamson, J.,Bingham, M. Strategies that promote the use of the Cochrane Library. Oral presentation at the Cochrane Colloquium, Dublin, Ireland. 
1. 2005 November:	**Fuller, D.**, & Gyurcsik, N. C. The coach-athlete relationship: Perceptions of coaching behaviour in individual sports. Oral presentation at the Sport Leadership Conference, Quebec, Quebec. 
1. 2005 December:	Forbes, D. A., Bangma, J. Bingham, M., Adamson, J., **Fuller, D.**, Marshall, C., Furniss, S., & Clark, K. Do province-wide access to the Cochrane Library and training sessions make a difference? Oral presentation at the Canadian Cochrane Symposium, Montreal, Quebec. 

__15.3 Poster Presentations__

* _Nil_

_Pre-appointment:_

1. 2018 February: Kestens Y, Fuller D, Winters M, Bell S, Cantinotti M, Datta G, Lewis P, Lord S, McKay H, Morency C, Muhajarine N, Nelson T, Sims-Gould J, Stanley K, Wasfi R, Shareck M, Berscheid J, Gough M, Laberee K, Ottoni C, Poirier Stephens Z, Pugh C, Sones M, Thierry B, Brondeel R, Thigpen C, Luan H. Monitoring The Impact of Urban Form Changes on Health and Inequality: The INTERACT Methodology. Active Living Research Conference, Banff, AB. (First prize for poster presentation)
1. 2017 June:	Winters M, **Fuller D**. Income inequalities in Bike Score and bicycle to work mode share in Canadian cities. Poster at the International Society for Behavioral Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 10, 2017.
1. 2017 June: 	Winters M, Therrien S, Branion-Calles M, **Fuller D**, Gauvin L, Whitehurst D, Nelson T. Laying down the context: Baseline findings from natural experiment study of Biketoria, a city-wide cycling network in Victoria, British Columbia. Poster at the International Society for Behavioral Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 10, 2017.
1. 2017 June:	Hosford K, **Fuller D**, Gauvin L, Brauer M, Teschke K, Winters M. Assessing the Modal Impacts of Public Bikeshare Systems: A Comparison of Survey Tools. Poster at the International Society for Behavioural Nutrition and Physical Activity Annual Meeting, Victoria, Canada, June 7-10 2017.
1. 2017 June:	**Fuller, D.**., McGowan, E., Cutumisu, N., North, S., & Courneya, K. (2017, June). The Role of the Built Environment in a Randomized Controlled Trial to Increase Physical Activity among Men with Prostate Cancer: The PROMOTE Trial. Poster at the International Society for Behavioural Nutrition and Physical Activity (ISBNPA) 2017 Annual Meeting, Victoria, British Columbia.
1. 2016 November: **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teshcke, K. Evaluating the impact of implementing public bicycle share programs on cycling: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Congress on Physical Activity and Public Health. Bangkok, Thailand. 
1. 2016 November: **Fuller, D.**, Gauvin, L., Dube, A-S., Winters, M., Teshcke, K. Evaluating the impact of implementing public bicycle share programs on collisions: The International Bikeshare Impacts on Cycling and Collisions Study (IBICCS). International Congress on Physical Activity and Public Health. Bangkok, Thailand. 
1. 2016 May:	Bernatchez, A.C., Dube, A.S, Gauvin, L., **Fuller, D.**, Drouin, L. Knowing About a Public Share Program in Montreal, Canada : Is Diffusion of Innovation and Proximity Enough for Equitable Awareness? Student Conference in Population Health. University of Ottawa.
1. 2016 June:	Ramsay, D., **Fuller, D.** The impact of social position on the relationship between active travel use and body mass index in a sample of urban Canadians. Canadian Public Health Association.
1. 2016 June:	Alphonsus, K., **Fuller, D.**, Waldner, C.. Examining the Association between Area Level Deprivation and Severity of Vehicle Collisions. Canadian Public Health Association.
1. 2015 November:	**Fuller, D.**, Ness, E., Joseph, M., Pswarayi, H., Van Nest, J., Grewal, J., Amery, A., Anstruther. S. Values and the measurement of social inequalities in health. Saskatchewan Epidemiology Association Conference, Regina, Saskatchewan. 
1. 2015 July:	**Fuller, D.**, Shareck, M. Canada Post community mailboxes: Implications for health research. International Medical Geography Symposium, Vancouver, Canada. 
1. 2015 April: **Fuller, D.**, Pabayo, R. The relationship between utilitarian walking, utilitarian cycling, and body mass index in a population based cohort study of adults: Comparing random intercepts and fixed effects models. Transportation Research Board, Washington, DC. 
1. 2015 March:	Lotoski, L., Muhajarine, N., Ridalls, T., **Fuller, D.**, Katapally, T., Stanley, K., A 4-season longitudinal study examining the association between seasonality and sedentary behaviour in 8-11 year old Canadian children. Poster presentation at the Health & Life Sciences Research Conference, Saskatoon, Saskatchewan.
1. 2013 July:	Datta, G., Barnett, T., **Fuller, D.** Are physical activity opportunities at school associated with self-reported and accelerometry estimated physical activity among elementary school students? Poster presentation at the 2013 Society for Epidemiological Research Conference, Boston, Massachusetts.
1. 2010 May:	**Fuller, D.**, Sabiston, C., Karp, I., Barnett, T., O’Loughlin, J. School sport opportunities influence physical activity in secondary school and beyond. Poster presentation at the International Congress on Physical Activity and Public Health, Toronto, Ontario.
1. 2010 February: **Fuller, D.**, Gauvin, L., Kestens, Y., Morency, P., Daniel, M., & Drouin, L. Behavioral Correlates of Awareness of a Large-scale, Self-service Bicycle Program: Potential for a Modal Shift Toward Active Transportation. Poster presentation at the Active Living Research Conference, San Diego, California.
1. 2009 April:	**Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. Walking for active transportation: Using social cognitive theory to examine differences between successful and less successful users. Poster presentation at the annual Society for Behavioral Medicine Conference, Montreal, QC. 
1. 2008 June: **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S. A prospective examination of social cognitive predictors of walking for active transportation. Poster presentation at the North American Society for the Psychology of Sport and Physical Activity Conference, Niagra Falls, ON.
1. 2008 March:	Bloomquist, C.D., **Fuller, D.**, Gyurcsik, N.C., Brawley, L.R., Spink, K.S., & Bray, S.R. Active Transportation Use By Sufficiently and Insufficiently Active First-Year University Students. Poster presentation at the Society of Behavioral Medicine Conference, San Diego, CA.
1. 2007 March: Bloomquist, C. D. & **Fuller, D.** Active Transportation: Sustainable physical activity options for university students. Poster presentation at the Health & Life Sciences Research Conference, Saskatoon, Saskatchewan.

## 16. REPORTS AND OTHER OUTPUTS



1. World Health Organization. Measuring Physical Activity in Adults Using Wearable Technologies: Report of a Scientific Meeting. 10-12, June 2025, Montreal, Canada. 
1. Exon Smith K, Chapple K, Fagan D, Siemiatycki M. Canada's Urban Infrastructure Deficit: Toward democracy & equitable prosperity. 2024. Chapter 8: Moving Healthy Cities Forward - The state of cycling infrastructure in Canada. __Fuller D__, Winters M, Kestens Y, Mamiya H, Sones M, Thierry B, Poirier Stephens Z. [https://stateofcitiessummit.ca/report](https://stateofcitiessummit.ca/report).
1. _Brondeel R_, _Rahimipour Anaraki J_, _KhataeiPour S_, __Fuller D__. activityCounts: Generate ActiLife Counts. [https://cran.r-project.org/web/packages/activityCounts/index.html](https://cran.r-project.org/web/packages/activityCounts/index.html)

_Pre-appointment:_

4. Holloway A, Chafe B, Fuller D.  Health and economic benefits of walking in St. John’s, Newfoundland and Labrador. [http://www.beaplab.com/home/wp-content/uploads/2020/08/HEAT-St-Johns.pdf](http://www.beaplab.com/home/wp-content/uploads/2020/08/HEAT-St-Johns.pdf)
1. Vanlaar W, Woods-Fry H, Mainegra Hing M, Robertson R, Laberee K, Ferster C, and  Nelson T. Bikemaps.org: Final report on the evaluation of a crowdsourced tool to compile, analyze and communicate data about cycling safety. 2020. Traffic Injury Research Foundation. 
1. Fuller D, Butt R. Report from the Bicycle Network Design Jam. 2018 ISBN: 978-0-88901-488-6. [http://www.beaplab.com/home/wp-content/uploads/2019/01/Design-Jam.pdf](http://www.beaplab.com/home/wp-content/uploads/2019/01/Design-Jam.pdf)
1. _Tobin M_, __Fuller D__. Developing Apps for Population Health Research. 2019. ISBN: 978-0-88901-487-9. [http://www.beaplab.com/home/wp-content/uploads/2019/01/App-Review.pdf](http://www.beaplab.com/home/wp-content/uploads/2019/01/App-Review.pdf)
1. Loucks-Atkinson, A, Yi, J.K., Hawkins, K., Loeffler, TA, **Fuller, D.** & Sullivan, A. 2017. A vision for an inclusive Newfoundland and Labrador. In R.E. Ommer, B. Neis, & D. Brake (Eds.), Asking the big questions: Reflections on a sustainable post oil-dependent Newfoundland and Labrador (pp. 46-54). St. John’s, NL: Harris Centre, Memorial University.
1. Neudrof, C., **Fuller, D.**, Neudorf, J., Lockhart, S., Plante, C., Williams-Roberts, H., Thurairasu, L. 2016. Changes in Social Inequalities in Health Over Time in Saskatchewan. [https://saskatchewanequitystudy.com/](https://saskatchewanequitystudy.com/)
1. **Fuller, D.**, Follwell, E. J., Jones, C., Sharp, K., Meili, R. 2015. Health in All Policies: Description of tools and practices with recommendations for the Government of Newfoundland and Labrador.
1. Neudorf, C., Kryzanowski, J., Marko, J., Ugolini C., Brown A., **Fuller, D.**, Murphy L. 2015. Better Health for All Series 6: Health behaviours and risk conditions. Saskatoon: Saskatoon Health Region. Accessed March 23, 2015: [https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2015_shr_series6_hsrfull.pdf](https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2015_shr_series6_hsrfull.pdf)
1. Neudorf, C., Kryzanowski, J., Turner, H., Cushon, J., **Fuller, D.**, Ugolini, C., Murphy, L., Marko, J. 2014. Better Health for All Series 3: Advancing Health Equity in Health Care. Saskatoon: Saskatoon Health Region. Accessed January 8, 2015: [https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2014_shr_phase3_advancing_healthequity_healthcare_series.pdf](https://www.saskatoonhealthregion.ca/locations_services/Services/Health-Observatory/Documents/Reports-Publications/2014_shr_phase3_advancing_healthequity_healthcare_series.pdf)

## 17. BOOK REVIEWS

* _Nil_

## 18. INTELLECTUAL PROPERTY

* _Nil_

## 19. RESEARCH FUNDING HISTORY

FORMAT: Applicant, A.A. (PI) & Team Member, B.B. (Start Year – End Year). Title of project,
Amount (Currency). Agency Program, Agency(ies). Amount of funding received by you where
multiple investigators are involved.

EXAMPLE: Smith, C.D. (PI) & Jones, A.B. (2015 - 2016). Effects of H1N1 flu in Adolescents.
$50,000. RUH Foundation Fund, 2015 - 2016. $25,000 to A.B. Jones.


1. __Fuller D.__, Rochon, M. A Human Activity Recognition Artificial Intelligence Research Cluster. USask Artificial Intelligence Research & Innovation: 2026 Research Capacity Building Grant. 2026-2027. $15,000 (CAD) to __D Fuller.__
1. __Fuller D.__. INTerventions, Equity, Research, and Action in Cities Team (INTERACT): Health and
economic impacts of sustainable transportation interventions. USask College of Medicine: CIHR Project Grant Bridge Fund. $50,000 (CAD) to __D Fuller.__
1. __Fuller D.__. Wearable devices for health research. USask College of Medicine Start Up Funds CIHR Project Grant Bridge Fund. 2026-2028. $50,000  (CAD) to __D Fuller.__
1. __Fuller D.__ INTerventions, Equity, Research, and Action in Cities Team (INTERACT), Open Science for Healthy Cities. CIHR-IMHA Inclusive Research Excellence Prizes - Open Science. 2024. $25,000  (CAD) to __D Fuller.__
1. __Fuller D.__ A working group for equity, measurement, and methods for commercial wearable devices among children and youth. Saskatchewan Health Research Foundation Mobilize Grant. 2023–2024. $10,000  (CAD) to __D Fuller.__
2. __Fuller D.__ Applying data driven tools to understand healthy sustainable transportation in Saskatoon. USask Research Junction. 2023–2024 $30,000  (CAD) to __D Fuller.__
1. Co-Applicant (September 2023–September 2027). Multilevel estimation of the relative impacts of social determinants on income-related health inequalities in urban Canada: Toward a new Canadian Social Determinants Urban Laboratory. CIHR Project Grant. 2023-2027. $940,000 (CAD), $60,000 to __D Fuller.__
3. Brook J, __Fuller D__, Gauvin L, Martin A, Padmaja S. Environment Health Summit 2023. 2022. $40,000, $0 (CAD) to __D Fuller.__
1. Winters, M. _Fuller, D.__, Cloutier, M., Afzal, S., Badeau, N., Churchill, T., Coleman, J., Fridman, L., Laberee, K., MacIsaac, D., Malzer, J., Schulz, C., Semple, I., Simor, D., Spandonide, B., Walker, K., Webb, S., Cloutier, M.-S., Fuller, D.L., Harris, M.A., Howard, A.W., Kestens, Y., Kirk, S.F., Macpherson, A., Moore, S.A., Rothman, L., Shareck, M. & Tomasone, J.R. Building CapaCITY/É for Sustainable Transportation. CIHR Team Grant: HCIS – Population and Public Health, 2022–2028. $3,000,000 (CAD), $400,000 to __D Fuller.__
1. Jung, M.E., Alexander, A., Casmey, S., Coes, C., Compton, S., Cullen, L., Hartley-Folz, S., Hughes, C.L., Kyle, J.L., Logan, S.M., Paterson, K., Squires, S., Bean, C., Fuller, D.L., Li, L.C., Martin Ginis, K.A., Sherifali, D.T. & Witteman, H.M. Small Steps for Big Changes: Implementing an Evidence-Based Diabetes Prevention Program into Diverse Urban Communities. CIHR Team Grant: HCIS – Type 2 Diabetes Prevention, 2022–2028. $2,958,703 (CAD), $0 to __D Fuller.__
3. __Fuller D.__, Bracewell D, Cloutier I, Kestens, Y, James M, Webb S, Winters M. INTerventions, Equity, Research and Action in Cities Team (INTERACT). 2021-2026. $918,000 (CAD) to __D Fuller.__
3. __Fuller D.__, Blais S, McDonald J, Beck B, Shareck M, Romasone, J. INTErventions, Research, and Action in Cities Team for Implementation Science (INTERACT IS). Team Grant: HCIS - LOI - Population and public health. 2021. $25,000 (CAD) to __D Fuller.__
1. Rosella, L.C., Anderson, M., Buckeridge, D.L., Fan, L., Lee, J., Lix, L.M. & Osgood, N.D., __Fuller D__. Artificial Intelligence for Public Health (AI4PH) Training Platform. CIHR Training Grant: Health Research Training Platform – AI, Public Health and Equity. 2021–2027. $2,394,219, $0 to __D Fuller.__

_Pre-appointment:_

14. Applicant, Principal Applicant (August 2021–August 2026). Canada Research Chair - Renewal, $500,000 (CAD). CRC, CRC. Amount received: $500,000.
1. Applicant, Co-Applicant (September 2020–March 2024). Examining the impacts of the downtown Sherbrooke (QC) revitalization project on health equity among young adults: a mixed-methods evaluation, $100,000 (CAD). CIHR, CIHR. Amount received: $0.
2. Applicant, Co-Applicant (September 2020–March 2024). Equity in Built Environment Surveillance Tool (E-BEST), $1,000,000 (CAD). Public Health Agency of Canada - Enhanced Surveillance for Chronic Disease Program, Public Health Agency of Canada. Amount received: $0.
3. Applicant, Co-Applicant (September 2020–March 2024). Citizen Mapping of Microscale Barriers to Mobility, $681,992 (CAD). Public Health Agency of Canada - Enhanced Surveillance for Chronic Disease Program, Public Health Agency of Canada. Amount received: $40,000.
4. Applicant, Co-Applicant (June 2020–June 2021). Dietary change during COVID‑19: A population-based study in Atlantic Canada to build evidence for government economic and social policy responses, $267,020 (CAD). CIHR COVID-19 Rapid Research - Social Policy and Public Health Response, CIHR. Amount received: $0.
5. Applicant, Co-Applicant (August 2019–August 2024). AI for public health (AI4PH): A focus on equity and prevention, $525,000 (CAD). Operating Grant: CIHR Summer Institute on Equitable AI for Public Health, CIHR. Amount received: $0.
6. Applicant, Co-Applicant (October 2019–October 2022). Impacts of the new Réseau Express Métropolitain (REM) on mobility, health and equity: A pre-post intervention study, $441,002 (CAD). CIHR-NSERC Collaborative Health Research Projects, CIHR/NSERC. Amount received: $0.
7. Applicant, Co-Applicant (February 2020–October 2020). Training for Healthy INterdisciplinary Knowledge in Cities (THINK-Cities), $25,000 (CAD). Training Grant: CIHR-NSERC-SSHRC Healthy Cities Research Training Platform (HCRTP), CIHR/NSERC/SSHRC. Amount received: $0.
8. Applicant, Principal Investigator (March 2019–March 2020). Creating and comparing activity space measures to understand how walkability, urban sprawl, and public transit accessibility are associated with location-based physical activity in 4 Canadian cities, $100,000 (CAD). CIHR, CIHR. Amount received: $100,000.
9. Applicant, Co-Applicant (May 2019–April 2020). Smart Cities, Healthy Citizens? Optimizing Health and Equity in City Policy Making, $24,985 (CAD). CIHR, CIHR. Amount received: $0.
10. Applicant, Co-Applicant (March 2019–March 2023). Sustainable Healthy Cities: The Interplay between Urban Interventions, Gentrification, and Population Health, $527,851 (CAD). CIHR, CIHR. Amount received: $6,000.
11. Applicant, Team Lead (April 2017–April 2021). Canadian Urban Environmental Health Research Consortium, $5,000,000 (CAD). CIHR, CIHR. Amount received: $45,000.
12. Applicant, Co-Principal Investigator (December 2017–December 2021). Environments and Health INTERACT: INTErventions, Research, and Action in Cities Team, $2,000,000 (CAD). CIHR, CIHR. Amount received: $106,256.
13. Applicant, Principal Investigator (August 2016–August 2021). Canada Research Chair in Population Physical Activity, $500,000 (CAD). CRC, CRC. Amount received: $500,000.
14. Applicant, Principal Investigator (August 2016–August 2021). Newfoundland Research and Development Corporation CRC Leverage, $100,000 (CAD). RDC, RDC. Amount received: $100,000.
15. Applicant, Principal Investigator (August 2016–August 2018). Canadian Foundation for Innovation John R. Evans Leaders Fund, $252,638 (CAD). CFI, CFI. Amount received: $252,638.
16. Applicant, Principal Investigator (August 2016–August 2018). Newfoundland Research and Development Corporation CFI Leverage Grant, $100,000 (CAD). RDC, RDC. Amount received: $100,000.
17. Applicant, Co-Applicant (August 2016–August 2021). Impacts of City-Wide Bicycle Infrastructure Investment on Population Health & Health Equity, $428,400 (CAD). CIHR, CIHR. Amount received: $0.
18. Applicant, Co-Applicant (December 2017–December 2021). Multisectoral Urban Systems for Health and Equity in Canadian Cities, $2,000,000 (CAD). CIHR, CIHR. Amount received: $0.

## 20. PRACTICE OF PROFESSIONAL SKILLS

* Generative AI 101. Saskatchewan Population Health and Evaluation Research Unit. 

## 21. ADMINISTRATIVE SERVICE

__21.1 University Committees__

__21.2 College and Departmental Committees__

__21.3 Other Administrative Service__

## 22. PROFESSIONAL OR ASSOCIATION OFFICES AND COMMITTEE ACTIVITY OUTSIDE UNIVERSITY OF SASKATCHEWAN

NOTE: Include activities related to your area of expertise or discipline, such as an editorship, participation on
a professional or conference organizing committee, membership on a board, etc.



## 23. PUBLIC AND COMMUNITY CONTRIBUTIONS

__23.1 University Related:__

__23.2 Non University Related:__

## 24. OTHER ACTIVITIES

NOTE: Include extension or consulting activities, such as addresses, tours, office visits, media events, etc.
Typically, these activities would involve producers or end users rather than peers. Entries may be in
paragraph or point form and should include the type of work, relevant dates, and whether the work was done
gratis or on a fee-for-service basis.


